<script lang="ts">
	import { inertia, router } from "@inertiajs/svelte";
	import AppLayout from "@layouts/AppLayout.svelte";
	import type { Tagihan, User } from "@lib/types";
	import { getCSRFToken } from "@lib/utils/csrf";
	import { Check, Eye, MessageCircle, RefreshCw, Search, X } from "lucide-svelte";

	interface Props { user?: User; tagihan?: Tagihan[]; filter?: { status?: string; search?: string; tanggal_dari?: string; tanggal_sampai?: string; kelas_id?: string; angkatan_kelas?: string; guru_id?: string; frekuensi?: string; level?: string; gender?: string; bulan_ke?: string }; }
	let props: Props = $props();
	let tagihan = $derived(props.tagihan ?? []);
	let filter = $state(props.filter ?? {});
	let search = $state(filter.search ?? ""); let status = $state(filter.status ?? ""); let tanggalDari = $state(filter.tanggal_dari ?? ""); let tanggalSampai = $state(filter.tanggal_sampai ?? ""); let kelasID = $state(filter.kelas_id ?? ""); let angkatan = $state(filter.angkatan_kelas ?? ""); let guruID = $state(filter.guru_id ?? ""); let frekuensi = $state(filter.frekuensi ?? ""); let level = $state(filter.level ?? ""); let gender = $state(filter.gender ?? ""); let bulanKe = $state(filter.bulan_ke ?? "");
	let selected = $state<Tagihan | null>(null); let metode = $state(""); let catatan = $state(""); let tanggalBayar = $state(new Date().toISOString().slice(0, 10));
	const rupiah = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);
	function applyFilter() { const p = new URLSearchParams(); const values = { search, status, tanggal_dari: tanggalDari, tanggal_sampai: tanggalSampai, kelas_id: kelasID, angkatan_kelas: angkatan, guru_id: guruID, frekuensi, level, gender, bulan_ke: bulanKe }; for (const [key, value] of Object.entries(values)) if (value) p.set(key, value); router.get(`/app/keuangan/tagihan?${p}`); }
	function lunasi() { if (!selected) return; router.put(`/app/keuangan/tagihan/${selected.id}/lunas`, { tanggal_bayar: tanggalBayar, metode, catatan }, { onSuccess: () => { selected = null; } }); }
	function batal(t: Tagihan) { if (confirm(`Batalkan tagihan ${t.santri_nama}?`)) router.put(`/app/keuangan/tagihan/${t.id}/batal`, { catatan: "Dibatalkan oleh petugas" }); }
	async function followUp(t: Tagihan) { if (!t.no_wa) return; const popup = window.open("", "_blank"); const response = await fetch(`/app/keuangan/tagihan/${t.id}/follow-up`, { method: "POST", headers: { "X-XSRF-TOKEN": getCSRFToken() } }); const data = await response.json(); if (!response.ok) { popup?.close(); alert(data.error ?? "Gagal membuat tautan WhatsApp"); return; } if (popup) popup.location.href = data.url; else window.location.href = data.url; }
	function sync() { router.post("/app/keuangan/tagihan/sync"); }
	function statusClass(value: string) { return value === "lunas" ? "bg-success/10 text-success" : value === "batal" ? "bg-neutral-200 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-300" : value === "terlambat" ? "bg-error/10 text-error" : "bg-warning/10 text-warning"; }
</script>

<AppLayout user={props.user}>
	<main class="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">
		<header class="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p class="text-xs font-bold tracking-[0.16em] uppercase text-brand-600 dark:text-brand-400">Keuangan</p><h1 class="mt-2 text-3xl font-bold text-neutral-900 dark:text-white">Daftar tagihan</h1><p class="mt-2 text-sm text-neutral-600 dark:text-neutral-400">{tagihan.length} tagihan sesuai filter. Filter angkatan menggunakan Angkatan Kelas.</p></div>{#if props.user?.role === "keuangan" || props.user?.role === "super_admin"}<button onclick={sync} class="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-brand-500/30 text-brand-700 dark:text-brand-300 font-semibold text-sm"><RefreshCw size="16" /> Sinkronkan tagihan</button>{/if}</header>
		<form onsubmit={(e) => { e.preventDefault(); applyFilter(); }} class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 p-4 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-925"><div class="lg:col-span-2 relative"><Search size="16" class="absolute top-3 left-3 text-neutral-400" /><input bind:value={search} placeholder="Nama atau ID mahasantri" class="w-full pl-9 pr-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm outline-none" /></div><select bind:value={status} class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm"><option value="">Semua status</option><option value="belum_bayar">Belum bayar</option><option value="terlambat">Terlambat</option><option value="lunas">Lunas</option><option value="batal">Batal</option></select><input bind:value={bulanKe} type="number" min="1" placeholder="Bulan ke-" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><input type="date" bind:value={tanggalDari} title="Tanggal tagih dari" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><input type="date" bind:value={tanggalSampai} title="Tanggal tagih sampai" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><input bind:value={angkatan} placeholder="Angkatan" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><input bind:value={level} placeholder="Level" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><select bind:value={frekuensi} class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm"><option value="">Semua frekuensi</option><option value="1x/pekan">1x/pekan</option><option value="2x/pekan">2x/pekan</option></select><select bind:value={gender} class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm"><option value="">Semua gender</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select><input bind:value={kelasID} type="number" min="1" placeholder="ID kelas" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><input bind:value={guruID} type="number" min="1" placeholder="ID guru" class="px-3 py-2.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 text-sm" /><button class="px-4 py-2.5 rounded-xl bg-brand-600 text-white text-sm font-semibold">Terapkan</button></form>
		<div class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-925 overflow-x-auto"><table class="w-full min-w-[940px] text-sm"><thead class="text-left text-xs uppercase tracking-wider text-neutral-500 border-b border-neutral-200 dark:border-neutral-800"><tr><th class="p-4">Santri</th><th class="p-4">Kelas</th><th class="p-4">Periode</th><th class="p-4">Nominal</th><th class="p-4">Tagih / Tempo</th><th class="p-4">Status</th><th class="p-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-neutral-100 dark:divide-neutral-800/70">{#each tagihan as t (t.id)}<tr><td class="p-4"><p class="font-semibold text-neutral-900 dark:text-white">{t.santri_nama}</p><p class="text-xs text-neutral-500">{t.id_mahasantri || "-"} · {t.frekuensi}</p></td><td class="p-4 text-neutral-600 dark:text-neutral-300">{t.kelas_nama || "-"}<br /><span class="text-xs text-neutral-500">{t.guru_nama}</span></td><td class="p-4">Bulan {t.bulan_ke}<br /><span class="text-xs text-neutral-500">P-{t.pertemuan_ke}</span></td><td class="p-4 font-mono">{rupiah(t.nominal)}</td><td class="p-4 text-xs">{t.tanggal_tagih}<br /><span class="text-neutral-500">{t.jatuh_tempo || "-"}</span></td><td class="p-4"><span class="inline-flex px-2 py-1 rounded-full text-xs font-bold {statusClass(t.status)}">{t.status.replace("_", " ")}</span></td><td class="p-4"><div class="flex justify-end gap-1"><a href={`/app/keuangan/tagihan/${t.id}`} use:inertia title="Detail" class="p-2 text-neutral-500 hover:bg-neutral-100 dark:hover:bg-neutral-800 rounded-lg"><Eye size="17" /></a>{#if t.status === "belum_bayar" || t.status === "terlambat"}<button onclick={() => { selected = t; metode = ""; catatan = ""; }} title="Tandai lunas" class="p-2 text-success hover:bg-success/10 rounded-lg"><Check size="17" /></button>{/if}<button onclick={() => followUp(t)} disabled={!t.no_wa} title={t.no_wa ? "Follow-up WhatsApp" : "Nomor WA belum diisi"} class="p-2 text-brand-600 hover:bg-brand-500/10 rounded-lg disabled:opacity-30"><MessageCircle size="17" /></button>{#if t.status !== "lunas" && t.status !== "batal"}<button onclick={() => batal(t)} title="Batalkan" class="p-2 text-error hover:bg-error/10 rounded-lg"><X size="17" /></button>{/if}</div></td></tr>{:else}<tr><td colspan="7" class="p-14 text-center text-neutral-500">Tidak ada tagihan yang ditemukan.</td></tr>{/each}</tbody></table></div>
	</main>
	{#if selected}<div class="fixed inset-0 z-50 bg-neutral-950/55 flex items-center justify-center p-4"><section class="w-full max-w-md rounded-2xl bg-white dark:bg-neutral-925 p-6 shadow-xl"><div class="flex justify-between gap-4"><div><h2 class="text-xl font-bold text-neutral-900 dark:text-white">Tandai lunas</h2><p class="text-sm text-neutral-500 mt-1">{selected.santri_nama} · {rupiah(selected.nominal)}</p></div><button onclick={() => selected = null} class="text-neutral-500"><X /></button></div><div class="mt-5 space-y-3"><label class="block text-sm font-medium">Tanggal bayar<input type="date" bind:value={tanggalBayar} class="mt-1 w-full px-3 py-2 rounded-lg bg-neutral-100 dark:bg-neutral-800" /></label><label class="block text-sm font-medium">Metode<input bind:value={metode} placeholder="Contoh: transfer BCA" class="mt-1 w-full px-3 py-2 rounded-lg bg-neutral-100 dark:bg-neutral-800" /></label><label class="block text-sm font-medium">Catatan<textarea bind:value={catatan} class="mt-1 w-full px-3 py-2 rounded-lg bg-neutral-100 dark:bg-neutral-800"></textarea></label><button onclick={lunasi} class="w-full py-2.5 rounded-xl bg-success text-white font-semibold">Simpan pelunasan</button></div></section></div>{/if}
</AppLayout>
