// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: absensi.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countAbsensiByStatus = `-- name: CountAbsensiByStatus :many
SELECT a.status, COUNT(*) AS total
FROM absensi a
JOIN pertemuan p ON a.pertemuan_id = p.id
WHERE p.kelas_id = ?
GROUP BY a.status
`

type CountAbsensiByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountAbsensiByStatus(ctx context.Context, kelasID int64) ([]CountAbsensiByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countAbsensiByStatus, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAbsensiByStatusRow
	for rows.Next() {
		var i CountAbsensiByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAbsensiSantriByKelas = `-- name: CountAbsensiSantriByKelas :many
SELECT a.santri_id, s.nama AS santri_nama,
    COUNT(*) AS total,
    SUM(CASE WHEN a.status = 'hadir' THEN 1 ELSE 0 END) AS total_hadir,
    SUM(CASE WHEN a.status = 'izin' THEN 1 ELSE 0 END) AS total_izin,
    SUM(CASE WHEN a.status = 'sakit' THEN 1 ELSE 0 END) AS total_sakit,
    SUM(CASE WHEN a.status = 'alpa' THEN 1 ELSE 0 END) AS total_alpa,
    SUM(CASE WHEN a.status = 'telat' THEN 1 ELSE 0 END) AS total_telat
FROM absensi a
JOIN pertemuan p ON a.pertemuan_id = p.id
JOIN santri s ON a.santri_id = s.id
WHERE p.kelas_id = ? AND p.status = 'selesai'
GROUP BY a.santri_id
ORDER BY s.nama
`

type CountAbsensiSantriByKelasRow struct {
	SantriID   int64
	SantriNama string
	Total      int64
	TotalHadir sql.NullFloat64
	TotalIzin  sql.NullFloat64
	TotalSakit sql.NullFloat64
	TotalAlpa  sql.NullFloat64
	TotalTelat sql.NullFloat64
}

func (q *Queries) CountAbsensiSantriByKelas(ctx context.Context, kelasID int64) ([]CountAbsensiSantriByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, countAbsensiSantriByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAbsensiSantriByKelasRow
	for rows.Next() {
		var i CountAbsensiSantriByKelasRow
		if err := rows.Scan(
			&i.SantriID,
			&i.SantriNama,
			&i.Total,
			&i.TotalHadir,
			&i.TotalIzin,
			&i.TotalSakit,
			&i.TotalAlpa,
			&i.TotalTelat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriAlpaBerturutByKelas = `-- name: CountSantriAlpaBerturutByKelas :many
SELECT s.id, s.nama, COUNT(*) AS total_alpa
FROM absensi a
JOIN pertemuan p ON a.pertemuan_id = p.id
JOIN santri s ON a.santri_id = s.id
WHERE p.kelas_id = ?
  AND a.status = 'alpa'
  AND p.tanggal >= date('now', '-30 days')
GROUP BY s.id
HAVING COUNT(*) >= 3
ORDER BY total_alpa DESC
`

type CountSantriAlpaBerturutByKelasRow struct {
	ID        int64
	Nama      string
	TotalAlpa int64
}

func (q *Queries) CountSantriAlpaBerturutByKelas(ctx context.Context, kelasID int64) ([]CountSantriAlpaBerturutByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriAlpaBerturutByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriAlpaBerturutByKelasRow
	for rows.Next() {
		var i CountSantriAlpaBerturutByKelasRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.TotalAlpa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAbsensi = `-- name: CreateAbsensi :exec
INSERT INTO absensi (pertemuan_id, santri_id, status, catatan, batas_materi, dibuat_oleh)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAbsensiParams struct {
	PertemuanID int64
	SantriID    int64
	Status      string
	Catatan     string
	BatasMateri string
	DibuatOleh  sql.NullInt64
}

func (q *Queries) CreateAbsensi(ctx context.Context, arg CreateAbsensiParams) error {
	_, err := q.db.ExecContext(ctx, createAbsensi,
		arg.PertemuanID,
		arg.SantriID,
		arg.Status,
		arg.Catatan,
		arg.BatasMateri,
		arg.DibuatOleh,
	)
	return err
}

const createOrUpdateAbsensi = `-- name: CreateOrUpdateAbsensi :exec
INSERT INTO absensi (pertemuan_id, santri_id, status, catatan, batas_materi, dibuat_oleh)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(pertemuan_id, santri_id)
DO UPDATE SET status = excluded.status, catatan = excluded.catatan, batas_materi = excluded.batas_materi, updated_at = CURRENT_TIMESTAMP
`

type CreateOrUpdateAbsensiParams struct {
	PertemuanID int64
	SantriID    int64
	Status      string
	Catatan     string
	BatasMateri string
	DibuatOleh  sql.NullInt64
}

func (q *Queries) CreateOrUpdateAbsensi(ctx context.Context, arg CreateOrUpdateAbsensiParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateAbsensi,
		arg.PertemuanID,
		arg.SantriID,
		arg.Status,
		arg.Catatan,
		arg.BatasMateri,
		arg.DibuatOleh,
	)
	return err
}

const getAbsensiByID = `-- name: GetAbsensiByID :one
SELECT id, pertemuan_id, santri_id, status, catatan, dibuat_oleh, created_at, updated_at, batas_materi FROM absensi WHERE id = ?
`

func (q *Queries) GetAbsensiByID(ctx context.Context, id int64) (Absensi, error) {
	row := q.db.QueryRowContext(ctx, getAbsensiByID, id)
	var i Absensi
	err := row.Scan(
		&i.ID,
		&i.PertemuanID,
		&i.SantriID,
		&i.Status,
		&i.Catatan,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatasMateri,
	)
	return i, err
}

const getAbsensiByPertemuan = `-- name: GetAbsensiByPertemuan :many
SELECT a.id, a.pertemuan_id, a.santri_id, a.status, a.catatan, a.dibuat_oleh, a.created_at, a.updated_at, a.batas_materi, s.nama AS santri_nama, s.id_mahasantri
FROM absensi a
JOIN santri s ON a.santri_id = s.id
WHERE a.pertemuan_id = ?
ORDER BY s.nama
`

type GetAbsensiByPertemuanRow struct {
	ID           int64
	PertemuanID  int64
	SantriID     int64
	Status       string
	Catatan      string
	DibuatOleh   sql.NullInt64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	BatasMateri  string
	SantriNama   string
	IDMahasantri string
}

func (q *Queries) GetAbsensiByPertemuan(ctx context.Context, pertemuanID int64) ([]GetAbsensiByPertemuanRow, error) {
	rows, err := q.db.QueryContext(ctx, getAbsensiByPertemuan, pertemuanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAbsensiByPertemuanRow
	for rows.Next() {
		var i GetAbsensiByPertemuanRow
		if err := rows.Scan(
			&i.ID,
			&i.PertemuanID,
			&i.SantriID,
			&i.Status,
			&i.Catatan,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatasMateri,
			&i.SantriNama,
			&i.IDMahasantri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAbsensiByPertemuanAndSantri = `-- name: GetAbsensiByPertemuanAndSantri :one
SELECT id, pertemuan_id, santri_id, status, catatan, dibuat_oleh, created_at, updated_at, batas_materi FROM absensi WHERE pertemuan_id = ? AND santri_id = ?
`

type GetAbsensiByPertemuanAndSantriParams struct {
	PertemuanID int64
	SantriID    int64
}

func (q *Queries) GetAbsensiByPertemuanAndSantri(ctx context.Context, arg GetAbsensiByPertemuanAndSantriParams) (Absensi, error) {
	row := q.db.QueryRowContext(ctx, getAbsensiByPertemuanAndSantri, arg.PertemuanID, arg.SantriID)
	var i Absensi
	err := row.Scan(
		&i.ID,
		&i.PertemuanID,
		&i.SantriID,
		&i.Status,
		&i.Catatan,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatasMateri,
	)
	return i, err
}

const getAbsensiByPertemuanIDs = `-- name: GetAbsensiByPertemuanIDs :many
SELECT a.pertemuan_id, a.santri_id, a.status, s.nama AS santri_nama
FROM absensi a
JOIN santri s ON a.santri_id = s.id
WHERE a.pertemuan_id IN (/*SLICE:pertemuan_ids*/?)
ORDER BY s.nama
`

type GetAbsensiByPertemuanIDsRow struct {
	PertemuanID int64
	SantriID    int64
	Status      string
	SantriNama  string
}

func (q *Queries) GetAbsensiByPertemuanIDs(ctx context.Context, pertemuanIds []int64) ([]GetAbsensiByPertemuanIDsRow, error) {
	query := getAbsensiByPertemuanIDs
	var queryParams []interface{}
	if len(pertemuanIds) > 0 {
		for _, v := range pertemuanIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:pertemuan_ids*/?", strings.Repeat(",?", len(pertemuanIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:pertemuan_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAbsensiByPertemuanIDsRow
	for rows.Next() {
		var i GetAbsensiByPertemuanIDsRow
		if err := rows.Scan(
			&i.PertemuanID,
			&i.SantriID,
			&i.Status,
			&i.SantriNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAbsensiBySantri = `-- name: GetAbsensiBySantri :many
SELECT a.id, a.pertemuan_id, a.santri_id, a.status, a.catatan, a.dibuat_oleh, a.created_at, a.updated_at, a.batas_materi, p.pertemuan_ke, p.tanggal, p.materi
FROM absensi a
JOIN pertemuan p ON a.pertemuan_id = p.id
WHERE a.santri_id = ?
ORDER BY p.tanggal DESC
`

type GetAbsensiBySantriRow struct {
	ID          int64
	PertemuanID int64
	SantriID    int64
	Status      string
	Catatan     string
	DibuatOleh  sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BatasMateri string
	PertemuanKe int64
	Tanggal     time.Time
	Materi      string
}

func (q *Queries) GetAbsensiBySantri(ctx context.Context, santriID int64) ([]GetAbsensiBySantriRow, error) {
	rows, err := q.db.QueryContext(ctx, getAbsensiBySantri, santriID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAbsensiBySantriRow
	for rows.Next() {
		var i GetAbsensiBySantriRow
		if err := rows.Scan(
			&i.ID,
			&i.PertemuanID,
			&i.SantriID,
			&i.Status,
			&i.Catatan,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatasMateri,
			&i.PertemuanKe,
			&i.Tanggal,
			&i.Materi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAbsensiTerakhirBySantri = `-- name: GetAbsensiTerakhirBySantri :one
SELECT a.id, a.pertemuan_id, a.santri_id, a.status, a.catatan, a.dibuat_oleh, a.created_at, a.updated_at, a.batas_materi, p.pertemuan_ke, p.tanggal, p.materi
FROM absensi a
JOIN pertemuan p ON a.pertemuan_id = p.id
WHERE a.santri_id = ?
ORDER BY p.tanggal DESC
LIMIT 1
`

type GetAbsensiTerakhirBySantriRow struct {
	ID          int64
	PertemuanID int64
	SantriID    int64
	Status      string
	Catatan     string
	DibuatOleh  sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BatasMateri string
	PertemuanKe int64
	Tanggal     time.Time
	Materi      string
}

func (q *Queries) GetAbsensiTerakhirBySantri(ctx context.Context, santriID int64) (GetAbsensiTerakhirBySantriRow, error) {
	row := q.db.QueryRowContext(ctx, getAbsensiTerakhirBySantri, santriID)
	var i GetAbsensiTerakhirBySantriRow
	err := row.Scan(
		&i.ID,
		&i.PertemuanID,
		&i.SantriID,
		&i.Status,
		&i.Catatan,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatasMateri,
		&i.PertemuanKe,
		&i.Tanggal,
		&i.Materi,
	)
	return i, err
}

const getPertemuanByKelasForRekap = `-- name: GetPertemuanByKelasForRekap :many
SELECT id, pertemuan_ke, pertemuan_level_ke, level_nama, tanggal
FROM pertemuan
WHERE kelas_id = ?
ORDER BY pertemuan_ke
`

type GetPertemuanByKelasForRekapRow struct {
	ID               int64
	PertemuanKe      int64
	PertemuanLevelKe int64
	LevelNama        string
	Tanggal          time.Time
}

func (q *Queries) GetPertemuanByKelasForRekap(ctx context.Context, kelasID int64) ([]GetPertemuanByKelasForRekapRow, error) {
	rows, err := q.db.QueryContext(ctx, getPertemuanByKelasForRekap, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPertemuanByKelasForRekapRow
	for rows.Next() {
		var i GetPertemuanByKelasForRekapRow
		if err := rows.Scan(
			&i.ID,
			&i.PertemuanKe,
			&i.PertemuanLevelKe,
			&i.LevelNama,
			&i.Tanggal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRekapAbsensiKelas = `-- name: GetRekapAbsensiKelas :many
SELECT
    s.id AS santri_id,
    s.nama AS santri_nama,
    s.id_mahasantri
FROM santri s
WHERE s.kelas_id = ? AND s.status = 'aktif'
ORDER BY s.nama
`

type GetRekapAbsensiKelasRow struct {
	SantriID     int64
	SantriNama   string
	IDMahasantri string
}

func (q *Queries) GetRekapAbsensiKelas(ctx context.Context, kelasID sql.NullInt64) ([]GetRekapAbsensiKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, getRekapAbsensiKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRekapAbsensiKelasRow
	for rows.Next() {
		var i GetRekapAbsensiKelasRow
		if err := rows.Scan(&i.SantriID, &i.SantriNama, &i.IDMahasantri); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAbsensi = `-- name: UpdateAbsensi :exec
UPDATE absensi SET status = ?, catatan = ?, batas_materi = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAbsensiParams struct {
	Status      string
	Catatan     string
	BatasMateri string
	ID          int64
}

func (q *Queries) UpdateAbsensi(ctx context.Context, arg UpdateAbsensiParams) error {
	_, err := q.db.ExecContext(ctx, updateAbsensi,
		arg.Status,
		arg.Catatan,
		arg.BatasMateri,
		arg.ID,
	)
	return err
}

const updateAbsensiByPertemuanAndSantri = `-- name: UpdateAbsensiByPertemuanAndSantri :exec
UPDATE absensi SET status = ?, catatan = ?, batas_materi = ?, updated_at = CURRENT_TIMESTAMP
WHERE pertemuan_id = ? AND santri_id = ?
`

type UpdateAbsensiByPertemuanAndSantriParams struct {
	Status      string
	Catatan     string
	BatasMateri string
	PertemuanID int64
	SantriID    int64
}

func (q *Queries) UpdateAbsensiByPertemuanAndSantri(ctx context.Context, arg UpdateAbsensiByPertemuanAndSantriParams) error {
	_, err := q.db.ExecContext(ctx, updateAbsensiByPertemuanAndSantri,
		arg.Status,
		arg.Catatan,
		arg.BatasMateri,
		arg.PertemuanID,
		arg.SantriID,
	)
	return err
}
