// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batas_materi.sql

package queries

import (
	"context"
)

const getBatasMateriTerakhirByKelas = `-- name: GetBatasMateriTerakhirByKelas :many
SELECT santri_id, batas_materi
FROM (
    SELECT
        a.santri_id,
        a.batas_materi,
        ROW_NUMBER() OVER (PARTITION BY a.santri_id ORDER BY p.pertemuan_ke DESC, a.id DESC) AS urutan
    FROM absensi a
    JOIN pertemuan p ON p.id = a.pertemuan_id
    WHERE p.kelas_id = ? AND p.status = 'selesai' AND a.batas_materi != ''
)
WHERE urutan = 1
`

type GetBatasMateriTerakhirByKelasRow struct {
	SantriID    int64
	BatasMateri string
}

func (q *Queries) GetBatasMateriTerakhirByKelas(ctx context.Context, kelasID int64) ([]GetBatasMateriTerakhirByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, getBatasMateriTerakhirByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBatasMateriTerakhirByKelasRow
	for rows.Next() {
		var i GetBatasMateriTerakhirByKelasRow
		if err := rows.Scan(&i.SantriID, &i.BatasMateri); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
