// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guru_beranda.sql

package queries

import (
	"context"
	"strings"
	"time"
)

const getTsiFinalTerakhir = `-- name: GetTsiFinalTerakhir :one
SELECT bulan FROM tsi_periode
WHERE guru_id = ? AND status = 'final'
ORDER BY bulan DESC
LIMIT 1
`

func (q *Queries) GetTsiFinalTerakhir(ctx context.Context, guruID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getTsiFinalTerakhir, guruID)
	var bulan string
	err := row.Scan(&bulan)
	return bulan, err
}

const listAgendaGuruMendatang = `-- name: ListAgendaGuruMendatang :many
SELECT jenis, id, CAST(tanggal AS TEXT) AS tanggal, judul FROM (
    SELECT 'pembinaan' AS jenis, id, tanggal, topik AS judul FROM pembinaan
    WHERE status = 'dijadwalkan' AND tanggal >= CAST(?1 AS TEXT)
    UNION ALL
    SELECT 'rapat' AS jenis, id, tanggal, judul FROM rapat_guru
    WHERE status = 'dijadwalkan' AND tanggal >= CAST(?1 AS TEXT)
    UNION ALL
    SELECT 'kalam' AS jenis, id, tanggal, topik AS judul FROM kalam_bersanad
    WHERE tanggal >= CAST(?1 AS TEXT)
)
ORDER BY tanggal, jenis
LIMIT 5
`

type ListAgendaGuruMendatangRow struct {
	Jenis   string
	ID      int64
	Tanggal string
	Judul   string
}

// Agenda koordinator terdekat: pembinaan, rapat, dan kalam bersanad.
func (q *Queries) ListAgendaGuruMendatang(ctx context.Context, sejak string) ([]ListAgendaGuruMendatangRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgendaGuruMendatang, sejak)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgendaGuruMendatangRow
	for rows.Next() {
		var i ListAgendaGuruMendatangRow
		if err := rows.Scan(
			&i.Jenis,
			&i.ID,
			&i.Tanggal,
			&i.Judul,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalPertemuanBeranda = `-- name: ListJadwalPertemuanBeranda :many
SELECT jp.id, jp.kelas_id, jp.tanggal, jp.jam_mulai, jp.status,
    jp.is_reschedule, jp.jadwal_semula,
    COALESCE(jp.guru_pengganti_id, 0) AS guru_pengganti_id,
    COALESCE(jp.pertemuan_id, 0) AS pertemuan_id,
    k.nama_kelas, k.level,
    COALESCE(k.guru_id, 0) AS guru_utama_id,
    COALESCE(gu.nama, '') AS guru_utama_nama,
    COALESCE(gb.nama, '') AS guru_pengganti_nama,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = k.id AND s.status = 'aktif') AS jumlah_santri
FROM jadwal_pertemuan jp
JOIN kelas k ON k.id = jp.kelas_id
LEFT JOIN guru gu ON gu.id = k.guru_id
LEFT JOIN guru gb ON gb.id = jp.guru_pengganti_id
WHERE (
        (jp.tanggal >= CAST(?1 AS TEXT) AND jp.tanggal < CAST(?2 AS TEXT))
     OR (jp.jadwal_semula >= CAST(?1 AS TEXT) AND jp.jadwal_semula < CAST(?2 AS TEXT))
  )
  AND (
      ?3 IS NULL
      OR k.guru_id = ?3
      OR jp.guru_pengganti_id = ?3
  )
ORDER BY jp.tanggal, jp.jam_mulai, jp.id
`

type ListJadwalPertemuanBerandaParams struct {
	Mulai   string
	Selesai string
	GuruID  interface{}
}

type ListJadwalPertemuanBerandaRow struct {
	ID                int64
	KelasID           int64
	Tanggal           time.Time
	JamMulai          string
	Status            string
	IsReschedule      int64
	JadwalSemula      string
	GuruPenggantiID   int64
	PertemuanID       int64
	NamaKelas         string
	Level             string
	GuruUtamaID       int64
	GuruUtamaNama     string
	GuruPenggantiNama string
	JumlahSantri      int64
}

// Jadwal pertemuan (reschedule/badal/batal) yang tanggal baru atau tanggal
// semulanya jatuh di rentang [mulai, selesai).
func (q *Queries) ListJadwalPertemuanBeranda(ctx context.Context, arg ListJadwalPertemuanBerandaParams) ([]ListJadwalPertemuanBerandaRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalPertemuanBeranda, arg.Mulai, arg.Selesai, arg.GuruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJadwalPertemuanBerandaRow
	for rows.Next() {
		var i ListJadwalPertemuanBerandaRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.Tanggal,
			&i.JamMulai,
			&i.Status,
			&i.IsReschedule,
			&i.JadwalSemula,
			&i.GuruPenggantiID,
			&i.PertemuanID,
			&i.NamaKelas,
			&i.Level,
			&i.GuruUtamaID,
			&i.GuruUtamaNama,
			&i.GuruPenggantiNama,
			&i.JumlahSantri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKelasAktifBeranda = `-- name: ListKelasAktifBeranda :many
SELECT k.id, k.nama_kelas, k.level, k.jadwal, k.created_at,
    COALESCE(k.guru_id, 0) AS guru_id,
    COALESCE(g.nama, '') AS guru_nama,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = k.id AND s.status = 'aktif') AS jumlah_santri
FROM kelas k
LEFT JOIN guru g ON g.id = k.guru_id
WHERE k.is_aktif = 1
  AND (?1 IS NULL OR k.guru_id = ?1)
ORDER BY k.nama_kelas
`

type ListKelasAktifBerandaRow struct {
	ID           int64
	NamaKelas    string
	Level        string
	Jadwal       string
	CreatedAt    time.Time
	GuruID       int64
	GuruNama     string
	JumlahSantri int64
}

// Kelas aktif dalam cakupan guru (NULL = semua) beserta jumlah santri aktif.
func (q *Queries) ListKelasAktifBeranda(ctx context.Context, guruID interface{}) ([]ListKelasAktifBerandaRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasAktifBeranda, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasAktifBerandaRow
	for rows.Next() {
		var i ListKelasAktifBerandaRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaKelas,
			&i.Level,
			&i.Jadwal,
			&i.CreatedAt,
			&i.GuruID,
			&i.GuruNama,
			&i.JumlahSantri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPertemuanKelasSejak = `-- name: ListPertemuanKelasSejak :many
SELECT id, kelas_id, tanggal, status
FROM pertemuan
WHERE kelas_id IN (/*SLICE:kelas_ids*/?)
  AND tanggal >= CAST(?2 AS TEXT)
  AND status IN ('berlangsung', 'selesai')
ORDER BY tanggal, id
`

type ListPertemuanKelasSejakParams struct {
	KelasIds []int64
	Sejak    string
}

type ListPertemuanKelasSejakRow struct {
	ID      int64
	KelasID int64
	Tanggal time.Time
	Status  string
}

func (q *Queries) ListPertemuanKelasSejak(ctx context.Context, arg ListPertemuanKelasSejakParams) ([]ListPertemuanKelasSejakRow, error) {
	query := listPertemuanKelasSejak
	var queryParams []interface{}
	if len(arg.KelasIds) > 0 {
		for _, v := range arg.KelasIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kelas_ids*/?", strings.Repeat(",?", len(arg.KelasIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kelas_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Sejak)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPertemuanKelasSejakRow
	for rows.Next() {
		var i ListPertemuanKelasSejakRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.Tanggal,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
