// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guru.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countGuruByUserID = `-- name: CountGuruByUserID :one
SELECT COUNT(*) FROM guru WHERE user_id = ?
`

func (q *Queries) CountGuruByUserID(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuruByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKelasByGuruID = `-- name: CountKelasByGuruID :one
SELECT COUNT(*) FROM kelas WHERE guru_id = ? AND is_aktif = 1
`

func (q *Queries) CountKelasByGuruID(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKelasByGuruID, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPertemuanHariIniByGuruID = `-- name: CountPertemuanHariIniByGuruID :one
SELECT COUNT(*) FROM pertemuan p
JOIN kelas k ON p.kelas_id = k.id
WHERE k.guru_id = ? AND p.tanggal = date('now')
`

func (q *Queries) CountPertemuanHariIniByGuruID(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPertemuanHariIniByGuruID, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPertemuanMingguIniByGuruID = `-- name: CountPertemuanMingguIniByGuruID :one
SELECT COUNT(*) FROM pertemuan p
JOIN kelas k ON p.kelas_id = k.id
WHERE k.guru_id = ? AND p.tanggal >= date('now', '-7 days') AND p.tanggal <= date('now')
`

func (q *Queries) CountPertemuanMingguIniByGuruID(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPertemuanMingguIniByGuruID, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSantriAktifByGuruID = `-- name: CountSantriAktifByGuruID :one
SELECT COUNT(*) FROM santri s
JOIN kelas k ON s.kelas_id = k.id
WHERE k.guru_id = ? AND s.status = 'aktif' AND k.is_aktif = 1
`

func (q *Queries) CountSantriAktifByGuruID(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSantriAktifByGuruID, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuruFull = `-- name: CreateGuruFull :one
INSERT INTO guru (nama, gelar, jenis_kelamin, status, no_wa, email, tanggal_gabung, foto, is_aktif)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateGuruFullParams struct {
	Nama          string
	Gelar         string
	JenisKelamin  string
	Status        string
	NoWa          string
	Email         string
	TanggalGabung sql.NullTime
	Foto          string
	IsAktif       int64
}

func (q *Queries) CreateGuruFull(ctx context.Context, arg CreateGuruFullParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGuruFull,
		arg.Nama,
		arg.Gelar,
		arg.JenisKelamin,
		arg.Status,
		arg.NoWa,
		arg.Email,
		arg.TanggalGabung,
		arg.Foto,
		arg.IsAktif,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGuruStats = `-- name: GetGuruStats :one
SELECT
    COUNT(DISTINCT k.id) AS total_kelas,
    COUNT(DISTINCT s.id) AS total_santri,
    COUNT(DISTINCT CASE WHEN s.status = 'aktif' THEN s.id END) AS santri_aktif,
    COUNT(DISTINCT p.id) AS total_pertemuan
FROM kelas k
LEFT JOIN santri s ON s.kelas_id = k.id
LEFT JOIN pertemuan p ON p.kelas_id = k.id
WHERE k.is_aktif = 1
  AND (?1 IS NULL OR k.guru_id = ?1)
`

type GetGuruStatsRow struct {
	TotalKelas     int64
	TotalSantri    int64
	SantriAktif    int64
	TotalPertemuan int64
}

func (q *Queries) GetGuruStats(ctx context.Context, guruID interface{}) (GetGuruStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getGuruStats, guruID)
	var i GetGuruStatsRow
	err := row.Scan(
		&i.TotalKelas,
		&i.TotalSantri,
		&i.SantriAktif,
		&i.TotalPertemuan,
	)
	return i, err
}

const getJadwalMengajarHariIni = `-- name: GetJadwalMengajarHariIni :many
SELECT k.id, k.nama_kelas, k.jadwal, k.level, k.tipe, k.jenis_kelamin,
    k.frekuensi, k.kapasitas,
    COALESCE((SELECT COUNT(*) FROM santri s WHERE s.kelas_id = k.id AND s.status = 'aktif'), 0) AS jumlah_santri_aktif
FROM kelas k
WHERE (?1 IS NULL OR k.guru_id = ?1) AND k.is_aktif = 1
ORDER BY k.jadwal
`

type GetJadwalMengajarHariIniRow struct {
	ID                int64
	NamaKelas         string
	Jadwal            string
	Level             string
	Tipe              string
	JenisKelamin      string
	Frekuensi         string
	Kapasitas         int64
	JumlahSantriAktif interface{}
}

func (q *Queries) GetJadwalMengajarHariIni(ctx context.Context, guruID interface{}) ([]GetJadwalMengajarHariIniRow, error) {
	rows, err := q.db.QueryContext(ctx, getJadwalMengajarHariIni, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJadwalMengajarHariIniRow
	for rows.Next() {
		var i GetJadwalMengajarHariIniRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaKelas,
			&i.Jadwal,
			&i.Level,
			&i.Tipe,
			&i.JenisKelamin,
			&i.Frekuensi,
			&i.Kapasitas,
			&i.JumlahSantriAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKelasBelumAbsen = `-- name: GetKelasBelumAbsen :many
SELECT k.id, k.nama_kelas, k.jadwal, k.level, k.tipe,
    COALESCE(lp.pertemuan_terakhir, 0) AS pertemuan_terakhir,
    COALESCE(lp.tanggal_terakhir, '') AS tanggal_terakhir
FROM kelas k
LEFT JOIN (
    SELECT kelas_id,
        (SELECT p2.pertemuan_level_ke FROM pertemuan p2 WHERE p2.kelas_id = pertemuan.kelas_id ORDER BY p2.pertemuan_ke DESC LIMIT 1) AS pertemuan_terakhir,
        MAX(tanggal) AS tanggal_terakhir
    FROM pertemuan
    GROUP BY kelas_id
) lp ON lp.kelas_id = k.id
WHERE (?1 IS NULL OR k.guru_id = ?1) AND k.is_aktif = 1
  AND (lp.tanggal_terakhir IS NULL OR lp.tanggal_terakhir < date('now', '-1 days'))
ORDER BY lp.tanggal_terakhir ASC
`

type GetKelasBelumAbsenRow struct {
	ID                int64
	NamaKelas         string
	Jadwal            string
	Level             string
	Tipe              string
	PertemuanTerakhir int64
	TanggalTerakhir   interface{}
}

func (q *Queries) GetKelasBelumAbsen(ctx context.Context, guruID interface{}) ([]GetKelasBelumAbsenRow, error) {
	rows, err := q.db.QueryContext(ctx, getKelasBelumAbsen, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKelasBelumAbsenRow
	for rows.Next() {
		var i GetKelasBelumAbsenRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaKelas,
			&i.Jadwal,
			&i.Level,
			&i.Tipe,
			&i.PertemuanTerakhir,
			&i.TanggalTerakhir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guruGetByID = `-- name: GuruGetByID :one
SELECT id, nama, jenis_kelamin, is_aktif, user_id, status, no_wa, email, tanggal_gabung, foto, gelar FROM guru WHERE id = ?
`

func (q *Queries) GuruGetByID(ctx context.Context, id int64) (Guru, error) {
	row := q.db.QueryRowContext(ctx, guruGetByID, id)
	var i Guru
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.JenisKelamin,
		&i.IsAktif,
		&i.UserID,
		&i.Status,
		&i.NoWa,
		&i.Email,
		&i.TanggalGabung,
		&i.Foto,
		&i.Gelar,
	)
	return i, err
}

const guruGetByUserID = `-- name: GuruGetByUserID :one
SELECT id, nama, jenis_kelamin, is_aktif, user_id, status, no_wa, email, tanggal_gabung, foto, gelar FROM guru WHERE user_id = ?
`

func (q *Queries) GuruGetByUserID(ctx context.Context, userID sql.NullInt64) (Guru, error) {
	row := q.db.QueryRowContext(ctx, guruGetByUserID, userID)
	var i Guru
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.JenisKelamin,
		&i.IsAktif,
		&i.UserID,
		&i.Status,
		&i.NoWa,
		&i.Email,
		&i.TanggalGabung,
		&i.Foto,
		&i.Gelar,
	)
	return i, err
}

const guruListAll = `-- name: GuruListAll :many
SELECT id, nama, jenis_kelamin, is_aktif, user_id, status, no_wa, email, tanggal_gabung, foto, gelar FROM guru ORDER BY nama ASC
`

func (q *Queries) GuruListAll(ctx context.Context) ([]Guru, error) {
	rows, err := q.db.QueryContext(ctx, guruListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guru
	for rows.Next() {
		var i Guru
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.JenisKelamin,
			&i.IsAktif,
			&i.UserID,
			&i.Status,
			&i.NoWa,
			&i.Email,
			&i.TanggalGabung,
			&i.Foto,
			&i.Gelar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruByIDs = `-- name: ListGuruByIDs :many
SELECT id, nama, jenis_kelamin, is_aktif, user_id, status, no_wa, email, tanggal_gabung, foto, gelar FROM guru WHERE id IN (/*SLICE:ids*/?) ORDER BY nama
`

func (q *Queries) ListGuruByIDs(ctx context.Context, ids []int64) ([]Guru, error) {
	query := listGuruByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guru
	for rows.Next() {
		var i Guru
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.JenisKelamin,
			&i.IsAktif,
			&i.UserID,
			&i.Status,
			&i.NoWa,
			&i.Email,
			&i.TanggalGabung,
			&i.Foto,
			&i.Gelar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruByStatus = `-- name: ListGuruByStatus :many
SELECT id, nama, jenis_kelamin, is_aktif, user_id, status, no_wa, email, tanggal_gabung, foto, gelar FROM guru WHERE status = ? ORDER BY nama ASC
`

func (q *Queries) ListGuruByStatus(ctx context.Context, status string) ([]Guru, error) {
	rows, err := q.db.QueryContext(ctx, listGuruByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guru
	for rows.Next() {
		var i Guru
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.JenisKelamin,
			&i.IsAktif,
			&i.UserID,
			&i.Status,
			&i.NoWa,
			&i.Email,
			&i.TanggalGabung,
			&i.Foto,
			&i.Gelar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKelasByGuruID = `-- name: ListKelasByGuruID :many
SELECT kelas.id, kelas.kunci_kelas, kelas.angkatan, kelas.tipe, kelas.jenis_kelamin, kelas.level, kelas.frekuensi, kelas.jadwal, kelas.sub_index, kelas.nama_kelas, kelas.guru_id, guru.nama AS guru_nama, kelas.kapasitas,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = kelas.id AND s.status IN ('aktif', 'cuti')) AS jumlah_santri,
    kelas.created_at, kelas.is_aktif
FROM kelas
LEFT JOIN guru ON guru.id = kelas.guru_id
WHERE (?1 IS NULL OR kelas.guru_id = ?1) AND kelas.is_aktif = 1
ORDER BY COALESCE(guru.nama, ''), angkatan, tipe, level, sub_index
`

type ListKelasByGuruIDRow struct {
	ID           int64
	KunciKelas   string
	Angkatan     string
	Tipe         string
	JenisKelamin string
	Level        string
	Frekuensi    string
	Jadwal       string
	SubIndex     int64
	NamaKelas    string
	GuruID       sql.NullInt64
	GuruNama     sql.NullString
	Kapasitas    int64
	JumlahSantri int64
	CreatedAt    time.Time
	IsAktif      int64
}

func (q *Queries) ListKelasByGuruID(ctx context.Context, guruID interface{}) ([]ListKelasByGuruIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasByGuruID, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasByGuruIDRow
	for rows.Next() {
		var i ListKelasByGuruIDRow
		if err := rows.Scan(
			&i.ID,
			&i.KunciKelas,
			&i.Angkatan,
			&i.Tipe,
			&i.JenisKelamin,
			&i.Level,
			&i.Frekuensi,
			&i.Jadwal,
			&i.SubIndex,
			&i.NamaKelas,
			&i.GuruID,
			&i.GuruNama,
			&i.Kapasitas,
			&i.JumlahSantri,
			&i.CreatedAt,
			&i.IsAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkableUsers = `-- name: ListLinkableUsers :many
SELECT id, name, email, role
FROM users
WHERE id NOT IN (SELECT user_id FROM guru WHERE user_id IS NOT NULL)
ORDER BY name ASC
`

type ListLinkableUsersRow struct {
	ID    int64
	Name  string
	Email string
	Role  string
}

// Accounts not yet linked to any guru record, eligible for linking.
func (q *Queries) ListLinkableUsers(ctx context.Context) ([]ListLinkableUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinkableUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkableUsersRow
	for rows.Next() {
		var i ListLinkableUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuruDirectory = `-- name: UpdateGuruDirectory :exec
UPDATE guru
SET nama = ?, gelar = ?, jenis_kelamin = ?, status = ?, no_wa = ?, email = ?,
    tanggal_gabung = ?, foto = ?, is_aktif = ?
WHERE id = ?
`

type UpdateGuruDirectoryParams struct {
	Nama          string
	Gelar         string
	JenisKelamin  string
	Status        string
	NoWa          string
	Email         string
	TanggalGabung sql.NullTime
	Foto          string
	IsAktif       int64
	ID            int64
}

func (q *Queries) UpdateGuruDirectory(ctx context.Context, arg UpdateGuruDirectoryParams) error {
	_, err := q.db.ExecContext(ctx, updateGuruDirectory,
		arg.Nama,
		arg.Gelar,
		arg.JenisKelamin,
		arg.Status,
		arg.NoWa,
		arg.Email,
		arg.TanggalGabung,
		arg.Foto,
		arg.IsAktif,
		arg.ID,
	)
	return err
}

const updateGuruUserID = `-- name: UpdateGuruUserID :exec
UPDATE guru SET user_id = ? WHERE id = ?
`

type UpdateGuruUserIDParams struct {
	UserID sql.NullInt64
	ID     int64
}

func (q *Queries) UpdateGuruUserID(ctx context.Context, arg UpdateGuruUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updateGuruUserID, arg.UserID, arg.ID)
	return err
}
