// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jadwal_pertemuan.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const cancelJadwalPertemuan = `-- name: CancelJadwalPertemuan :execrows
UPDATE jadwal_pertemuan
SET status = 'dibatalkan', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'dijadwalkan'
`

type CancelJadwalPertemuanParams struct {
	ID      int64
	KelasID int64
}

func (q *Queries) CancelJadwalPertemuan(ctx context.Context, arg CancelJadwalPertemuanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelJadwalPertemuan, arg.ID, arg.KelasID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimJadwalPertemuan = `-- name: ClaimJadwalPertemuan :execrows
UPDATE jadwal_pertemuan
SET status = 'diproses', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'dijadwalkan'
`

type ClaimJadwalPertemuanParams struct {
	ID      int64
	KelasID int64
}

func (q *Queries) ClaimJadwalPertemuan(ctx context.Context, arg ClaimJadwalPertemuanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimJadwalPertemuan, arg.ID, arg.KelasID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJadwalPertemuanStart = `-- name: CompleteJadwalPertemuanStart :exec
UPDATE jadwal_pertemuan
SET status = 'dimulai', pertemuan_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'diproses'
`

type CompleteJadwalPertemuanStartParams struct {
	PertemuanID sql.NullInt64
	ID          int64
	KelasID     int64
}

func (q *Queries) CompleteJadwalPertemuanStart(ctx context.Context, arg CompleteJadwalPertemuanStartParams) error {
	_, err := q.db.ExecContext(ctx, completeJadwalPertemuanStart, arg.PertemuanID, arg.ID, arg.KelasID)
	return err
}

const countDueJadwalPertemuanByKelas = `-- name: CountDueJadwalPertemuanByKelas :one
SELECT COUNT(*) FROM jadwal_pertemuan
WHERE kelas_id = ? AND status = 'dijadwalkan' AND tanggal <= ?
`

type CountDueJadwalPertemuanByKelasParams struct {
	KelasID int64
	Tanggal time.Time
}

func (q *Queries) CountDueJadwalPertemuanByKelas(ctx context.Context, arg CountDueJadwalPertemuanByKelasParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDueJadwalPertemuanByKelas, arg.KelasID, arg.Tanggal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJadwalPertemuan = `-- name: CreateJadwalPertemuan :one
INSERT INTO jadwal_pertemuan (kelas_id, tanggal, jam_mulai, catatan, dibuat_oleh)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateJadwalPertemuanParams struct {
	KelasID    int64
	Tanggal    time.Time
	JamMulai   string
	Catatan    string
	DibuatOleh sql.NullInt64
}

func (q *Queries) CreateJadwalPertemuan(ctx context.Context, arg CreateJadwalPertemuanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createJadwalPertemuan,
		arg.KelasID,
		arg.Tanggal,
		arg.JamMulai,
		arg.Catatan,
		arg.DibuatOleh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getJadwalPertemuanByID = `-- name: GetJadwalPertemuanByID :one
SELECT id, kelas_id, tanggal, jam_mulai, catatan, is_reschedule, jadwal_semula, alasan_reschedule, guru_pengganti_id, alasan_badal, status, pertemuan_id, dibuat_oleh, created_at, updated_at, jadwal_kelas_berubah FROM jadwal_pertemuan WHERE id = ? AND kelas_id = ?
`

type GetJadwalPertemuanByIDParams struct {
	ID      int64
	KelasID int64
}

func (q *Queries) GetJadwalPertemuanByID(ctx context.Context, arg GetJadwalPertemuanByIDParams) (JadwalPertemuan, error) {
	row := q.db.QueryRowContext(ctx, getJadwalPertemuanByID, arg.ID, arg.KelasID)
	var i JadwalPertemuan
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.Tanggal,
		&i.JamMulai,
		&i.Catatan,
		&i.IsReschedule,
		&i.JadwalSemula,
		&i.AlasanReschedule,
		&i.GuruPenggantiID,
		&i.AlasanBadal,
		&i.Status,
		&i.PertemuanID,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JadwalKelasBerubah,
	)
	return i, err
}

const listDueJadwalPertemuanByKelas = `-- name: ListDueJadwalPertemuanByKelas :many
SELECT jp.id, jp.kelas_id, jp.tanggal, jp.jam_mulai, jp.catatan, jp.is_reschedule, jp.jadwal_semula, jp.alasan_reschedule, jp.guru_pengganti_id, jp.alasan_badal, jp.status, jp.pertemuan_id, jp.dibuat_oleh, jp.created_at, jp.updated_at, jp.jadwal_kelas_berubah, COALESCE(gb.nama, '') AS guru_pengganti_nama
FROM jadwal_pertemuan jp
LEFT JOIN guru gb ON gb.id = jp.guru_pengganti_id
WHERE jp.kelas_id = ? AND jp.status = 'dijadwalkan' AND jp.tanggal <= ?
ORDER BY jp.tanggal, jp.jam_mulai, jp.id
`

type ListDueJadwalPertemuanByKelasParams struct {
	KelasID int64
	Tanggal time.Time
}

type ListDueJadwalPertemuanByKelasRow struct {
	ID                 int64
	KelasID            int64
	Tanggal            time.Time
	JamMulai           string
	Catatan            string
	IsReschedule       int64
	JadwalSemula       string
	AlasanReschedule   string
	GuruPenggantiID    sql.NullInt64
	AlasanBadal        string
	Status             string
	PertemuanID        sql.NullInt64
	DibuatOleh         sql.NullInt64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	JadwalKelasBerubah int64
	GuruPenggantiNama  string
}

func (q *Queries) ListDueJadwalPertemuanByKelas(ctx context.Context, arg ListDueJadwalPertemuanByKelasParams) ([]ListDueJadwalPertemuanByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueJadwalPertemuanByKelas, arg.KelasID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueJadwalPertemuanByKelasRow
	for rows.Next() {
		var i ListDueJadwalPertemuanByKelasRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.Tanggal,
			&i.JamMulai,
			&i.Catatan,
			&i.IsReschedule,
			&i.JadwalSemula,
			&i.AlasanReschedule,
			&i.GuruPenggantiID,
			&i.AlasanBadal,
			&i.Status,
			&i.PertemuanID,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JadwalKelasBerubah,
			&i.GuruPenggantiNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalPertemuanForGuru = `-- name: ListJadwalPertemuanForGuru :many
SELECT
    jp.id, jp.kelas_id, jp.tanggal, jp.jam_mulai, jp.catatan, jp.is_reschedule, jp.jadwal_semula, jp.alasan_reschedule, jp.guru_pengganti_id, jp.alasan_badal, jp.status, jp.pertemuan_id, jp.dibuat_oleh, jp.created_at, jp.updated_at, jp.jadwal_kelas_berubah,
    k.nama_kelas,
    k.guru_id AS guru_utama_id,
    COALESCE(gu.nama, '') AS guru_utama_nama,
    COALESCE(gb.nama, '') AS guru_pengganti_nama
FROM jadwal_pertemuan jp
JOIN kelas k ON k.id = jp.kelas_id
LEFT JOIN guru gu ON gu.id = k.guru_id
LEFT JOIN guru gb ON gb.id = jp.guru_pengganti_id
WHERE jp.status IN ('dijadwalkan', 'dimulai')
  AND (
      ?1 IS NULL
      OR k.guru_id = ?1
      OR jp.guru_pengganti_id = ?1
  )
ORDER BY jp.tanggal, jp.jam_mulai, jp.id
`

type ListJadwalPertemuanForGuruRow struct {
	ID                 int64
	KelasID            int64
	Tanggal            time.Time
	JamMulai           string
	Catatan            string
	IsReschedule       int64
	JadwalSemula       string
	AlasanReschedule   string
	GuruPenggantiID    sql.NullInt64
	AlasanBadal        string
	Status             string
	PertemuanID        sql.NullInt64
	DibuatOleh         sql.NullInt64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	JadwalKelasBerubah int64
	NamaKelas          string
	GuruUtamaID        sql.NullInt64
	GuruUtamaNama      string
	GuruPenggantiNama  string
}

func (q *Queries) ListJadwalPertemuanForGuru(ctx context.Context, guruID interface{}) ([]ListJadwalPertemuanForGuruRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalPertemuanForGuru, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJadwalPertemuanForGuruRow
	for rows.Next() {
		var i ListJadwalPertemuanForGuruRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.Tanggal,
			&i.JamMulai,
			&i.Catatan,
			&i.IsReschedule,
			&i.JadwalSemula,
			&i.AlasanReschedule,
			&i.GuruPenggantiID,
			&i.AlasanBadal,
			&i.Status,
			&i.PertemuanID,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JadwalKelasBerubah,
			&i.NamaKelas,
			&i.GuruUtamaID,
			&i.GuruUtamaNama,
			&i.GuruPenggantiNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJadwalPertemuanKelasBerubah = `-- name: MarkJadwalPertemuanKelasBerubah :exec
UPDATE jadwal_pertemuan
SET jadwal_kelas_berubah = 1, updated_at = CURRENT_TIMESTAMP
WHERE kelas_id = ? AND status = 'dijadwalkan'
`

func (q *Queries) MarkJadwalPertemuanKelasBerubah(ctx context.Context, kelasID int64) error {
	_, err := q.db.ExecContext(ctx, markJadwalPertemuanKelasBerubah, kelasID)
	return err
}

const markJadwalPertemuanSelesai = `-- name: MarkJadwalPertemuanSelesai :exec
UPDATE jadwal_pertemuan
SET status = 'selesai', updated_at = CURRENT_TIMESTAMP
WHERE pertemuan_id = ? AND status = 'dimulai'
`

func (q *Queries) MarkJadwalPertemuanSelesai(ctx context.Context, pertemuanID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, markJadwalPertemuanSelesai, pertemuanID)
	return err
}

const updateJadwalPertemuanBadal = `-- name: UpdateJadwalPertemuanBadal :execrows
UPDATE jadwal_pertemuan
SET guru_pengganti_id = ?, alasan_badal = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'dijadwalkan'
`

type UpdateJadwalPertemuanBadalParams struct {
	GuruPenggantiID sql.NullInt64
	AlasanBadal     string
	ID              int64
	KelasID         int64
}

func (q *Queries) UpdateJadwalPertemuanBadal(ctx context.Context, arg UpdateJadwalPertemuanBadalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJadwalPertemuanBadal,
		arg.GuruPenggantiID,
		arg.AlasanBadal,
		arg.ID,
		arg.KelasID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateJadwalPertemuanReschedule = `-- name: UpdateJadwalPertemuanReschedule :execrows
UPDATE jadwal_pertemuan
SET tanggal = ?, jam_mulai = ?, is_reschedule = 1, jadwal_semula = ?,
    alasan_reschedule = ?, jadwal_kelas_berubah = 0, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'dijadwalkan'
`

type UpdateJadwalPertemuanRescheduleParams struct {
	Tanggal          time.Time
	JamMulai         string
	JadwalSemula     string
	AlasanReschedule string
	ID               int64
	KelasID          int64
}

func (q *Queries) UpdateJadwalPertemuanReschedule(ctx context.Context, arg UpdateJadwalPertemuanRescheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJadwalPertemuanReschedule,
		arg.Tanggal,
		arg.JamMulai,
		arg.JadwalSemula,
		arg.AlasanReschedule,
		arg.ID,
		arg.KelasID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
