// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kelas_perubahan.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createKelasPerubahan = `-- name: CreateKelasPerubahan :exec
INSERT INTO kelas_perubahan (
    kelas_id, santri_id, kelas_tujuan_id, jenis, nilai_lama, nilai_baru, pertemuan_ke, alasan, dibuat_oleh
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateKelasPerubahanParams struct {
	KelasID       sql.NullInt64
	SantriID      sql.NullInt64
	KelasTujuanID sql.NullInt64
	Jenis         string
	NilaiLama     string
	NilaiBaru     string
	PertemuanKe   int64
	Alasan        string
	DibuatOleh    sql.NullInt64
}

func (q *Queries) CreateKelasPerubahan(ctx context.Context, arg CreateKelasPerubahanParams) error {
	_, err := q.db.ExecContext(ctx, createKelasPerubahan,
		arg.KelasID,
		arg.SantriID,
		arg.KelasTujuanID,
		arg.Jenis,
		arg.NilaiLama,
		arg.NilaiBaru,
		arg.PertemuanKe,
		arg.Alasan,
		arg.DibuatOleh,
	)
	return err
}

const getKelasPerubahanState = `-- name: GetKelasPerubahanState :one
SELECT id, kunci_kelas, level, jadwal, sub_index, level_pertemuan_awal
FROM kelas WHERE id = ?
`

type GetKelasPerubahanStateRow struct {
	ID                 int64
	KunciKelas         string
	Level              string
	Jadwal             string
	SubIndex           int64
	LevelPertemuanAwal int64
}

func (q *Queries) GetKelasPerubahanState(ctx context.Context, id int64) (GetKelasPerubahanStateRow, error) {
	row := q.db.QueryRowContext(ctx, getKelasPerubahanState, id)
	var i GetKelasPerubahanStateRow
	err := row.Scan(
		&i.ID,
		&i.KunciKelas,
		&i.Level,
		&i.Jadwal,
		&i.SubIndex,
		&i.LevelPertemuanAwal,
	)
	return i, err
}

const listKelasPerubahanByKelas = `-- name: ListKelasPerubahanByKelas :many
SELECT
    kp.id, kp.kelas_id, kp.santri_id, kp.kelas_tujuan_id, kp.jenis,
    kp.nilai_lama, kp.nilai_baru, kp.pertemuan_ke, kp.alasan, kp.created_at,
    COALESCE(s.nama, '') AS santri_nama,
    COALESCE(ka.nama_kelas, '') AS kelas_asal_nama,
    COALESCE(kt.nama_kelas, '') AS kelas_tujuan_nama,
    COALESCE(u.name, 'Sistem') AS dibuat_oleh_nama
FROM kelas_perubahan kp
LEFT JOIN santri s ON s.id = kp.santri_id
LEFT JOIN kelas ka ON ka.id = kp.kelas_id
LEFT JOIN kelas kt ON kt.id = kp.kelas_tujuan_id
LEFT JOIN users u ON u.id = kp.dibuat_oleh
WHERE kp.kelas_id = ?1 OR kp.kelas_tujuan_id = ?1
ORDER BY kp.created_at DESC, kp.id DESC
LIMIT 50
`

type ListKelasPerubahanByKelasRow struct {
	ID              int64
	KelasID         sql.NullInt64
	SantriID        sql.NullInt64
	KelasTujuanID   sql.NullInt64
	Jenis           string
	NilaiLama       string
	NilaiBaru       string
	PertemuanKe     int64
	Alasan          string
	CreatedAt       time.Time
	SantriNama      string
	KelasAsalNama   string
	KelasTujuanNama string
	DibuatOlehNama  string
}

func (q *Queries) ListKelasPerubahanByKelas(ctx context.Context, kelasID sql.NullInt64) ([]ListKelasPerubahanByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasPerubahanByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasPerubahanByKelasRow
	for rows.Next() {
		var i ListKelasPerubahanByKelasRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.SantriID,
			&i.KelasTujuanID,
			&i.Jenis,
			&i.NilaiLama,
			&i.NilaiBaru,
			&i.PertemuanKe,
			&i.Alasan,
			&i.CreatedAt,
			&i.SantriNama,
			&i.KelasAsalNama,
			&i.KelasTujuanNama,
			&i.DibuatOlehNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKelasAwalPertemuan = `-- name: SetKelasAwalPertemuan :exec
UPDATE kelas SET pertemuan_terakhir = ?, level_pertemuan_awal = ?, kapasitas = ? WHERE id = ?
`

type SetKelasAwalPertemuanParams struct {
	PertemuanTerakhir  int64
	LevelPertemuanAwal int64
	Kapasitas          int64
	ID                 int64
}

// Kelas baru hasil naik level melanjutkan nomor internal kelas asal (untuk
// periode tagihan) sementara nomor per level tetap mulai dari 1.
func (q *Queries) SetKelasAwalPertemuan(ctx context.Context, arg SetKelasAwalPertemuanParams) error {
	_, err := q.db.ExecContext(ctx, setKelasAwalPertemuan,
		arg.PertemuanTerakhir,
		arg.LevelPertemuanAwal,
		arg.Kapasitas,
		arg.ID,
	)
	return err
}

const syncSantriLevelJadwalByKelas = `-- name: SyncSantriLevelJadwalByKelas :exec
UPDATE santri SET level = ?, jadwal = ?, updated_at = ? WHERE kelas_id = ?
`

type SyncSantriLevelJadwalByKelasParams struct {
	Level     string
	Jadwal    string
	UpdatedAt time.Time
	KelasID   sql.NullInt64
}

func (q *Queries) SyncSantriLevelJadwalByKelas(ctx context.Context, arg SyncSantriLevelJadwalByKelasParams) error {
	_, err := q.db.ExecContext(ctx, syncSantriLevelJadwalByKelas,
		arg.Level,
		arg.Jadwal,
		arg.UpdatedAt,
		arg.KelasID,
	)
	return err
}

const updateKelasIdentitas = `-- name: UpdateKelasIdentitas :exec
UPDATE kelas
SET level = ?, jadwal = ?, kunci_kelas = ?, sub_index = ?, nama_kelas = ?, level_pertemuan_awal = ?
WHERE id = ?
`

type UpdateKelasIdentitasParams struct {
	Level              string
	Jadwal             string
	KunciKelas         string
	SubIndex           int64
	NamaKelas          string
	LevelPertemuanAwal int64
	ID                 int64
}

// Dipakai ganti level / ganti jadwal: level & jadwal adalah bagian dari
// kunci_kelas, jadi kunci, sub_index, dan nama ikut dibentuk ulang.
func (q *Queries) UpdateKelasIdentitas(ctx context.Context, arg UpdateKelasIdentitasParams) error {
	_, err := q.db.ExecContext(ctx, updateKelasIdentitas,
		arg.Level,
		arg.Jadwal,
		arg.KunciKelas,
		arg.SubIndex,
		arg.NamaKelas,
		arg.LevelPertemuanAwal,
		arg.ID,
	)
	return err
}


const getPertemuanRebaseBounds = `-- name: GetPertemuanRebaseBounds :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(MIN(pertemuan_ke), 0) AS INTEGER) AS min_pertemuan_ke,
    CAST(COALESCE(MAX(pertemuan_ke), 0) AS INTEGER) AS max_pertemuan_ke
FROM pertemuan
WHERE kelas_id = ?
`

type GetPertemuanRebaseBoundsRow struct {
	Total            int64
	MinPertemuanKe   int64
	MaxPertemuanKe   int64
}

func (q *Queries) GetPertemuanRebaseBounds(ctx context.Context, kelasID int64) (GetPertemuanRebaseBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, getPertemuanRebaseBounds, kelasID)
	var i GetPertemuanRebaseBoundsRow
	err := row.Scan(&i.Total, &i.MinPertemuanKe, &i.MaxPertemuanKe)
	return i, err
}

const getFirstLevelChangeBoundary = `-- name: GetFirstLevelChangeBoundary :one
SELECT CAST(COALESCE(MIN(pertemuan_ke), 0) AS INTEGER)
FROM kelas_perubahan
WHERE kelas_id = ? AND jenis = 'level_kelas' AND pertemuan_ke > 0
`

func (q *Queries) GetFirstLevelChangeBoundary(ctx context.Context, kelasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFirstLevelChangeBoundary, kelasID)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const getFirstPertemuanLevelKe = `-- name: GetFirstPertemuanLevelKe :one
SELECT pertemuan_level_ke
FROM pertemuan
WHERE kelas_id = ?
ORDER BY pertemuan_ke ASC, id ASC
LIMIT 1
`

func (q *Queries) GetFirstPertemuanLevelKe(ctx context.Context, kelasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFirstPertemuanLevelKe, kelasID)
	var pertemuanLevelKe int64
	err := row.Scan(&pertemuanLevelKe)
	return pertemuanLevelKe, err
}

const shiftPertemuanLevelKeThrough = `-- name: ShiftPertemuanLevelKeThrough :exec
UPDATE pertemuan
SET pertemuan_level_ke = pertemuan_level_ke + ?1
WHERE kelas_id = ?2
  AND pertemuan_ke <= ?3
`

type ShiftPertemuanLevelKeThroughParams struct {
	Delta    int64
	KelasID  int64
	Boundary int64
}

func (q *Queries) ShiftPertemuanLevelKeThrough(ctx context.Context, arg ShiftPertemuanLevelKeThroughParams) error {
	_, err := q.db.ExecContext(ctx, shiftPertemuanLevelKeThrough, arg.Delta, arg.KelasID, arg.Boundary)
	return err
}

const shiftAllPertemuanLevelKe = `-- name: ShiftAllPertemuanLevelKe :exec
UPDATE pertemuan
SET pertemuan_level_ke = pertemuan_level_ke + ?1
WHERE kelas_id = ?2
`

type ShiftAllPertemuanLevelKeParams struct {
	Delta   int64
	KelasID int64
}

func (q *Queries) ShiftAllPertemuanLevelKe(ctx context.Context, arg ShiftAllPertemuanLevelKeParams) error {
	_, err := q.db.ExecContext(ctx, shiftAllPertemuanLevelKe, arg.Delta, arg.KelasID)
	return err
}

const offsetPertemuanKeForRebase = `-- name: OffsetPertemuanKeForRebase :exec
UPDATE pertemuan
SET pertemuan_ke = pertemuan_ke + ?1
WHERE kelas_id = ?2
`

type OffsetPertemuanKeForRebaseParams struct {
	Offset  int64
	KelasID int64
}

func (q *Queries) OffsetPertemuanKeForRebase(ctx context.Context, arg OffsetPertemuanKeForRebaseParams) error {
	_, err := q.db.ExecContext(ctx, offsetPertemuanKeForRebase, arg.Offset, arg.KelasID)
	return err
}

const finalizePertemuanKeRebase = `-- name: FinalizePertemuanKeRebase :exec
UPDATE pertemuan
SET pertemuan_ke = pertemuan_ke - ?1 + ?2
WHERE kelas_id = ?3
`

type FinalizePertemuanKeRebaseParams struct {
	Offset  int64
	Delta   int64
	KelasID int64
}

func (q *Queries) FinalizePertemuanKeRebase(ctx context.Context, arg FinalizePertemuanKeRebaseParams) error {
	_, err := q.db.ExecContext(ctx, finalizePertemuanKeRebase, arg.Offset, arg.Delta, arg.KelasID)
	return err
}

const rebaseKelasMeetingAnchors = `-- name: RebaseKelasMeetingAnchors :exec
UPDATE kelas
SET pertemuan_terakhir = ?1,
    level_pertemuan_awal = CASE
        WHEN level_pertemuan_awal > 0 THEN level_pertemuan_awal + ?2
        ELSE level_pertemuan_awal
    END
WHERE id = ?3
`

type RebaseKelasMeetingAnchorsParams struct {
	NewAnchor int64
	Delta     int64
	KelasID   int64
}

func (q *Queries) RebaseKelasMeetingAnchors(ctx context.Context, arg RebaseKelasMeetingAnchorsParams) error {
	_, err := q.db.ExecContext(ctx, rebaseKelasMeetingAnchors, arg.NewAnchor, arg.Delta, arg.KelasID)
	return err
}

const shiftLevelChangeBoundaries = `-- name: ShiftLevelChangeBoundaries :exec
UPDATE kelas_perubahan
SET pertemuan_ke = pertemuan_ke + ?1
WHERE kelas_id = ?2
  AND jenis = 'level_kelas'
  AND pertemuan_ke > 0
`

type ShiftLevelChangeBoundariesParams struct {
	Delta   int64
	KelasID int64
}

func (q *Queries) ShiftLevelChangeBoundaries(ctx context.Context, arg ShiftLevelChangeBoundariesParams) error {
	_, err := q.db.ExecContext(ctx, shiftLevelChangeBoundaries, arg.Delta, arg.KelasID)
	return err
}

const shiftSantriPertemuanAwalByKelas = `-- name: ShiftSantriPertemuanAwalByKelas :exec
UPDATE santri
SET pertemuan_awal = pertemuan_awal + ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE kelas_id = ?2
  AND pertemuan_awal > 0
`

type ShiftSantriPertemuanAwalByKelasParams struct {
	Delta   int64
	KelasID int64
}

func (q *Queries) ShiftSantriPertemuanAwalByKelas(ctx context.Context, arg ShiftSantriPertemuanAwalByKelasParams) error {
	_, err := q.db.ExecContext(ctx, shiftSantriPertemuanAwalByKelas, arg.Delta, arg.KelasID)
	return err
}

const syncTagihanPertemuanKeByKelas = `-- name: SyncTagihanPertemuanKeByKelas :exec
UPDATE tagihan
SET pertemuan_ke = (
    SELECT p.pertemuan_ke
    FROM pertemuan p
    WHERE p.id = tagihan.pertemuan_id
)
WHERE kelas_id = ?1
  AND pertemuan_id IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM pertemuan p
      WHERE p.id = tagihan.pertemuan_id
        AND p.kelas_id = ?1
  )
`

func (q *Queries) SyncTagihanPertemuanKeByKelas(ctx context.Context, kelasID int64) error {
	_, err := q.db.ExecContext(ctx, syncTagihanPertemuanKeByKelas, kelasID)
	return err
}
