// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kelas_perubahan.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createKelasPerubahan = `-- name: CreateKelasPerubahan :exec
INSERT INTO kelas_perubahan (
    kelas_id, santri_id, kelas_tujuan_id, jenis, nilai_lama, nilai_baru, pertemuan_ke, dibuat_oleh
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateKelasPerubahanParams struct {
	KelasID       sql.NullInt64
	SantriID      sql.NullInt64
	KelasTujuanID sql.NullInt64
	Jenis         string
	NilaiLama     string
	NilaiBaru     string
	PertemuanKe   int64
	DibuatOleh    sql.NullInt64
}

func (q *Queries) CreateKelasPerubahan(ctx context.Context, arg CreateKelasPerubahanParams) error {
	_, err := q.db.ExecContext(ctx, createKelasPerubahan,
		arg.KelasID,
		arg.SantriID,
		arg.KelasTujuanID,
		arg.Jenis,
		arg.NilaiLama,
		arg.NilaiBaru,
		arg.PertemuanKe,
		arg.DibuatOleh,
	)
	return err
}

const getKelasPerubahanState = `-- name: GetKelasPerubahanState :one
SELECT id, kunci_kelas, level, jadwal, sub_index, level_pertemuan_awal
FROM kelas WHERE id = ?
`

type GetKelasPerubahanStateRow struct {
	ID                 int64
	KunciKelas         string
	Level              string
	Jadwal             string
	SubIndex           int64
	LevelPertemuanAwal int64
}

func (q *Queries) GetKelasPerubahanState(ctx context.Context, id int64) (GetKelasPerubahanStateRow, error) {
	row := q.db.QueryRowContext(ctx, getKelasPerubahanState, id)
	var i GetKelasPerubahanStateRow
	err := row.Scan(
		&i.ID,
		&i.KunciKelas,
		&i.Level,
		&i.Jadwal,
		&i.SubIndex,
		&i.LevelPertemuanAwal,
	)
	return i, err
}

const listKelasPerubahanByKelas = `-- name: ListKelasPerubahanByKelas :many
SELECT
    kp.id, kp.kelas_id, kp.santri_id, kp.kelas_tujuan_id, kp.jenis,
    kp.nilai_lama, kp.nilai_baru, kp.pertemuan_ke, kp.created_at,
    COALESCE(s.nama, '') AS santri_nama,
    COALESCE(ka.nama_kelas, '') AS kelas_asal_nama,
    COALESCE(kt.nama_kelas, '') AS kelas_tujuan_nama,
    COALESCE(u.name, 'Sistem') AS dibuat_oleh_nama
FROM kelas_perubahan kp
LEFT JOIN santri s ON s.id = kp.santri_id
LEFT JOIN kelas ka ON ka.id = kp.kelas_id
LEFT JOIN kelas kt ON kt.id = kp.kelas_tujuan_id
LEFT JOIN users u ON u.id = kp.dibuat_oleh
WHERE kp.kelas_id = ?1 OR kp.kelas_tujuan_id = ?1
ORDER BY kp.created_at DESC, kp.id DESC
LIMIT 50
`

type ListKelasPerubahanByKelasRow struct {
	ID              int64
	KelasID         sql.NullInt64
	SantriID        sql.NullInt64
	KelasTujuanID   sql.NullInt64
	Jenis           string
	NilaiLama       string
	NilaiBaru       string
	PertemuanKe     int64
	CreatedAt       time.Time
	SantriNama      string
	KelasAsalNama   string
	KelasTujuanNama string
	DibuatOlehNama  string
}

func (q *Queries) ListKelasPerubahanByKelas(ctx context.Context, kelasID sql.NullInt64) ([]ListKelasPerubahanByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasPerubahanByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasPerubahanByKelasRow
	for rows.Next() {
		var i ListKelasPerubahanByKelasRow
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.SantriID,
			&i.KelasTujuanID,
			&i.Jenis,
			&i.NilaiLama,
			&i.NilaiBaru,
			&i.PertemuanKe,
			&i.CreatedAt,
			&i.SantriNama,
			&i.KelasAsalNama,
			&i.KelasTujuanNama,
			&i.DibuatOlehNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKelasAwalPertemuan = `-- name: SetKelasAwalPertemuan :exec
UPDATE kelas SET pertemuan_terakhir = ?, level_pertemuan_awal = ?, kapasitas = ? WHERE id = ?
`

type SetKelasAwalPertemuanParams struct {
	PertemuanTerakhir  int64
	LevelPertemuanAwal int64
	Kapasitas          int64
	ID                 int64
}

// Kelas baru hasil naik level melanjutkan nomor internal kelas asal (untuk
// periode tagihan) sementara nomor per level tetap mulai dari 1.
func (q *Queries) SetKelasAwalPertemuan(ctx context.Context, arg SetKelasAwalPertemuanParams) error {
	_, err := q.db.ExecContext(ctx, setKelasAwalPertemuan,
		arg.PertemuanTerakhir,
		arg.LevelPertemuanAwal,
		arg.Kapasitas,
		arg.ID,
	)
	return err
}

const syncSantriLevelJadwalByKelas = `-- name: SyncSantriLevelJadwalByKelas :exec
UPDATE santri SET level = ?, jadwal = ?, updated_at = ? WHERE kelas_id = ?
`

type SyncSantriLevelJadwalByKelasParams struct {
	Level     string
	Jadwal    string
	UpdatedAt time.Time
	KelasID   sql.NullInt64
}

func (q *Queries) SyncSantriLevelJadwalByKelas(ctx context.Context, arg SyncSantriLevelJadwalByKelasParams) error {
	_, err := q.db.ExecContext(ctx, syncSantriLevelJadwalByKelas,
		arg.Level,
		arg.Jadwal,
		arg.UpdatedAt,
		arg.KelasID,
	)
	return err
}

const updateKelasIdentitas = `-- name: UpdateKelasIdentitas :exec
UPDATE kelas
SET level = ?, jadwal = ?, kunci_kelas = ?, sub_index = ?, nama_kelas = ?, level_pertemuan_awal = ?
WHERE id = ?
`

type UpdateKelasIdentitasParams struct {
	Level              string
	Jadwal             string
	KunciKelas         string
	SubIndex           int64
	NamaKelas          string
	LevelPertemuanAwal int64
	ID                 int64
}

// Dipakai ganti level / ganti jadwal: level & jadwal adalah bagian dari
// kunci_kelas, jadi kunci, sub_index, dan nama ikut dibentuk ulang.
func (q *Queries) UpdateKelasIdentitas(ctx context.Context, arg UpdateKelasIdentitasParams) error {
	_, err := q.db.ExecContext(ctx, updateKelasIdentitas,
		arg.Level,
		arg.Jadwal,
		arg.KunciKelas,
		arg.SubIndex,
		arg.NamaKelas,
		arg.LevelPertemuanAwal,
		arg.ID,
	)
	return err
}
