// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kelas.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const assignGuru = `-- name: AssignGuru :exec
UPDATE kelas SET guru_id = ? WHERE id = ?
`

type AssignGuruParams struct {
	GuruID sql.NullInt64
	ID     int64
}

func (q *Queries) AssignGuru(ctx context.Context, arg AssignGuruParams) error {
	_, err := q.db.ExecContext(ctx, assignGuru, arg.GuruID, arg.ID)
	return err
}

const countKelasByAngkatan = `-- name: CountKelasByAngkatan :many
SELECT angkatan, COUNT(*) as total FROM kelas
GROUP BY angkatan
ORDER BY angkatan
`

type CountKelasByAngkatanRow struct {
	Angkatan string
	Total    int64
}

func (q *Queries) CountKelasByAngkatan(ctx context.Context) ([]CountKelasByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, countKelasByAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountKelasByAngkatanRow
	for rows.Next() {
		var i CountKelasByAngkatanRow
		if err := rows.Scan(&i.Angkatan, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countKelasTotal = `-- name: CountKelasTotal :one
SELECT COUNT(*) FROM kelas
`

func (q *Queries) CountKelasTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKelasTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKelas = `-- name: CreateKelas :execresult
INSERT INTO kelas (
    kunci_kelas, angkatan, tipe, jenis_kelamin, level, frekuensi,
    jadwal, sub_index, nama_kelas, guru_id, kapasitas, jumlah_santri,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?
)
`

type CreateKelasParams struct {
	KunciKelas   string
	Angkatan     string
	Tipe         string
	JenisKelamin string
	Level        string
	Frekuensi    string
	Jadwal       string
	SubIndex     int64
	NamaKelas    string
	GuruID       sql.NullInt64
	Kapasitas    int64
	JumlahSantri int64
	CreatedAt    time.Time
}

func (q *Queries) CreateKelas(ctx context.Context, arg CreateKelasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createKelas,
		arg.KunciKelas,
		arg.Angkatan,
		arg.Tipe,
		arg.JenisKelamin,
		arg.Level,
		arg.Frekuensi,
		arg.Jadwal,
		arg.SubIndex,
		arg.NamaKelas,
		arg.GuruID,
		arg.Kapasitas,
		arg.JumlahSantri,
		arg.CreatedAt,
	)
}

const decrementJumlahSantri = `-- name: DecrementJumlahSantri :exec
UPDATE kelas SET jumlah_santri = jumlah_santri - 1 WHERE id = ?
`

func (q *Queries) DecrementJumlahSantri(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, decrementJumlahSantri, id)
	return err
}

const deleteKelas = `-- name: DeleteKelas :exec
DELETE FROM kelas WHERE id = ?
`

func (q *Queries) DeleteKelas(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKelas, id)
	return err
}

const findKelasByKunci = `-- name: FindKelasByKunci :many

SELECT id, kunci_kelas, angkatan, tipe, jenis_kelamin, level, frekuensi, jadwal, sub_index, nama_kelas, guru_id, kapasitas,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = kelas.id AND s.status != 'tidak_lanjut') AS jumlah_santri,
    created_at, is_aktif
FROM kelas
WHERE kunci_kelas = ?
ORDER BY sub_index ASC
`

type FindKelasByKunciRow struct {
	ID           int64
	KunciKelas   string
	Angkatan     string
	Tipe         string
	JenisKelamin string
	Level        string
	Frekuensi    string
	Jadwal       string
	SubIndex     int64
	NamaKelas    string
	GuruID       sql.NullInt64
	Kapasitas    int64
	JumlahSantri int64
	CreatedAt    time.Time
	IsAktif      int64
}

// jumlah_santri is computed live as the count of ACTIVE santri (excluding
// tidak_lanjut) so class occupancy reflects only continuing mahasantri.
func (q *Queries) FindKelasByKunci(ctx context.Context, kunciKelas string) ([]FindKelasByKunciRow, error) {
	rows, err := q.db.QueryContext(ctx, findKelasByKunci, kunciKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindKelasByKunciRow
	for rows.Next() {
		var i FindKelasByKunciRow
		if err := rows.Scan(
			&i.ID,
			&i.KunciKelas,
			&i.Angkatan,
			&i.Tipe,
			&i.JenisKelamin,
			&i.Level,
			&i.Frekuensi,
			&i.Jadwal,
			&i.SubIndex,
			&i.NamaKelas,
			&i.GuruID,
			&i.Kapasitas,
			&i.JumlahSantri,
			&i.CreatedAt,
			&i.IsAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKelasByID = `-- name: GetKelasByID :one
SELECT id, kunci_kelas, angkatan, tipe, jenis_kelamin, level, frekuensi, jadwal, sub_index, nama_kelas, guru_id, kapasitas,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = kelas.id AND s.status != 'tidak_lanjut') AS jumlah_santri,
    created_at, is_aktif
FROM kelas WHERE kelas.id = ?
`

type GetKelasByIDRow struct {
	ID           int64
	KunciKelas   string
	Angkatan     string
	Tipe         string
	JenisKelamin string
	Level        string
	Frekuensi    string
	Jadwal       string
	SubIndex     int64
	NamaKelas    string
	GuruID       sql.NullInt64
	Kapasitas    int64
	JumlahSantri int64
	CreatedAt    time.Time
	IsAktif      int64
}

func (q *Queries) GetKelasByID(ctx context.Context, id int64) (GetKelasByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getKelasByID, id)
	var i GetKelasByIDRow
	err := row.Scan(
		&i.ID,
		&i.KunciKelas,
		&i.Angkatan,
		&i.Tipe,
		&i.JenisKelamin,
		&i.Level,
		&i.Frekuensi,
		&i.Jadwal,
		&i.SubIndex,
		&i.NamaKelas,
		&i.GuruID,
		&i.Kapasitas,
		&i.JumlahSantri,
		&i.CreatedAt,
		&i.IsAktif,
	)
	return i, err
}

const incrementJumlahSantri = `-- name: IncrementJumlahSantri :exec
UPDATE kelas SET jumlah_santri = jumlah_santri + 1 WHERE id = ?
`

func (q *Queries) IncrementJumlahSantri(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementJumlahSantri, id)
	return err
}

const listKelasByAngkatan = `-- name: ListKelasByAngkatan :many
SELECT id, kunci_kelas, angkatan, tipe, jenis_kelamin, level, frekuensi, jadwal, sub_index, nama_kelas, guru_id, kapasitas,
    (SELECT COUNT(*) FROM santri s WHERE s.kelas_id = kelas.id AND s.status != 'tidak_lanjut') AS jumlah_santri,
    created_at, is_aktif
FROM kelas
WHERE (?1 = '' OR angkatan = ?1)
ORDER BY angkatan, tipe, jenis_kelamin, level, sub_index
`

type ListKelasByAngkatanRow struct {
	ID           int64
	KunciKelas   string
	Angkatan     string
	Tipe         string
	JenisKelamin string
	Level        string
	Frekuensi    string
	Jadwal       string
	SubIndex     int64
	NamaKelas    string
	GuruID       sql.NullInt64
	Kapasitas    int64
	JumlahSantri int64
	CreatedAt    time.Time
	IsAktif      int64
}

func (q *Queries) ListKelasByAngkatan(ctx context.Context, angkatan interface{}) ([]ListKelasByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasByAngkatan, angkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasByAngkatanRow
	for rows.Next() {
		var i ListKelasByAngkatanRow
		if err := rows.Scan(
			&i.ID,
			&i.KunciKelas,
			&i.Angkatan,
			&i.Tipe,
			&i.JenisKelamin,
			&i.Level,
			&i.Frekuensi,
			&i.Jadwal,
			&i.SubIndex,
			&i.NamaKelas,
			&i.GuruID,
			&i.Kapasitas,
			&i.JumlahSantri,
			&i.CreatedAt,
			&i.IsAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKelasAktif = `-- name: SetKelasAktif :exec
UPDATE kelas SET is_aktif = ? WHERE id = ?
`

type SetKelasAktifParams struct {
	IsAktif int64
	ID      int64
}

func (q *Queries) SetKelasAktif(ctx context.Context, arg SetKelasAktifParams) error {
	_, err := q.db.ExecContext(ctx, setKelasAktif, arg.IsAktif, arg.ID)
	return err
}
