// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kode_kelas.sql

package queries

import (
	"context"
)

const createKodeKelas = `-- name: CreateKodeKelas :exec
INSERT INTO kode_kelas (kode, tipe, frekuensi, urutan) VALUES (?, ?, ?, ?)
`

type CreateKodeKelasParams struct {
	Kode      string
	Tipe      string
	Frekuensi string
	Urutan    int64
}

func (q *Queries) CreateKodeKelas(ctx context.Context, arg CreateKodeKelasParams) error {
	_, err := q.db.ExecContext(ctx, createKodeKelas,
		arg.Kode,
		arg.Tipe,
		arg.Frekuensi,
		arg.Urutan,
	)
	return err
}

const deleteKodeKelas = `-- name: DeleteKodeKelas :exec
DELETE FROM kode_kelas WHERE id = ?
`

func (q *Queries) DeleteKodeKelas(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKodeKelas, id)
	return err
}

const getKodeKelasByKode = `-- name: GetKodeKelasByKode :one
SELECT id, kode, tipe, frekuensi, urutan FROM kode_kelas WHERE kode = ?
`

func (q *Queries) GetKodeKelasByKode(ctx context.Context, kode string) (KodeKela, error) {
	row := q.db.QueryRowContext(ctx, getKodeKelasByKode, kode)
	var i KodeKela
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Tipe,
		&i.Frekuensi,
		&i.Urutan,
	)
	return i, err
}

const listKodeKelas = `-- name: ListKodeKelas :many
SELECT id, kode, tipe, frekuensi, urutan FROM kode_kelas ORDER BY urutan ASC
`

func (q *Queries) ListKodeKelas(ctx context.Context) ([]KodeKela, error) {
	rows, err := q.db.QueryContext(ctx, listKodeKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KodeKela
	for rows.Next() {
		var i KodeKela
		if err := rows.Scan(
			&i.ID,
			&i.Kode,
			&i.Tipe,
			&i.Frekuensi,
			&i.Urutan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKodeKelas = `-- name: UpdateKodeKelas :exec
UPDATE kode_kelas SET tipe = ?, frekuensi = ?, urutan = ? WHERE id = ?
`

type UpdateKodeKelasParams struct {
	Tipe      string
	Frekuensi string
	Urutan    int64
	ID        int64
}

func (q *Queries) UpdateKodeKelas(ctx context.Context, arg UpdateKodeKelasParams) error {
	_, err := q.db.ExecContext(ctx, updateKodeKelas,
		arg.Tipe,
		arg.Frekuensi,
		arg.Urutan,
		arg.ID,
	)
	return err
}
