// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: koordinator.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countGuruAktifTotal = `-- name: CountGuruAktifTotal :one
SELECT COUNT(*) FROM guru WHERE is_aktif = 1
`

func (q *Queries) CountGuruAktifTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuruAktifTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuruByStatusAktif = `-- name: CountGuruByStatusAktif :one
SELECT COUNT(*) FROM guru WHERE is_aktif = 1 AND status = ?
`

func (q *Queries) CountGuruByStatusAktif(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuruByStatusAktif, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKalamShareByGuruRange = `-- name: CountKalamShareByGuruRange :one
SELECT COUNT(*) FROM kalam_share_log ksl
JOIN kalam_bersanad kb ON kb.id = ksl.kalam_id
WHERE ksl.guru_id = ? AND kb.tanggal >= ? AND kb.tanggal <= ?
`

type CountKalamShareByGuruRangeParams struct {
	GuruID    int64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountKalamShareByGuruRange(ctx context.Context, arg CountKalamShareByGuruRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKalamShareByGuruRange, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKelasAktifTotal = `-- name: CountKelasAktifTotal :one
SELECT COUNT(*) FROM kelas WHERE is_aktif = 1
`

func (q *Queries) CountKelasAktifTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKelasAktifTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPembinaanHadirByGuru = `-- name: CountPembinaanHadirByGuru :one
SELECT COUNT(*) FROM pembinaan_absen pa
JOIN pembinaan p ON p.id = pa.pembinaan_id
WHERE pa.guru_id = ? AND pa.hadir = 1 AND p.status = 'terlaksana' AND p.tanggal >= ? AND p.tanggal <= ?
`

type CountPembinaanHadirByGuruParams struct {
	GuruID    int64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountPembinaanHadirByGuru(ctx context.Context, arg CountPembinaanHadirByGuruParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPembinaanHadirByGuru, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPembinaanTerlaksana = `-- name: CountPembinaanTerlaksana :one
SELECT COUNT(*) FROM pembinaan WHERE status = 'terlaksana' AND tanggal >= ? AND tanggal <= ?
`

type CountPembinaanTerlaksanaParams struct {
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountPembinaanTerlaksana(ctx context.Context, arg CountPembinaanTerlaksanaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPembinaanTerlaksana, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRapatHadirByGuru = `-- name: CountRapatHadirByGuru :one
SELECT COUNT(*) FROM rapat_absen ra
JOIN rapat_guru r ON r.id = ra.rapat_id
WHERE ra.guru_id = ? AND ra.hadir = 1 AND r.status = 'terlaksana' AND r.tanggal >= ? AND r.tanggal <= ?
`

type CountRapatHadirByGuruParams struct {
	GuruID    int64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountRapatHadirByGuru(ctx context.Context, arg CountRapatHadirByGuruParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRapatHadirByGuru, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSantriAktifTotal = `-- name: CountSantriAktifTotal :one
SELECT COUNT(*) FROM santri WHERE status = 'aktif'
`

func (q *Queries) CountSantriAktifTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSantriAktifTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTilawahByGuruRange = `-- name: CountTilawahByGuruRange :one
SELECT COUNT(*) FROM tilawah_harian WHERE guru_id = ? AND tanggal >= ? AND tanggal <= ?
`

type CountTilawahByGuruRangeParams struct {
	GuruID    int64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountTilawahByGuruRange(ctx context.Context, arg CountTilawahByGuruRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTilawahByGuruRange, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKalam = `-- name: CreateKalam :one

INSERT INTO kalam_bersanad (tanggal, topik, kitab, keterangan) VALUES (?, ?, ?, ?) RETURNING id
`

type CreateKalamParams struct {
	Tanggal    time.Time
	Topik      string
	Kitab      string
	Keterangan string
}

// ============ Kalam Bersanad ============
func (q *Queries) CreateKalam(ctx context.Context, arg CreateKalamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createKalam,
		arg.Tanggal,
		arg.Topik,
		arg.Kitab,
		arg.Keterangan,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createKunjungan = `-- name: CreateKunjungan :one

INSERT INTO kunjungan_kelas (guru_id, kelas_id, target_mulai, target_selesai, tanggal, jam, status, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateKunjunganParams struct {
	GuruID        int64
	KelasID       sql.NullInt64
	TargetMulai   sql.NullTime
	TargetSelesai sql.NullTime
	Tanggal       sql.NullTime
	Jam           string
	Status        string
	Catatan       string
}

// ============ Kunjungan Kelas ============
func (q *Queries) CreateKunjungan(ctx context.Context, arg CreateKunjunganParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createKunjungan,
		arg.GuruID,
		arg.KelasID,
		arg.TargetMulai,
		arg.TargetSelesai,
		arg.Tanggal,
		arg.Jam,
		arg.Status,
		arg.Catatan,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPembinaan = `-- name: CreatePembinaan :one

INSERT INTO pembinaan (tanggal, bulan, pekan_ke, topik, keterangan, status)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id
`

type CreatePembinaanParams struct {
	Tanggal    time.Time
	Bulan      string
	PekanKe    int64
	Topik      string
	Keterangan string
	Status     string
}

// ============ Pembinaan ============
func (q *Queries) CreatePembinaan(ctx context.Context, arg CreatePembinaanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPembinaan,
		arg.Tanggal,
		arg.Bulan,
		arg.PekanKe,
		arg.Topik,
		arg.Keterangan,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createRapat = `-- name: CreateRapat :one

INSERT INTO rapat_guru (tanggal, judul, catatan, status) VALUES (?, ?, ?, ?) RETURNING id
`

type CreateRapatParams struct {
	Tanggal time.Time
	Judul   string
	Catatan string
	Status  string
}

// ============ Rapat Guru ============
func (q *Queries) CreateRapat(ctx context.Context, arg CreateRapatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRapat,
		arg.Tanggal,
		arg.Judul,
		arg.Catatan,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTilawah = `-- name: CreateTilawah :exec

INSERT INTO tilawah_harian (guru_id, tanggal) VALUES (?, ?) ON CONFLICT(guru_id, tanggal) DO NOTHING
`

type CreateTilawahParams struct {
	GuruID  int64
	Tanggal time.Time
}

// ============ Tilawah Harian ============
func (q *Queries) CreateTilawah(ctx context.Context, arg CreateTilawahParams) error {
	_, err := q.db.ExecContext(ctx, createTilawah, arg.GuruID, arg.Tanggal)
	return err
}

const createWaTemplate = `-- name: CreateWaTemplate :one

INSERT INTO wa_template (nama, target_type, body, is_aktif) VALUES (?, ?, ?, ?) RETURNING id
`

type CreateWaTemplateParams struct {
	Nama       string
	TargetType string
	Body       string
	IsAktif    int64
}

// ============ WA Template ============
func (q *Queries) CreateWaTemplate(ctx context.Context, arg CreateWaTemplateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWaTemplate,
		arg.Nama,
		arg.TargetType,
		arg.Body,
		arg.IsAktif,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteKalam = `-- name: DeleteKalam :exec
DELETE FROM kalam_bersanad WHERE id = ?
`

func (q *Queries) DeleteKalam(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKalam, id)
	return err
}

const deleteKunjungan = `-- name: DeleteKunjungan :exec
DELETE FROM kunjungan_kelas WHERE id = ?
`

func (q *Queries) DeleteKunjungan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKunjungan, id)
	return err
}

const deletePembinaan = `-- name: DeletePembinaan :exec
DELETE FROM pembinaan WHERE id = ?
`

func (q *Queries) DeletePembinaan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePembinaan, id)
	return err
}

const deleteRapat = `-- name: DeleteRapat :exec
DELETE FROM rapat_guru WHERE id = ?
`

func (q *Queries) DeleteRapat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRapat, id)
	return err
}

const deleteTilawah = `-- name: DeleteTilawah :exec
DELETE FROM tilawah_harian WHERE guru_id = ? AND tanggal = ?
`

type DeleteTilawahParams struct {
	GuruID  int64
	Tanggal time.Time
}

func (q *Queries) DeleteTilawah(ctx context.Context, arg DeleteTilawahParams) error {
	_, err := q.db.ExecContext(ctx, deleteTilawah, arg.GuruID, arg.Tanggal)
	return err
}

const deleteWaTemplate = `-- name: DeleteWaTemplate :exec
DELETE FROM wa_template WHERE id = ?
`

func (q *Queries) DeleteWaTemplate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWaTemplate, id)
	return err
}

const existsTilawah = `-- name: ExistsTilawah :one
SELECT COUNT(*) FROM tilawah_harian WHERE guru_id = ? AND tanggal = ?
`

type ExistsTilawahParams struct {
	GuruID  int64
	Tanggal time.Time
}

func (q *Queries) ExistsTilawah(ctx context.Context, arg ExistsTilawahParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsTilawah, arg.GuruID, arg.Tanggal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGuruKompetensi = `-- name: GetGuruKompetensi :one

SELECT guru_id, hafalan_quran, hafalan_tuhfah, hafalan_jazariy, hafalan_khaqaniy, hafalan_syakhawiy, sanad_qiroah, bahasa_arab_pasif, bahasa_arab_aktif, updated_at FROM guru_kompetensi WHERE guru_id = ?
`

// ============ Kompetensi ============
func (q *Queries) GetGuruKompetensi(ctx context.Context, guruID int64) (GuruKompetensi, error) {
	row := q.db.QueryRowContext(ctx, getGuruKompetensi, guruID)
	var i GuruKompetensi
	err := row.Scan(
		&i.GuruID,
		&i.HafalanQuran,
		&i.HafalanTuhfah,
		&i.HafalanJazariy,
		&i.HafalanKhaqaniy,
		&i.HafalanSyakhawiy,
		&i.SanadQiroah,
		&i.BahasaArabPasif,
		&i.BahasaArabAktif,
		&i.UpdatedAt,
	)
	return i, err
}

const getKalam = `-- name: GetKalam :one
SELECT id, tanggal, topik, kitab, keterangan, created_at, updated_at FROM kalam_bersanad WHERE id = ?
`

func (q *Queries) GetKalam(ctx context.Context, id int64) (KalamBersanad, error) {
	row := q.db.QueryRowContext(ctx, getKalam, id)
	var i KalamBersanad
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.Topik,
		&i.Kitab,
		&i.Keterangan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKunjungan = `-- name: GetKunjungan :one
SELECT id, guru_id, kelas_id, target_mulai, target_selesai, tanggal, jam, status, catatan, created_at, updated_at FROM kunjungan_kelas WHERE id = ?
`

func (q *Queries) GetKunjungan(ctx context.Context, id int64) (KunjunganKela, error) {
	row := q.db.QueryRowContext(ctx, getKunjungan, id)
	var i KunjunganKela
	err := row.Scan(
		&i.ID,
		&i.GuruID,
		&i.KelasID,
		&i.TargetMulai,
		&i.TargetSelesai,
		&i.Tanggal,
		&i.Jam,
		&i.Status,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPembinaan = `-- name: GetPembinaan :one
SELECT id, tanggal, bulan, pekan_ke, topik, keterangan, status, created_at, updated_at FROM pembinaan WHERE id = ?
`

func (q *Queries) GetPembinaan(ctx context.Context, id int64) (Pembinaan, error) {
	row := q.db.QueryRowContext(ctx, getPembinaan, id)
	var i Pembinaan
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.Bulan,
		&i.PekanKe,
		&i.Topik,
		&i.Keterangan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRapat = `-- name: GetRapat :one
SELECT id, tanggal, judul, catatan, status, created_at, updated_at FROM rapat_guru WHERE id = ?
`

func (q *Queries) GetRapat(ctx context.Context, id int64) (RapatGuru, error) {
	row := q.db.QueryRowContext(ctx, getRapat, id)
	var i RapatGuru
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.Judul,
		&i.Catatan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWaTemplate = `-- name: GetWaTemplate :one
SELECT id, nama, target_type, body, is_aktif, created_at, updated_at FROM wa_template WHERE id = ?
`

func (q *Queries) GetWaTemplate(ctx context.Context, id int64) (WaTemplate, error) {
	row := q.db.QueryRowContext(ctx, getWaTemplate, id)
	var i WaTemplate
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.TargetType,
		&i.Body,
		&i.IsAktif,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuruAktifSimple = `-- name: ListGuruAktifSimple :many

SELECT id, nama, status, no_wa FROM guru WHERE is_aktif = 1 ORDER BY nama ASC
`

type ListGuruAktifSimpleRow struct {
	ID     int64
	Nama   string
	Status string
	NoWa   string
}

// ============ Guru (helpers) ============
func (q *Queries) ListGuruAktifSimple(ctx context.Context) ([]ListGuruAktifSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuruAktifSimple)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuruAktifSimpleRow
	for rows.Next() {
		var i ListGuruAktifSimpleRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Status,
			&i.NoWa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruBelumAbsenPekanIni = `-- name: ListGuruBelumAbsenPekanIni :many
SELECT DISTINCT g.id, g.nama, g.no_wa
FROM guru g
JOIN kelas k ON k.guru_id = g.id AND k.is_aktif = 1
WHERE g.is_aktif = 1
  AND NOT EXISTS (
    SELECT 1 FROM pertemuan p WHERE p.kelas_id = k.id AND p.tanggal >= date('now', '-7 days')
  )
ORDER BY g.nama ASC
`

type ListGuruBelumAbsenPekanIniRow struct {
	ID   int64
	Nama string
	NoWa string
}

func (q *Queries) ListGuruBelumAbsenPekanIni(ctx context.Context) ([]ListGuruBelumAbsenPekanIniRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuruBelumAbsenPekanIni)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuruBelumAbsenPekanIniRow
	for rows.Next() {
		var i ListGuruBelumAbsenPekanIniRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.NoWa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruWithKalamShare = `-- name: ListGuruWithKalamShare :many
SELECT g.id AS guru_id, g.nama,
    CASE WHEN ksl.id IS NULL THEN 0 ELSE 1 END AS sudah_share
FROM guru g
LEFT JOIN kalam_share_log ksl ON ksl.guru_id = g.id AND ksl.kalam_id = ?
WHERE g.is_aktif = 1
ORDER BY g.nama ASC
`

type ListGuruWithKalamShareRow struct {
	GuruID     int64
	Nama       string
	SudahShare int64
}

func (q *Queries) ListGuruWithKalamShare(ctx context.Context, kalamID int64) ([]ListGuruWithKalamShareRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuruWithKalamShare, kalamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuruWithKalamShareRow
	for rows.Next() {
		var i ListGuruWithKalamShareRow
		if err := rows.Scan(&i.GuruID, &i.Nama, &i.SudahShare); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruWithPembinaanAbsen = `-- name: ListGuruWithPembinaanAbsen :many
SELECT g.id AS guru_id, g.nama, g.status,
    COALESCE(pa.hadir, 0) AS hadir, COALESCE(pa.jam_masuk, '') AS jam_masuk,
    COALESCE(pa.keterangan, '') AS keterangan, COALESCE(pa.alasan, '') AS alasan
FROM guru g
LEFT JOIN pembinaan_absen pa ON pa.guru_id = g.id AND pa.pembinaan_id = ?
WHERE g.is_aktif = 1
ORDER BY g.nama ASC
`

type ListGuruWithPembinaanAbsenRow struct {
	GuruID     int64
	Nama       string
	Status     string
	Hadir      int64
	JamMasuk   string
	Keterangan string
	Alasan     string
}

func (q *Queries) ListGuruWithPembinaanAbsen(ctx context.Context, pembinaanID int64) ([]ListGuruWithPembinaanAbsenRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuruWithPembinaanAbsen, pembinaanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuruWithPembinaanAbsenRow
	for rows.Next() {
		var i ListGuruWithPembinaanAbsenRow
		if err := rows.Scan(
			&i.GuruID,
			&i.Nama,
			&i.Status,
			&i.Hadir,
			&i.JamMasuk,
			&i.Keterangan,
			&i.Alasan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruWithRapatAbsen = `-- name: ListGuruWithRapatAbsen :many
SELECT g.id AS guru_id, g.nama, g.status,
    COALESCE(ra.hadir, 0) AS hadir, COALESCE(ra.jam_masuk, '') AS jam_masuk,
    COALESCE(ra.keterangan, '') AS keterangan, COALESCE(ra.alasan, '') AS alasan
FROM guru g
LEFT JOIN rapat_absen ra ON ra.guru_id = g.id AND ra.rapat_id = ?
WHERE g.is_aktif = 1
ORDER BY g.nama ASC
`

type ListGuruWithRapatAbsenRow struct {
	GuruID     int64
	Nama       string
	Status     string
	Hadir      int64
	JamMasuk   string
	Keterangan string
	Alasan     string
}

func (q *Queries) ListGuruWithRapatAbsen(ctx context.Context, rapatID int64) ([]ListGuruWithRapatAbsenRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuruWithRapatAbsen, rapatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuruWithRapatAbsenRow
	for rows.Next() {
		var i ListGuruWithRapatAbsenRow
		if err := rows.Scan(
			&i.GuruID,
			&i.Nama,
			&i.Status,
			&i.Hadir,
			&i.JamMasuk,
			&i.Keterangan,
			&i.Alasan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKalam = `-- name: ListKalam :many
SELECT kb.id, kb.tanggal, kb.topik, kb.kitab, kb.keterangan, kb.created_at, kb.updated_at, (SELECT COUNT(*) FROM kalam_share_log ksl WHERE ksl.kalam_id = kb.id) AS total_share
FROM kalam_bersanad kb ORDER BY kb.tanggal DESC
`

type ListKalamRow struct {
	ID         int64
	Tanggal    time.Time
	Topik      string
	Kitab      string
	Keterangan string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	TotalShare int64
}

func (q *Queries) ListKalam(ctx context.Context) ([]ListKalamRow, error) {
	rows, err := q.db.QueryContext(ctx, listKalam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKalamRow
	for rows.Next() {
		var i ListKalamRow
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.Topik,
			&i.Kitab,
			&i.Keterangan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalShare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKelasAktifSimple = `-- name: ListKelasAktifSimple :many
SELECT id, nama_kelas FROM kelas WHERE is_aktif = 1 ORDER BY nama_kelas ASC
`

type ListKelasAktifSimpleRow struct {
	ID        int64
	NamaKelas string
}

func (q *Queries) ListKelasAktifSimple(ctx context.Context) ([]ListKelasAktifSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, listKelasAktifSimple)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKelasAktifSimpleRow
	for rows.Next() {
		var i ListKelasAktifSimpleRow
		if err := rows.Scan(&i.ID, &i.NamaKelas); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKunjungan = `-- name: ListKunjungan :many
SELECT kk.id, kk.guru_id, kk.kelas_id, kk.target_mulai, kk.target_selesai, kk.tanggal, kk.jam, kk.status, kk.catatan, kk.created_at, kk.updated_at, g.nama AS guru_nama, COALESCE(k.nama_kelas, '') AS kelas_nama
FROM kunjungan_kelas kk
JOIN guru g ON g.id = kk.guru_id
LEFT JOIN kelas k ON k.id = kk.kelas_id
ORDER BY COALESCE(kk.tanggal, kk.target_mulai) DESC
`

type ListKunjunganRow struct {
	ID            int64
	GuruID        int64
	KelasID       sql.NullInt64
	TargetMulai   sql.NullTime
	TargetSelesai sql.NullTime
	Tanggal       sql.NullTime
	Jam           string
	Status        string
	Catatan       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	GuruNama      string
	KelasNama     string
}

func (q *Queries) ListKunjungan(ctx context.Context) ([]ListKunjunganRow, error) {
	rows, err := q.db.QueryContext(ctx, listKunjungan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKunjunganRow
	for rows.Next() {
		var i ListKunjunganRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.KelasID,
			&i.TargetMulai,
			&i.TargetSelesai,
			&i.Tanggal,
			&i.Jam,
			&i.Status,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuruNama,
			&i.KelasNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPembinaan = `-- name: ListPembinaan :many
SELECT id, tanggal, bulan, pekan_ke, topik, keterangan, status, created_at, updated_at FROM pembinaan ORDER BY tanggal DESC
`

func (q *Queries) ListPembinaan(ctx context.Context) ([]Pembinaan, error) {
	rows, err := q.db.QueryContext(ctx, listPembinaan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pembinaan
	for rows.Next() {
		var i Pembinaan
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.Bulan,
			&i.PekanKe,
			&i.Topik,
			&i.Keterangan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRapat = `-- name: ListRapat :many
SELECT id, tanggal, judul, catatan, status, created_at, updated_at FROM rapat_guru ORDER BY tanggal DESC
`

func (q *Queries) ListRapat(ctx context.Context) ([]RapatGuru, error) {
	rows, err := q.db.QueryContext(ctx, listRapat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RapatGuru
	for rows.Next() {
		var i RapatGuru
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.Judul,
			&i.Catatan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiwayatAbsensiGuru = `-- name: ListRiwayatAbsensiGuru :many
SELECT pa.guru_id, g.nama AS guru_nama, 'pembinaan' AS kegiatan, p.id AS kegiatan_id,
       p.tanggal, p.topik AS judul, pa.hadir, pa.jam_masuk, pa.keterangan, pa.alasan
FROM pembinaan_absen pa
JOIN pembinaan p ON p.id = pa.pembinaan_id
JOIN guru g ON g.id = pa.guru_id
UNION ALL
SELECT ra.guru_id, g.nama AS guru_nama, 'rapat' AS kegiatan, r.id AS kegiatan_id,
       r.tanggal, r.judul, ra.hadir, ra.jam_masuk, ra.keterangan, ra.alasan
FROM rapat_absen ra
JOIN rapat_guru r ON r.id = ra.rapat_id
JOIN guru g ON g.id = ra.guru_id
UNION ALL
SELECT k.guru_id, g.nama AS guru_nama, 'kunjungan' AS kegiatan, k.id AS kegiatan_id,
       k.tanggal, COALESCE(kl.nama_kelas, '') AS judul,
       CASE WHEN k.status = 'terlaksana' THEN 1 ELSE 0 END AS hadir,
       k.jam AS jam_masuk, k.catatan AS keterangan,
       CASE WHEN k.status = 'terlaksana' THEN '' ELSE k.status END AS alasan
FROM kunjungan_kelas k
JOIN guru g ON g.id = k.guru_id
LEFT JOIN kelas kl ON kl.id = k.kelas_id
WHERE k.tanggal IS NOT NULL
ORDER BY tanggal DESC, guru_nama ASC
`

type ListRiwayatAbsensiGuruRow struct {
	GuruID     int64
	GuruNama   string
	Kegiatan   string
	KegiatanID int64
	Tanggal    time.Time
	Judul      string
	Hadir      int64
	JamMasuk   string
	Keterangan string
	Alasan     string
}

func (q *Queries) ListRiwayatAbsensiGuru(ctx context.Context) ([]ListRiwayatAbsensiGuruRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiwayatAbsensiGuru)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatAbsensiGuruRow
	for rows.Next() {
		var i ListRiwayatAbsensiGuruRow
		if err := rows.Scan(
			&i.GuruID,
			&i.GuruNama,
			&i.Kegiatan,
			&i.KegiatanID,
			&i.Tanggal,
			&i.Judul,
			&i.Hadir,
			&i.JamMasuk,
			&i.Keterangan,
			&i.Alasan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTilawahByGuruRange = `-- name: ListTilawahByGuruRange :many
SELECT tanggal FROM tilawah_harian WHERE guru_id = ? AND tanggal >= ? AND tanggal <= ? ORDER BY tanggal ASC
`

type ListTilawahByGuruRangeParams struct {
	GuruID    int64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) ListTilawahByGuruRange(ctx context.Context, arg ListTilawahByGuruRangeParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, listTilawahByGuruRange, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var tanggal time.Time
		if err := rows.Scan(&tanggal); err != nil {
			return nil, err
		}
		items = append(items, tanggal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaTemplate = `-- name: ListWaTemplate :many
SELECT id, nama, target_type, body, is_aktif, created_at, updated_at FROM wa_template ORDER BY target_type, nama ASC
`

func (q *Queries) ListWaTemplate(ctx context.Context) ([]WaTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listWaTemplate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaTemplate
	for rows.Next() {
		var i WaTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.TargetType,
			&i.Body,
			&i.IsAktif,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleKalamShareOff = `-- name: ToggleKalamShareOff :exec
DELETE FROM kalam_share_log WHERE kalam_id = ? AND guru_id = ?
`

type ToggleKalamShareOffParams struct {
	KalamID int64
	GuruID  int64
}

func (q *Queries) ToggleKalamShareOff(ctx context.Context, arg ToggleKalamShareOffParams) error {
	_, err := q.db.ExecContext(ctx, toggleKalamShareOff, arg.KalamID, arg.GuruID)
	return err
}

const toggleKalamShareOn = `-- name: ToggleKalamShareOn :exec
INSERT INTO kalam_share_log (kalam_id, guru_id) VALUES (?, ?) ON CONFLICT(kalam_id, guru_id) DO NOTHING
`

type ToggleKalamShareOnParams struct {
	KalamID int64
	GuruID  int64
}

func (q *Queries) ToggleKalamShareOn(ctx context.Context, arg ToggleKalamShareOnParams) error {
	_, err := q.db.ExecContext(ctx, toggleKalamShareOn, arg.KalamID, arg.GuruID)
	return err
}

const updateKalam = `-- name: UpdateKalam :exec
UPDATE kalam_bersanad SET tanggal = ?, topik = ?, kitab = ?, keterangan = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateKalamParams struct {
	Tanggal    time.Time
	Topik      string
	Kitab      string
	Keterangan string
	ID         int64
}

func (q *Queries) UpdateKalam(ctx context.Context, arg UpdateKalamParams) error {
	_, err := q.db.ExecContext(ctx, updateKalam,
		arg.Tanggal,
		arg.Topik,
		arg.Kitab,
		arg.Keterangan,
		arg.ID,
	)
	return err
}

const updateKunjungan = `-- name: UpdateKunjungan :exec
UPDATE kunjungan_kelas SET guru_id = ?, kelas_id = ?, target_mulai = ?, target_selesai = ?, tanggal = ?, jam = ?, status = ?, catatan = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateKunjunganParams struct {
	GuruID        int64
	KelasID       sql.NullInt64
	TargetMulai   sql.NullTime
	TargetSelesai sql.NullTime
	Tanggal       sql.NullTime
	Jam           string
	Status        string
	Catatan       string
	ID            int64
}

func (q *Queries) UpdateKunjungan(ctx context.Context, arg UpdateKunjunganParams) error {
	_, err := q.db.ExecContext(ctx, updateKunjungan,
		arg.GuruID,
		arg.KelasID,
		arg.TargetMulai,
		arg.TargetSelesai,
		arg.Tanggal,
		arg.Jam,
		arg.Status,
		arg.Catatan,
		arg.ID,
	)
	return err
}

const updatePembinaan = `-- name: UpdatePembinaan :exec
UPDATE pembinaan SET tanggal = ?, bulan = ?, pekan_ke = ?, topik = ?, keterangan = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePembinaanParams struct {
	Tanggal    time.Time
	Bulan      string
	PekanKe    int64
	Topik      string
	Keterangan string
	Status     string
	ID         int64
}

func (q *Queries) UpdatePembinaan(ctx context.Context, arg UpdatePembinaanParams) error {
	_, err := q.db.ExecContext(ctx, updatePembinaan,
		arg.Tanggal,
		arg.Bulan,
		arg.PekanKe,
		arg.Topik,
		arg.Keterangan,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateRapat = `-- name: UpdateRapat :exec
UPDATE rapat_guru SET tanggal = ?, judul = ?, catatan = ?, status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRapatParams struct {
	Tanggal time.Time
	Judul   string
	Catatan string
	Status  string
	ID      int64
}

func (q *Queries) UpdateRapat(ctx context.Context, arg UpdateRapatParams) error {
	_, err := q.db.ExecContext(ctx, updateRapat,
		arg.Tanggal,
		arg.Judul,
		arg.Catatan,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateWaTemplate = `-- name: UpdateWaTemplate :exec
UPDATE wa_template SET nama = ?, target_type = ?, body = ?, is_aktif = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateWaTemplateParams struct {
	Nama       string
	TargetType string
	Body       string
	IsAktif    int64
	ID         int64
}

func (q *Queries) UpdateWaTemplate(ctx context.Context, arg UpdateWaTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateWaTemplate,
		arg.Nama,
		arg.TargetType,
		arg.Body,
		arg.IsAktif,
		arg.ID,
	)
	return err
}

const upsertGuruKompetensi = `-- name: UpsertGuruKompetensi :exec
INSERT INTO guru_kompetensi (
    guru_id, hafalan_quran, hafalan_tuhfah, hafalan_jazariy, hafalan_khaqaniy,
    hafalan_syakhawiy, sanad_qiroah, bahasa_arab_pasif, bahasa_arab_aktif, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(guru_id) DO UPDATE SET
    hafalan_quran = excluded.hafalan_quran,
    hafalan_tuhfah = excluded.hafalan_tuhfah,
    hafalan_jazariy = excluded.hafalan_jazariy,
    hafalan_khaqaniy = excluded.hafalan_khaqaniy,
    hafalan_syakhawiy = excluded.hafalan_syakhawiy,
    sanad_qiroah = excluded.sanad_qiroah,
    bahasa_arab_pasif = excluded.bahasa_arab_pasif,
    bahasa_arab_aktif = excluded.bahasa_arab_aktif,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertGuruKompetensiParams struct {
	GuruID           int64
	HafalanQuran     int64
	HafalanTuhfah    int64
	HafalanJazariy   int64
	HafalanKhaqaniy  int64
	HafalanSyakhawiy int64
	SanadQiroah      int64
	BahasaArabPasif  int64
	BahasaArabAktif  int64
}

func (q *Queries) UpsertGuruKompetensi(ctx context.Context, arg UpsertGuruKompetensiParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuruKompetensi,
		arg.GuruID,
		arg.HafalanQuran,
		arg.HafalanTuhfah,
		arg.HafalanJazariy,
		arg.HafalanKhaqaniy,
		arg.HafalanSyakhawiy,
		arg.SanadQiroah,
		arg.BahasaArabPasif,
		arg.BahasaArabAktif,
	)
	return err
}

const upsertPembinaanAbsen = `-- name: UpsertPembinaanAbsen :exec
INSERT INTO pembinaan_absen (pembinaan_id, guru_id, hadir, jam_masuk, keterangan, alasan, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(pembinaan_id, guru_id) DO UPDATE SET hadir = excluded.hadir, jam_masuk = excluded.jam_masuk, keterangan = excluded.keterangan, alasan = excluded.alasan, updated_at = CURRENT_TIMESTAMP
`

type UpsertPembinaanAbsenParams struct {
	PembinaanID int64
	GuruID      int64
	Hadir       int64
	JamMasuk    string
	Keterangan  string
	Alasan      string
}

func (q *Queries) UpsertPembinaanAbsen(ctx context.Context, arg UpsertPembinaanAbsenParams) error {
	_, err := q.db.ExecContext(ctx, upsertPembinaanAbsen,
		arg.PembinaanID,
		arg.GuruID,
		arg.Hadir,
		arg.JamMasuk,
		arg.Keterangan,
		arg.Alasan,
	)
	return err
}

const upsertRapatAbsen = `-- name: UpsertRapatAbsen :exec
INSERT INTO rapat_absen (rapat_id, guru_id, hadir, jam_masuk, keterangan, alasan, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(rapat_id, guru_id) DO UPDATE SET hadir = excluded.hadir, jam_masuk = excluded.jam_masuk, keterangan = excluded.keterangan, alasan = excluded.alasan, updated_at = CURRENT_TIMESTAMP
`

type UpsertRapatAbsenParams struct {
	RapatID    int64
	GuruID     int64
	Hadir      int64
	JamMasuk   string
	Keterangan string
	Alasan     string
}

func (q *Queries) UpsertRapatAbsen(ctx context.Context, arg UpsertRapatAbsenParams) error {
	_, err := q.db.ExecContext(ctx, upsertRapatAbsen,
		arg.RapatID,
		arg.GuruID,
		arg.Hadir,
		arg.JamMasuk,
		arg.Keterangan,
		arg.Alasan,
	)
	return err
}
