// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kunjungan.sql

package queries

import (
	"context"
	"database/sql"
)

const bukaKunciKunjungan = `-- name: BukaKunciKunjungan :exec
UPDATE kunjungan_kelas
SET dikirim_at = NULL, dikirim_oleh = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) BukaKunciKunjungan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, bukaKunciKunjungan, id)
	return err
}

const createKunjungan = `-- name: CreateKunjungan :one

INSERT INTO kunjungan_kelas (
    guru_id, kelas_id, target_mulai, target_selesai, tanggal, jam, status, catatan,
    nilai_kedisiplinan, nilai_materi, nilai_metode, nilai_interaksi
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateKunjunganParams struct {
	GuruID            int64
	KelasID           sql.NullInt64
	TargetMulai       sql.NullTime
	TargetSelesai     sql.NullTime
	Tanggal           sql.NullTime
	Jam               string
	Status            string
	Catatan           string
	NilaiKedisiplinan sql.NullInt64
	NilaiMateri       sql.NullInt64
	NilaiMetode       sql.NullInt64
	NilaiInteraksi    sql.NullInt64
}

// ============ Kunjungan Kelas ============
func (q *Queries) CreateKunjungan(ctx context.Context, arg CreateKunjunganParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createKunjungan,
		arg.GuruID,
		arg.KelasID,
		arg.TargetMulai,
		arg.TargetSelesai,
		arg.Tanggal,
		arg.Jam,
		arg.Status,
		arg.Catatan,
		arg.NilaiKedisiplinan,
		arg.NilaiMateri,
		arg.NilaiMetode,
		arg.NilaiInteraksi,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTindakLanjut = `-- name: CreateTindakLanjut :one

INSERT INTO kunjungan_tindak_lanjut (kunjungan_id, jenis, catatan, target_tanggal, dibuat_oleh)
VALUES (?, ?, ?, ?, ?) RETURNING id
`

type CreateTindakLanjutParams struct {
	KunjunganID   int64
	Jenis         string
	Catatan       string
	TargetTanggal sql.NullTime
	DibuatOleh    sql.NullInt64
}

// ============ Tindak Lanjut ============
func (q *Queries) CreateTindakLanjut(ctx context.Context, arg CreateTindakLanjutParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTindakLanjut,
		arg.KunjunganID,
		arg.Jenis,
		arg.Catatan,
		arg.TargetTanggal,
		arg.DibuatOleh,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteKunjungan = `-- name: DeleteKunjungan :execrows
DELETE FROM kunjungan_kelas WHERE id = ? AND dikirim_at IS NULL
`

func (q *Queries) DeleteKunjungan(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKunjungan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTindakLanjut = `-- name: DeleteTindakLanjut :exec
DELETE FROM kunjungan_tindak_lanjut WHERE id = ?
`

func (q *Queries) DeleteTindakLanjut(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTindakLanjut, id)
	return err
}

const getKelasPengampu = `-- name: GetKelasPengampu :one
SELECT guru_id, is_aktif FROM kelas WHERE id = ?
`

type GetKelasPengampuRow struct {
	GuruID  sql.NullInt64
	IsAktif int64
}

func (q *Queries) GetKelasPengampu(ctx context.Context, id int64) (GetKelasPengampuRow, error) {
	row := q.db.QueryRowContext(ctx, getKelasPengampu, id)
	var i GetKelasPengampuRow
	err := row.Scan(&i.GuruID, &i.IsAktif)
	return i, err
}

const getKunjungan = `-- name: GetKunjungan :one
SELECT kk.id, kk.guru_id, kk.kelas_id, kk.target_mulai, kk.target_selesai, kk.tanggal, kk.jam,
       kk.status, kk.catatan, kk.nilai_kedisiplinan, kk.nilai_materi, kk.nilai_metode,
       kk.nilai_interaksi, kk.dikirim_at, kk.dibaca_at, kk.tanggapan_guru, kk.tanggapan_at,
       g.nama AS guru_nama, g.no_wa AS guru_no_wa, g.user_id AS guru_user_id,
       COALESCE(k.nama_kelas, '') AS kelas_nama
FROM kunjungan_kelas kk
JOIN guru g ON g.id = kk.guru_id
LEFT JOIN kelas k ON k.id = kk.kelas_id
WHERE kk.id = ?
`

type GetKunjunganRow struct {
	ID                int64
	GuruID            int64
	KelasID           sql.NullInt64
	TargetMulai       sql.NullTime
	TargetSelesai     sql.NullTime
	Tanggal           sql.NullTime
	Jam               string
	Status            string
	Catatan           string
	NilaiKedisiplinan sql.NullInt64
	NilaiMateri       sql.NullInt64
	NilaiMetode       sql.NullInt64
	NilaiInteraksi    sql.NullInt64
	DikirimAt         sql.NullTime
	DibacaAt          sql.NullTime
	TanggapanGuru     string
	TanggapanAt       sql.NullTime
	GuruNama          string
	GuruNoWa          string
	GuruUserID        sql.NullInt64
	KelasNama         string
}

func (q *Queries) GetKunjungan(ctx context.Context, id int64) (GetKunjunganRow, error) {
	row := q.db.QueryRowContext(ctx, getKunjungan, id)
	var i GetKunjunganRow
	err := row.Scan(
		&i.ID,
		&i.GuruID,
		&i.KelasID,
		&i.TargetMulai,
		&i.TargetSelesai,
		&i.Tanggal,
		&i.Jam,
		&i.Status,
		&i.Catatan,
		&i.NilaiKedisiplinan,
		&i.NilaiMateri,
		&i.NilaiMetode,
		&i.NilaiInteraksi,
		&i.DikirimAt,
		&i.DibacaAt,
		&i.TanggapanGuru,
		&i.TanggapanAt,
		&i.GuruNama,
		&i.GuruNoWa,
		&i.GuruUserID,
		&i.KelasNama,
	)
	return i, err
}

const getTindakLanjut = `-- name: GetTindakLanjut :one
SELECT id, kunjungan_id, jenis, catatan, target_tanggal, status, selesai_at,
       kunjungan_berikutnya_id, dibuat_oleh, created_at, updated_at
FROM kunjungan_tindak_lanjut WHERE id = ?
`

func (q *Queries) GetTindakLanjut(ctx context.Context, id int64) (KunjunganTindakLanjut, error) {
	row := q.db.QueryRowContext(ctx, getTindakLanjut, id)
	var i KunjunganTindakLanjut
	err := row.Scan(
		&i.ID,
		&i.KunjunganID,
		&i.Jenis,
		&i.Catatan,
		&i.TargetTanggal,
		&i.Status,
		&i.SelesaiAt,
		&i.KunjunganBerikutnyaID,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const kirimKunjungan = `-- name: KirimKunjungan :exec
UPDATE kunjungan_kelas
SET dikirim_at = ?, dikirim_oleh = ?, dibaca_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type KirimKunjunganParams struct {
	DikirimAt   sql.NullTime
	DikirimOleh sql.NullInt64
	ID          int64
}

func (q *Queries) KirimKunjungan(ctx context.Context, arg KirimKunjunganParams) error {
	_, err := q.db.ExecContext(ctx, kirimKunjungan, arg.DikirimAt, arg.DikirimOleh, arg.ID)
	return err
}

const listKunjungan = `-- name: ListKunjungan :many
SELECT kk.id, kk.guru_id, kk.kelas_id, kk.target_mulai, kk.target_selesai, kk.tanggal, kk.jam,
       kk.status, kk.catatan, kk.nilai_kedisiplinan, kk.nilai_materi, kk.nilai_metode,
       kk.nilai_interaksi, kk.dikirim_at, kk.dibaca_at, kk.tanggapan_guru, kk.tanggapan_at,
       g.nama AS guru_nama, g.no_wa AS guru_no_wa, g.user_id AS guru_user_id,
       COALESCE(k.nama_kelas, '') AS kelas_nama
FROM kunjungan_kelas kk
JOIN guru g ON g.id = kk.guru_id
LEFT JOIN kelas k ON k.id = kk.kelas_id
ORDER BY COALESCE(kk.tanggal, kk.target_mulai) DESC, kk.id DESC
`

type ListKunjunganRow struct {
	ID                int64
	GuruID            int64
	KelasID           sql.NullInt64
	TargetMulai       sql.NullTime
	TargetSelesai     sql.NullTime
	Tanggal           sql.NullTime
	Jam               string
	Status            string
	Catatan           string
	NilaiKedisiplinan sql.NullInt64
	NilaiMateri       sql.NullInt64
	NilaiMetode       sql.NullInt64
	NilaiInteraksi    sql.NullInt64
	DikirimAt         sql.NullTime
	DibacaAt          sql.NullTime
	TanggapanGuru     string
	TanggapanAt       sql.NullTime
	GuruNama          string
	GuruNoWa          string
	GuruUserID        sql.NullInt64
	KelasNama         string
}

func (q *Queries) ListKunjungan(ctx context.Context) ([]ListKunjunganRow, error) {
	rows, err := q.db.QueryContext(ctx, listKunjungan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKunjunganRow
	for rows.Next() {
		var i ListKunjunganRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.KelasID,
			&i.TargetMulai,
			&i.TargetSelesai,
			&i.Tanggal,
			&i.Jam,
			&i.Status,
			&i.Catatan,
			&i.NilaiKedisiplinan,
			&i.NilaiMateri,
			&i.NilaiMetode,
			&i.NilaiInteraksi,
			&i.DikirimAt,
			&i.DibacaAt,
			&i.TanggapanGuru,
			&i.TanggapanAt,
			&i.GuruNama,
			&i.GuruNoWa,
			&i.GuruUserID,
			&i.KelasNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKunjunganTerkirimByGuru = `-- name: ListKunjunganTerkirimByGuru :many
SELECT kk.id, kk.guru_id, kk.kelas_id, kk.target_mulai, kk.target_selesai, kk.tanggal, kk.jam,
       kk.status, kk.catatan, kk.nilai_kedisiplinan, kk.nilai_materi, kk.nilai_metode,
       kk.nilai_interaksi, kk.dikirim_at, kk.dibaca_at, kk.tanggapan_guru, kk.tanggapan_at,
       g.nama AS guru_nama, g.no_wa AS guru_no_wa, g.user_id AS guru_user_id,
       COALESCE(k.nama_kelas, '') AS kelas_nama
FROM kunjungan_kelas kk
JOIN guru g ON g.id = kk.guru_id
LEFT JOIN kelas k ON k.id = kk.kelas_id
WHERE kk.guru_id = ? AND kk.dikirim_at IS NOT NULL
ORDER BY kk.tanggal DESC, kk.id DESC
`

type ListKunjunganTerkirimByGuruRow struct {
	ID                int64
	GuruID            int64
	KelasID           sql.NullInt64
	TargetMulai       sql.NullTime
	TargetSelesai     sql.NullTime
	Tanggal           sql.NullTime
	Jam               string
	Status            string
	Catatan           string
	NilaiKedisiplinan sql.NullInt64
	NilaiMateri       sql.NullInt64
	NilaiMetode       sql.NullInt64
	NilaiInteraksi    sql.NullInt64
	DikirimAt         sql.NullTime
	DibacaAt          sql.NullTime
	TanggapanGuru     string
	TanggapanAt       sql.NullTime
	GuruNama          string
	GuruNoWa          string
	GuruUserID        sql.NullInt64
	KelasNama         string
}

func (q *Queries) ListKunjunganTerkirimByGuru(ctx context.Context, guruID int64) ([]ListKunjunganTerkirimByGuruRow, error) {
	rows, err := q.db.QueryContext(ctx, listKunjunganTerkirimByGuru, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKunjunganTerkirimByGuruRow
	for rows.Next() {
		var i ListKunjunganTerkirimByGuruRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.KelasID,
			&i.TargetMulai,
			&i.TargetSelesai,
			&i.Tanggal,
			&i.Jam,
			&i.Status,
			&i.Catatan,
			&i.NilaiKedisiplinan,
			&i.NilaiMateri,
			&i.NilaiMetode,
			&i.NilaiInteraksi,
			&i.DikirimAt,
			&i.DibacaAt,
			&i.TanggapanGuru,
			&i.TanggapanAt,
			&i.GuruNama,
			&i.GuruNoWa,
			&i.GuruUserID,
			&i.KelasNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTindakLanjut = `-- name: ListTindakLanjut :many
SELECT tl.id, tl.kunjungan_id, tl.jenis, tl.catatan, tl.target_tanggal, tl.status, tl.selesai_at,
       tl.kunjungan_berikutnya_id, kk.guru_id, g.nama AS guru_nama,
       COALESCE(k.nama_kelas, '') AS kelas_nama, kk.tanggal AS kunjungan_tanggal
FROM kunjungan_tindak_lanjut tl
JOIN kunjungan_kelas kk ON kk.id = tl.kunjungan_id
JOIN guru g ON g.id = kk.guru_id
LEFT JOIN kelas k ON k.id = kk.kelas_id
ORDER BY tl.status = 'selesai', tl.target_tanggal IS NULL, tl.target_tanggal, tl.id
`

type ListTindakLanjutRow struct {
	ID                    int64
	KunjunganID           int64
	Jenis                 string
	Catatan               string
	TargetTanggal         sql.NullTime
	Status                string
	SelesaiAt             sql.NullTime
	KunjunganBerikutnyaID sql.NullInt64
	GuruID                int64
	GuruNama              string
	KelasNama             string
	KunjunganTanggal      sql.NullTime
}

func (q *Queries) ListTindakLanjut(ctx context.Context) ([]ListTindakLanjutRow, error) {
	rows, err := q.db.QueryContext(ctx, listTindakLanjut)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTindakLanjutRow
	for rows.Next() {
		var i ListTindakLanjutRow
		if err := rows.Scan(
			&i.ID,
			&i.KunjunganID,
			&i.Jenis,
			&i.Catatan,
			&i.TargetTanggal,
			&i.Status,
			&i.SelesaiAt,
			&i.KunjunganBerikutnyaID,
			&i.GuruID,
			&i.GuruNama,
			&i.KelasNama,
			&i.KunjunganTanggal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTindakLanjutByKunjungan = `-- name: ListTindakLanjutByKunjungan :many
SELECT id, kunjungan_id, jenis, catatan, target_tanggal, status, selesai_at,
       kunjungan_berikutnya_id, dibuat_oleh, created_at, updated_at
FROM kunjungan_tindak_lanjut WHERE kunjungan_id = ?
ORDER BY id
`

func (q *Queries) ListTindakLanjutByKunjungan(ctx context.Context, kunjunganID int64) ([]KunjunganTindakLanjut, error) {
	rows, err := q.db.QueryContext(ctx, listTindakLanjutByKunjungan, kunjunganID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KunjunganTindakLanjut
	for rows.Next() {
		var i KunjunganTindakLanjut
		if err := rows.Scan(
			&i.ID,
			&i.KunjunganID,
			&i.Jenis,
			&i.Catatan,
			&i.TargetTanggal,
			&i.Status,
			&i.SelesaiAt,
			&i.KunjunganBerikutnyaID,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selesaikanMonitoringOlehKunjungan = `-- name: SelesaikanMonitoringOlehKunjungan :exec
UPDATE kunjungan_tindak_lanjut
SET status = 'selesai', selesai_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE kunjungan_berikutnya_id = ? AND status = 'terbuka'
`

type SelesaikanMonitoringOlehKunjunganParams struct {
	SelesaiAt             sql.NullTime
	KunjunganBerikutnyaID sql.NullInt64
}

func (q *Queries) SelesaikanMonitoringOlehKunjungan(ctx context.Context, arg SelesaikanMonitoringOlehKunjunganParams) error {
	_, err := q.db.ExecContext(ctx, selesaikanMonitoringOlehKunjungan, arg.SelesaiAt, arg.KunjunganBerikutnyaID)
	return err
}

const setTindakLanjutKunjunganBerikutnya = `-- name: SetTindakLanjutKunjunganBerikutnya :exec
UPDATE kunjungan_tindak_lanjut
SET kunjungan_berikutnya_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetTindakLanjutKunjunganBerikutnyaParams struct {
	KunjunganBerikutnyaID sql.NullInt64
	ID                    int64
}

func (q *Queries) SetTindakLanjutKunjunganBerikutnya(ctx context.Context, arg SetTindakLanjutKunjunganBerikutnyaParams) error {
	_, err := q.db.ExecContext(ctx, setTindakLanjutKunjunganBerikutnya, arg.KunjunganBerikutnyaID, arg.ID)
	return err
}

const simpanTanggapanKunjungan = `-- name: SimpanTanggapanKunjungan :execrows
UPDATE kunjungan_kelas
SET tanggapan_guru = ?1, tanggapan_at = ?2,
    dibaca_at = COALESCE(dibaca_at, ?2), updated_at = CURRENT_TIMESTAMP
WHERE id = ?3 AND guru_id = ?4 AND dikirim_at IS NOT NULL
`

type SimpanTanggapanKunjunganParams struct {
	TanggapanGuru string
	Waktu         sql.NullTime
	ID            int64
	GuruID        int64
}

func (q *Queries) SimpanTanggapanKunjungan(ctx context.Context, arg SimpanTanggapanKunjunganParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, simpanTanggapanKunjungan,
		arg.TanggapanGuru,
		arg.Waktu,
		arg.ID,
		arg.GuruID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tandaiKunjunganDibaca = `-- name: TandaiKunjunganDibaca :exec
UPDATE kunjungan_kelas
SET dibaca_at = ?
WHERE id = ? AND guru_id = ? AND dikirim_at IS NOT NULL AND dibaca_at IS NULL
`

type TandaiKunjunganDibacaParams struct {
	DibacaAt sql.NullTime
	ID       int64
	GuruID   int64
}

func (q *Queries) TandaiKunjunganDibaca(ctx context.Context, arg TandaiKunjunganDibacaParams) error {
	_, err := q.db.ExecContext(ctx, tandaiKunjunganDibaca, arg.DibacaAt, arg.ID, arg.GuruID)
	return err
}

const updateKunjungan = `-- name: UpdateKunjungan :execrows
UPDATE kunjungan_kelas
SET guru_id = ?, kelas_id = ?, target_mulai = ?, target_selesai = ?, tanggal = ?, jam = ?,
    status = ?, catatan = ?, nilai_kedisiplinan = ?, nilai_materi = ?, nilai_metode = ?,
    nilai_interaksi = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND dikirim_at IS NULL
`

type UpdateKunjunganParams struct {
	GuruID            int64
	KelasID           sql.NullInt64
	TargetMulai       sql.NullTime
	TargetSelesai     sql.NullTime
	Tanggal           sql.NullTime
	Jam               string
	Status            string
	Catatan           string
	NilaiKedisiplinan sql.NullInt64
	NilaiMateri       sql.NullInt64
	NilaiMetode       sql.NullInt64
	NilaiInteraksi    sql.NullInt64
	ID                int64
}

func (q *Queries) UpdateKunjungan(ctx context.Context, arg UpdateKunjunganParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateKunjungan,
		arg.GuruID,
		arg.KelasID,
		arg.TargetMulai,
		arg.TargetSelesai,
		arg.Tanggal,
		arg.Jam,
		arg.Status,
		arg.Catatan,
		arg.NilaiKedisiplinan,
		arg.NilaiMateri,
		arg.NilaiMetode,
		arg.NilaiInteraksi,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTindakLanjutStatus = `-- name: UpdateTindakLanjutStatus :exec
UPDATE kunjungan_tindak_lanjut
SET status = ?, selesai_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTindakLanjutStatusParams struct {
	Status    string
	SelesaiAt sql.NullTime
	ID        int64
}

func (q *Queries) UpdateTindakLanjutStatus(ctx context.Context, arg UpdateTindakLanjutStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTindakLanjutStatus, arg.Status, arg.SelesaiAt, arg.ID)
	return err
}
