// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master.sql

package queries

import (
	"context"
)

const createAngkatan = `-- name: CreateAngkatan :exec
INSERT INTO angkatan (kode, keterangan, is_aktif, created_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateAngkatanParams struct {
	Kode       string
	Keterangan string
	IsAktif    int64
}

func (q *Queries) CreateAngkatan(ctx context.Context, arg CreateAngkatanParams) error {
	_, err := q.db.ExecContext(ctx, createAngkatan, arg.Kode, arg.Keterangan, arg.IsAktif)
	return err
}

const createGuru = `-- name: CreateGuru :exec
INSERT INTO guru (nama, jenis_kelamin, is_aktif) VALUES (?, ?, ?)
`

type CreateGuruParams struct {
	Nama         string
	JenisKelamin string
	IsAktif      int64
}

func (q *Queries) CreateGuru(ctx context.Context, arg CreateGuruParams) error {
	_, err := q.db.ExecContext(ctx, createGuru, arg.Nama, arg.JenisKelamin, arg.IsAktif)
	return err
}

const createJadwal = `-- name: CreateJadwal :exec
INSERT INTO jadwal (nama) VALUES (?)
`

func (q *Queries) CreateJadwal(ctx context.Context, nama string) error {
	_, err := q.db.ExecContext(ctx, createJadwal, nama)
	return err
}

const createLevel = `-- name: CreateLevel :exec
INSERT INTO level (kode, nama, urutan) VALUES (?, ?, ?)
`

type CreateLevelParams struct {
	Kode   string
	Nama   string
	Urutan int64
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) error {
	_, err := q.db.ExecContext(ctx, createLevel, arg.Kode, arg.Nama, arg.Urutan)
	return err
}

const getAngkatanByKode = `-- name: GetAngkatanByKode :one
SELECT id, kode, keterangan, is_aktif, created_at FROM angkatan WHERE kode = ?
`

func (q *Queries) GetAngkatanByKode(ctx context.Context, kode string) (Angkatan, error) {
	row := q.db.QueryRowContext(ctx, getAngkatanByKode, kode)
	var i Angkatan
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Keterangan,
		&i.IsAktif,
		&i.CreatedAt,
	)
	return i, err
}

const getGuruByID = `-- name: GetGuruByID :one
SELECT id, nama, jenis_kelamin, is_aktif FROM guru WHERE id = ?
`

func (q *Queries) GetGuruByID(ctx context.Context, id int64) (Guru, error) {
	row := q.db.QueryRowContext(ctx, getGuruByID, id)
	var i Guru
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.JenisKelamin,
		&i.IsAktif,
	)
	return i, err
}

const getJadwalByNama = `-- name: GetJadwalByNama :one
SELECT id, nama FROM jadwal WHERE nama = ?
`

func (q *Queries) GetJadwalByNama(ctx context.Context, nama string) (Jadwal, error) {
	row := q.db.QueryRowContext(ctx, getJadwalByNama, nama)
	var i Jadwal
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}

const getLevelByKode = `-- name: GetLevelByKode :one
SELECT id, kode, nama, urutan FROM level WHERE kode = ?
`

func (q *Queries) GetLevelByKode(ctx context.Context, kode string) (Level, error) {
	row := q.db.QueryRowContext(ctx, getLevelByKode, kode)
	var i Level
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Nama,
		&i.Urutan,
	)
	return i, err
}

const listAngkatan = `-- name: ListAngkatan :many
SELECT id, kode, keterangan, is_aktif, created_at FROM angkatan ORDER BY kode DESC
`

func (q *Queries) ListAngkatan(ctx context.Context) ([]Angkatan, error) {
	rows, err := q.db.QueryContext(ctx, listAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Angkatan
	for rows.Next() {
		var i Angkatan
		if err := rows.Scan(
			&i.ID,
			&i.Kode,
			&i.Keterangan,
			&i.IsAktif,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuru = `-- name: ListGuru :many
SELECT id, nama, jenis_kelamin, is_aktif FROM guru WHERE is_aktif = 1 ORDER BY nama ASC
`

func (q *Queries) ListGuru(ctx context.Context) ([]Guru, error) {
	rows, err := q.db.QueryContext(ctx, listGuru)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guru
	for rows.Next() {
		var i Guru
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.JenisKelamin,
			&i.IsAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuruAll = `-- name: ListGuruAll :many
SELECT id, nama, jenis_kelamin, is_aktif FROM guru ORDER BY nama ASC
`

func (q *Queries) ListGuruAll(ctx context.Context) ([]Guru, error) {
	rows, err := q.db.QueryContext(ctx, listGuruAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guru
	for rows.Next() {
		var i Guru
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.JenisKelamin,
			&i.IsAktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwal = `-- name: ListJadwal :many
SELECT id, nama FROM jadwal ORDER BY nama ASC
`

func (q *Queries) ListJadwal(ctx context.Context) ([]Jadwal, error) {
	rows, err := q.db.QueryContext(ctx, listJadwal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jadwal
	for rows.Next() {
		var i Jadwal
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLevel = `-- name: ListLevel :many
SELECT id, kode, nama, urutan FROM level ORDER BY urutan ASC
`

func (q *Queries) ListLevel(ctx context.Context) ([]Level, error) {
	rows, err := q.db.QueryContext(ctx, listLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Level
	for rows.Next() {
		var i Level
		if err := rows.Scan(
			&i.ID,
			&i.Kode,
			&i.Nama,
			&i.Urutan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAngkatan = `-- name: UpdateAngkatan :exec
UPDATE angkatan SET keterangan = ?, is_aktif = ? WHERE id = ?
`

type UpdateAngkatanParams struct {
	Keterangan string
	IsAktif    int64
	ID         int64
}

func (q *Queries) UpdateAngkatan(ctx context.Context, arg UpdateAngkatanParams) error {
	_, err := q.db.ExecContext(ctx, updateAngkatan, arg.Keterangan, arg.IsAktif, arg.ID)
	return err
}

const updateGuru = `-- name: UpdateGuru :exec
UPDATE guru SET nama = ?, jenis_kelamin = ?, is_aktif = ? WHERE id = ?
`

type UpdateGuruParams struct {
	Nama         string
	JenisKelamin string
	IsAktif      int64
	ID           int64
}

func (q *Queries) UpdateGuru(ctx context.Context, arg UpdateGuruParams) error {
	_, err := q.db.ExecContext(ctx, updateGuru,
		arg.Nama,
		arg.JenisKelamin,
		arg.IsAktif,
		arg.ID,
	)
	return err
}

const updateLevel = `-- name: UpdateLevel :exec
UPDATE level SET nama = ?, urutan = ? WHERE id = ?
`

type UpdateLevelParams struct {
	Nama   string
	Urutan int64
	ID     int64
}

func (q *Queries) UpdateLevel(ctx context.Context, arg UpdateLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateLevel, arg.Nama, arg.Urutan, arg.ID)
	return err
}
