// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master_extend.sql

package queries

import (
	"context"
)

const deleteAngkatan = `-- name: DeleteAngkatan :exec
DELETE FROM angkatan WHERE id = ?
`

func (q *Queries) DeleteAngkatan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAngkatan, id)
	return err
}

const deleteGuru = `-- name: DeleteGuru :exec
DELETE FROM guru WHERE id = ?
`

func (q *Queries) DeleteGuru(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGuru, id)
	return err
}

const deleteJadwal = `-- name: DeleteJadwal :exec
DELETE FROM jadwal WHERE id = ?
`

func (q *Queries) DeleteJadwal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJadwal, id)
	return err
}

const deleteLevel = `-- name: DeleteLevel :exec
DELETE FROM level WHERE id = ?
`

func (q *Queries) DeleteLevel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLevel, id)
	return err
}

const updateJadwal = `-- name: UpdateJadwal :exec
UPDATE jadwal SET nama = ? WHERE id = ?
`

type UpdateJadwalParams struct {
	Nama string
	ID   int64
}

func (q *Queries) UpdateJadwal(ctx context.Context, arg UpdateJadwalParams) error {
	_, err := q.db.ExecContext(ctx, updateJadwal, arg.Nama, arg.ID)
	return err
}
