// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type Absensi struct {
	ID          int64
	PertemuanID int64
	SantriID    int64
	Status      string
	Catatan     string
	DibuatOleh  sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BatasMateri string
}

type Angkatan struct {
	ID         int64
	Kode       string
	Keterangan string
	IsAktif    int64
	CreatedAt  time.Time
}

type CatatanRiayah struct {
	ID           int64
	GuruID       sql.NullInt64
	AuthorUserID sql.NullInt64
	TargetType   string
	TargetID     int64
	Catatan      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ClassMonitoringNote struct {
	ID                int64
	JadwalPertemuanID int64
	Note              string
	CreatedBy         sql.NullInt64
	CreatedAt         time.Time
}

type Guru struct {
	ID            int64
	Nama          string
	JenisKelamin  string
	IsAktif       int64
	UserID        sql.NullInt64
	Status        string
	NoWa          string
	Email         string
	TanggalGabung sql.NullTime
	Foto          string
	Gelar         string
}

type GuruKompetensi struct {
	GuruID           int64
	HafalanQuran     int64
	HafalanTuhfah    int64
	HafalanJazariy   int64
	HafalanKhaqaniy  int64
	HafalanSyakhawiy int64
	SanadQiroah      int64
	BahasaArabPasif  int64
	BahasaArabAktif  int64
	UpdatedAt        time.Time
}

type ImportLog struct {
	ID         int64
	UserID     int64
	NamaFile   string
	TotalBaris int64
	Berhasil   int64
	Gagal      int64
	Catatan    string
	CreatedAt  time.Time
}

type Jadwal struct {
	ID   int64
	Nama string
}

type JadwalPertemuan struct {
	ID                 int64
	KelasID            int64
	Tanggal            time.Time
	JamMulai           string
	Catatan            string
	IsReschedule       int64
	JadwalSemula       string
	AlasanReschedule   string
	GuruPenggantiID    sql.NullInt64
	AlasanBadal        string
	Status             string
	PertemuanID        sql.NullInt64
	DibuatOleh         sql.NullInt64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	JadwalKelasBerubah int64
}

type KalamBersanad struct {
	ID         int64
	Tanggal    time.Time
	Topik      string
	Kitab      string
	Keterangan string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type KalamShareLog struct {
	ID        int64
	KalamID   int64
	GuruID    int64
	CreatedAt time.Time
}

type Kela struct {
	ID                 int64
	KunciKelas         string
	Angkatan           string
	Tipe               string
	JenisKelamin       string
	Level              string
	Frekuensi          string
	Jadwal             string
	SubIndex           int64
	NamaKelas          string
	GuruID             sql.NullInt64
	Kapasitas          int64
	JumlahSantri       int64
	CreatedAt          time.Time
	IsAktif            int64
	PertemuanTerakhir  int64
	MateriIndividual   int64
	LevelPertemuanAwal int64
}

type KelasPerubahan struct {
	ID            int64
	KelasID       sql.NullInt64
	SantriID      sql.NullInt64
	KelasTujuanID sql.NullInt64
	Jenis         string
	NilaiLama     string
	NilaiBaru     string
	PertemuanKe   int64
	DibuatOleh    sql.NullInt64
	CreatedAt     time.Time
}

type KodeKela struct {
	ID        int64
	Kode      string
	Tipe      string
	Frekuensi string
	Urutan    int64
}

type KunjunganKela struct {
	ID            int64
	GuruID        int64
	KelasID       sql.NullInt64
	TargetMulai   sql.NullTime
	TargetSelesai sql.NullTime
	Tanggal       sql.NullTime
	Jam           string
	Status        string
	Catatan       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Level struct {
	ID     int64
	Kode   string
	Nama   string
	Urutan int64
}

type Notification struct {
	ID            int64
	UserID        int64
	Type          string
	Title         string
	Message       string
	ActionUrl     string
	ReferenceType string
	ReferenceID   sql.NullInt64
	ReadAt        sql.NullTime
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
}

type PasswordReset struct {
	Token     string
	UserID    int64
	Email     string
	ExpiresAt time.Time
	Used      int64
	CreatedAt time.Time
}

type Pembinaan struct {
	ID         int64
	Tanggal    time.Time
	Bulan      string
	PekanKe    int64
	Topik      string
	Keterangan string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type PembinaanAbsen struct {
	ID          int64
	PembinaanID int64
	GuruID      int64
	Hadir       int64
	Alasan      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	JamMasuk    string
	Keterangan  string
}

type Pertemuan struct {
	ID               int64
	KelasID          int64
	PertemuanKe      int64
	Tanggal          time.Time
	JamMulai         string
	JamSelesai       string
	Materi           string
	Catatan          string
	IsReschedule     int64
	JadwalSemula     string
	AlasanReschedule string
	IsBadal          int64
	GuruPenggantiID  sql.NullInt64
	AlasanBadal      string
	Status           string
	DibuatOleh       sql.NullInt64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LevelNama        string
	PertemuanLevelKe int64
}

type RapatAbsen struct {
	ID         int64
	RapatID    int64
	GuruID     int64
	Hadir      int64
	Alasan     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	JamMasuk   string
	Keterangan string
}

type RapatGuru struct {
	ID        int64
	Tanggal   time.Time
	Judul     string
	Catatan   string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Santri struct {
	ID                    int64
	IDMahasantri          string
	KelasKode             string
	Nama                  string
	JenisKelamin          string
	Nominal               int64
	TanggalDaftar         sql.NullTime
	Angkatan              string
	Usia                  sql.NullInt64
	Domisili              string
	Fu                    string
	TanggalVn             sql.NullTime
	HasilVn               string
	MasukGrup             string
	MulaiBelajar          sql.NullTime
	Jumlah                sql.NullInt64
	Level                 string
	Jadwal                string
	Guru                  string
	JadwalCatatan         string
	InfaqTerakhir         string
	KeteranganTidakLanjut string
	Tipe                  string
	Frekuensi             string
	IsLengkap             int64
	KelasID               sql.NullInt64
	Status                string
	CreatedBy             sql.NullInt64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	NoWa                  string
	VoiceNoteUrl          string
	KeteranganVn          string
	Email                 string
	PertemuanAwal         int64
	AngkatanKelas         string
	StatusAlasan          string
	CutiMulai             string
	CutiSelesai           string
}

type SantriStatusLog struct {
	ID          int64
	SantriID    int64
	KelasID     sql.NullInt64
	StatusLama  string
	StatusBaru  string
	Alasan      string
	CutiMulai   string
	CutiSelesai string
	DibuatOleh  sql.NullInt64
	CreatedAt   time.Time
}

type ScheduleActivityLog struct {
	ID                int64
	JadwalPertemuanID int64
	Action            string
	Details           string
	CreatedBy         sql.NullInt64
	CreatedAt         time.Time
}

type Session struct {
	ID        string
	UserID    int64
	Data      string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tagihan struct {
	ID            int64
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	Status        string
	TanggalBayar  sql.NullTime
	Metode        string
	Catatan       string
	DicatatOleh   sql.NullInt64
	FuTerakhir    sql.NullTime
	FuCount       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AngkatanKelas string
}

type TilawahHarian struct {
	ID        int64
	GuruID    int64
	Tanggal   time.Time
	CreatedAt time.Time
}

type TodoKoordinator struct {
	ID            int64
	Judul         string
	Teknis        string
	Kebutuhan     string
	Deadline      sql.NullTime
	Pic           string
	Status        string
	Recurring     string
	LinkPendukung string
	Catatan       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TsiAudit struct {
	ID         int64
	PeriodeID  int64
	KriteriaID int64
	NilaiLama  sql.NullFloat64
	NilaiBaru  sql.NullFloat64
	Alasan     string
	Oleh       sql.NullInt64
	CreatedAt  time.Time
}

type TsiKriterium struct {
	ID       int64
	Kategori string
	Bobot    int64
	Urutan   int64
	Sumber   string
	Kode     string
	Nama     string
}

type TsiNilai struct {
	ID             int64
	PeriodeID      int64
	KriteriaID     int64
	Nilai          sql.NullFloat64
	IsOverride     int64
	AlasanOverride string
	Catatan        string
	UpdatedAt      time.Time
}

type TsiPeriode struct {
	ID        int64
	GuruID    int64
	Bulan     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            int64
	Email         string
	Name          string
	Password      sql.NullString
	Avatar        sql.NullString
	Role          string
	GoogleID      sql.NullString
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WaTemplate struct {
	ID         int64
	Nama       string
	TargetType string
	Body       string
	IsAktif    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
