// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pertemuan.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const claimPertemuanCompletion = `-- name: ClaimPertemuanCompletion :execrows
UPDATE pertemuan
SET status = 'menyelesaikan', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'berlangsung'
`

type ClaimPertemuanCompletionParams struct {
	ID      int64
	KelasID int64
}

func (q *Queries) ClaimPertemuanCompletion(ctx context.Context, arg ClaimPertemuanCompletionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimPertemuanCompletion, arg.ID, arg.KelasID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPertemuanBadal = `-- name: CountPertemuanBadal :one
SELECT COUNT(*) FROM pertemuan WHERE kelas_id = ? AND is_badal = 1
`

func (q *Queries) CountPertemuanBadal(ctx context.Context, kelasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPertemuanBadal, kelasID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPertemuanByGuruID = `-- name: CountPertemuanByGuruID :many
SELECT k.id AS kelas_id, k.nama_kelas, COUNT(p.id) AS total_pertemuan
FROM kelas k
LEFT JOIN pertemuan p ON p.kelas_id = k.id
WHERE k.guru_id = ?
GROUP BY k.id
ORDER BY k.nama_kelas
`

type CountPertemuanByGuruIDRow struct {
	KelasID        int64
	NamaKelas      string
	TotalPertemuan int64
}

func (q *Queries) CountPertemuanByGuruID(ctx context.Context, guruID sql.NullInt64) ([]CountPertemuanByGuruIDRow, error) {
	rows, err := q.db.QueryContext(ctx, countPertemuanByGuruID, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPertemuanByGuruIDRow
	for rows.Next() {
		var i CountPertemuanByGuruIDRow
		if err := rows.Scan(&i.KelasID, &i.NamaKelas, &i.TotalPertemuan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPertemuanByKelas = `-- name: CountPertemuanByKelas :one
SELECT COUNT(*) FROM pertemuan WHERE kelas_id = ?
`

func (q *Queries) CountPertemuanByKelas(ctx context.Context, kelasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPertemuanByKelas, kelasID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPertemuanReschedule = `-- name: CountPertemuanReschedule :one
SELECT COUNT(*) FROM pertemuan WHERE kelas_id = ? AND is_reschedule = 1
`

func (q *Queries) CountPertemuanReschedule(ctx context.Context, kelasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPertemuanReschedule, kelasID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPertemuan = `-- name: CreatePertemuan :execresult
INSERT INTO pertemuan (
    kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai,
    materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule,
    is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type CreatePertemuanParams struct {
	KelasID          int64
	PertemuanKe      int64
	Tanggal          time.Time
	JamMulai         string
	JamSelesai       string
	Materi           string
	Catatan          string
	IsReschedule     int64
	JadwalSemula     string
	AlasanReschedule string
	IsBadal          int64
	GuruPenggantiID  sql.NullInt64
	AlasanBadal      string
	Status           string
	DibuatOleh       sql.NullInt64
}

func (q *Queries) CreatePertemuan(ctx context.Context, arg CreatePertemuanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPertemuan,
		arg.KelasID,
		arg.PertemuanKe,
		arg.Tanggal,
		arg.JamMulai,
		arg.JamSelesai,
		arg.Materi,
		arg.Catatan,
		arg.IsReschedule,
		arg.JadwalSemula,
		arg.AlasanReschedule,
		arg.IsBadal,
		arg.GuruPenggantiID,
		arg.AlasanBadal,
		arg.Status,
		arg.DibuatOleh,
	)
}

const getActivePertemuanByKelas = `-- name: GetActivePertemuanByKelas :one
SELECT id, kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai, materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule, is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh, created_at, updated_at FROM pertemuan
WHERE kelas_id = ? AND status = 'berlangsung'
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetActivePertemuanByKelas(ctx context.Context, kelasID int64) (Pertemuan, error) {
	row := q.db.QueryRowContext(ctx, getActivePertemuanByKelas, kelasID)
	var i Pertemuan
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.PertemuanKe,
		&i.Tanggal,
		&i.JamMulai,
		&i.JamSelesai,
		&i.Materi,
		&i.Catatan,
		&i.IsReschedule,
		&i.JadwalSemula,
		&i.AlasanReschedule,
		&i.IsBadal,
		&i.GuruPenggantiID,
		&i.AlasanBadal,
		&i.Status,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastPertemuanByKelas = `-- name: GetLastPertemuanByKelas :one
SELECT id, kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai, materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule, is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh, created_at, updated_at FROM pertemuan
WHERE kelas_id = ? AND status = 'selesai'
ORDER BY pertemuan_ke DESC
LIMIT 1
`

func (q *Queries) GetLastPertemuanByKelas(ctx context.Context, kelasID int64) (Pertemuan, error) {
	row := q.db.QueryRowContext(ctx, getLastPertemuanByKelas, kelasID)
	var i Pertemuan
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.PertemuanKe,
		&i.Tanggal,
		&i.JamMulai,
		&i.JamSelesai,
		&i.Materi,
		&i.Catatan,
		&i.IsReschedule,
		&i.JadwalSemula,
		&i.AlasanReschedule,
		&i.IsBadal,
		&i.GuruPenggantiID,
		&i.AlasanBadal,
		&i.Status,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextPertemuanKe = `-- name: GetNextPertemuanKe :one
SELECT MAX(COALESCE((SELECT MAX(p.pertemuan_ke) FROM pertemuan p WHERE p.kelas_id = kelas.id), 0), kelas.pertemuan_terakhir) + 1 AS next_ke
FROM kelas
WHERE kelas.id = ?
`

func (q *Queries) GetNextPertemuanKe(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextPertemuanKe, id)
	var next_ke int64
	err := row.Scan(&next_ke)
	return next_ke, err
}

const getPertemuanByID = `-- name: GetPertemuanByID :one
SELECT id, kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai, materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule, is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh, created_at, updated_at FROM pertemuan WHERE id = ?
`

func (q *Queries) GetPertemuanByID(ctx context.Context, id int64) (Pertemuan, error) {
	row := q.db.QueryRowContext(ctx, getPertemuanByID, id)
	var i Pertemuan
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.PertemuanKe,
		&i.Tanggal,
		&i.JamMulai,
		&i.JamSelesai,
		&i.Materi,
		&i.Catatan,
		&i.IsReschedule,
		&i.JadwalSemula,
		&i.AlasanReschedule,
		&i.IsBadal,
		&i.GuruPenggantiID,
		&i.AlasanBadal,
		&i.Status,
		&i.DibuatOleh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRiwayatPertemuanByKelas = `-- name: ListRiwayatPertemuanByKelas :many
SELECT id, kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai, materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule, is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh, created_at, updated_at FROM pertemuan
WHERE kelas_id = ? AND status = 'selesai'
ORDER BY pertemuan_ke DESC
`

func (q *Queries) ListRiwayatPertemuanByKelas(ctx context.Context, kelasID int64) ([]Pertemuan, error) {
	rows, err := q.db.QueryContext(ctx, listRiwayatPertemuanByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pertemuan
	for rows.Next() {
		var i Pertemuan
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.PertemuanKe,
			&i.Tanggal,
			&i.JamMulai,
			&i.JamSelesai,
			&i.Materi,
			&i.Catatan,
			&i.IsReschedule,
			&i.JadwalSemula,
			&i.AlasanReschedule,
			&i.IsBadal,
			&i.GuruPenggantiID,
			&i.AlasanBadal,
			&i.Status,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePertemuanSelesai = `-- name: UpdatePertemuanSelesai :execrows
UPDATE pertemuan
SET jam_selesai = ?, materi = ?, catatan = ?, status = 'selesai', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND kelas_id = ? AND status = 'menyelesaikan'
`

type UpdatePertemuanSelesaiParams struct {
	JamSelesai string
	Materi     string
	Catatan    string
	ID         int64
	KelasID    int64
}

func (q *Queries) UpdatePertemuanSelesai(ctx context.Context, arg UpdatePertemuanSelesaiParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePertemuanSelesai,
		arg.JamSelesai,
		arg.Materi,
		arg.Catatan,
		arg.ID,
		arg.KelasID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePertemuanStatus = `-- name: UpdatePertemuanStatus :exec
UPDATE pertemuan SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdatePertemuanStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdatePertemuanStatus(ctx context.Context, arg UpdatePertemuanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePertemuanStatus, arg.Status, arg.ID)
	return err
}
