// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: riayah_santri.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createRiayahKontak = `-- name: CreateRiayahKontak :execresult
INSERT INTO riayah_kontak (santri_id, guru_id, author_user_id, tanggal, media, jenis, periode, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRiayahKontakParams struct {
	SantriID     int64
	GuruID       sql.NullInt64
	AuthorUserID sql.NullInt64
	Tanggal      string
	Media        string
	Jenis        string
	Periode      string
	Catatan      string
}

func (q *Queries) CreateRiayahKontak(ctx context.Context, arg CreateRiayahKontakParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRiayahKontak,
		arg.SantriID,
		arg.GuruID,
		arg.AuthorUserID,
		arg.Tanggal,
		arg.Media,
		arg.Jenis,
		arg.Periode,
		arg.Catatan,
	)
}

const deleteRiayahKontakByID = `-- name: DeleteRiayahKontakByID :exec
DELETE FROM riayah_kontak WHERE id = ?
`

func (q *Queries) DeleteRiayahKontakByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRiayahKontakByID, id)
	return err
}

const getRiayahKontakByID = `-- name: GetRiayahKontakByID :one
SELECT id, santri_id, guru_id, author_user_id, tanggal, media, jenis, periode, catatan, created_at FROM riayah_kontak WHERE id = ?
`

func (q *Queries) GetRiayahKontakByID(ctx context.Context, id int64) (RiayahKontak, error) {
	row := q.db.QueryRowContext(ctx, getRiayahKontakByID, id)
	var i RiayahKontak
	err := row.Scan(
		&i.ID,
		&i.SantriID,
		&i.GuruID,
		&i.AuthorUserID,
		&i.Tanggal,
		&i.Media,
		&i.Jenis,
		&i.Periode,
		&i.Catatan,
		&i.CreatedAt,
	)
	return i, err
}

const listAbsensiSantriPeriode = `-- name: ListAbsensiSantriPeriode :many
SELECT a.status, a.catatan, a.batas_materi,
    p.tanggal, p.pertemuan_level_ke, p.materi, k.nama_kelas
FROM absensi a
JOIN pertemuan p ON p.id = a.pertemuan_id
JOIN kelas k ON k.id = p.kelas_id
WHERE a.santri_id = ?1
  AND p.status = 'selesai'
  AND p.tanggal >= CAST(?2 AS TEXT)
  AND p.tanggal < CAST(?3 AS TEXT)
ORDER BY p.tanggal, p.id
`

type ListAbsensiSantriPeriodeParams struct {
	SantriID int64
	Mulai    string
	Selesai  string
}

type ListAbsensiSantriPeriodeRow struct {
	Status           string
	Catatan          string
	BatasMateri      string
	Tanggal          time.Time
	PertemuanLevelKe int64
	Materi           string
	NamaKelas        string
}

func (q *Queries) ListAbsensiSantriPeriode(ctx context.Context, arg ListAbsensiSantriPeriodeParams) ([]ListAbsensiSantriPeriodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAbsensiSantriPeriode, arg.SantriID, arg.Mulai, arg.Selesai)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAbsensiSantriPeriodeRow
	for rows.Next() {
		var i ListAbsensiSantriPeriodeRow
		if err := rows.Scan(
			&i.Status,
			&i.Catatan,
			&i.BatasMateri,
			&i.Tanggal,
			&i.PertemuanLevelKe,
			&i.Materi,
			&i.NamaKelas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbsensiTerakhirRiayah = `-- name: ListAbsensiTerakhirRiayah :many
SELECT santri_id, status, batas_materi, tanggal, urutan
FROM (
    SELECT a.santri_id, a.status, a.batas_materi, p.tanggal,
        ROW_NUMBER() OVER (PARTITION BY a.santri_id ORDER BY p.tanggal DESC, p.id DESC) AS urutan
    FROM absensi a
    JOIN pertemuan p ON p.id = a.pertemuan_id
    JOIN santri s ON s.id = a.santri_id
    JOIN kelas k ON k.id = s.kelas_id
    WHERE p.status = 'selesai'
      AND s.status = 'aktif'
      AND (?1 IS NULL OR k.guru_id = ?1)
)
WHERE urutan <= 12
ORDER BY santri_id, urutan
`

type ListAbsensiTerakhirRiayahRow struct {
	SantriID    int64
	Status      string
	BatasMateri string
	Tanggal     time.Time
	Urutan      interface{}
}

// 12 absensi terakhir per santri dalam scope, terbaru dulu.
func (q *Queries) ListAbsensiTerakhirRiayah(ctx context.Context, guruID interface{}) ([]ListAbsensiTerakhirRiayahRow, error) {
	rows, err := q.db.QueryContext(ctx, listAbsensiTerakhirRiayah, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAbsensiTerakhirRiayahRow
	for rows.Next() {
		var i ListAbsensiTerakhirRiayahRow
		if err := rows.Scan(
			&i.SantriID,
			&i.Status,
			&i.BatasMateri,
			&i.Tanggal,
			&i.Urutan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKontakTerakhirRiayah = `-- name: ListKontakTerakhirRiayah :many
SELECT rk.santri_id, CAST(MAX(rk.tanggal) AS TEXT) AS kontak_terakhir
FROM riayah_kontak rk
JOIN santri s ON s.id = rk.santri_id
JOIN kelas k ON k.id = s.kelas_id
WHERE s.status = 'aktif'
  AND (?1 IS NULL OR k.guru_id = ?1)
GROUP BY rk.santri_id
`

type ListKontakTerakhirRiayahRow struct {
	SantriID       int64
	KontakTerakhir string
}

func (q *Queries) ListKontakTerakhirRiayah(ctx context.Context, guruID interface{}) ([]ListKontakTerakhirRiayahRow, error) {
	rows, err := q.db.QueryContext(ctx, listKontakTerakhirRiayah, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKontakTerakhirRiayahRow
	for rows.Next() {
		var i ListKontakTerakhirRiayahRow
		if err := rows.Scan(&i.SantriID, &i.KontakTerakhir); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaporTerkirimSantri = `-- name: ListRaporTerkirimSantri :many
SELECT periode, tanggal
FROM riayah_kontak
WHERE santri_id = ? AND jenis = 'rapor'
ORDER BY tanggal DESC, id DESC
`

type ListRaporTerkirimSantriRow struct {
	Periode string
	Tanggal string
}

func (q *Queries) ListRaporTerkirimSantri(ctx context.Context, santriID int64) ([]ListRaporTerkirimSantriRow, error) {
	rows, err := q.db.QueryContext(ctx, listRaporTerkirimSantri, santriID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRaporTerkirimSantriRow
	for rows.Next() {
		var i ListRaporTerkirimSantriRow
		if err := rows.Scan(&i.Periode, &i.Tanggal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiayahKontakBySantri = `-- name: ListRiayahKontakBySantri :many
SELECT rk.id, rk.santri_id, rk.guru_id, rk.author_user_id, rk.tanggal, rk.media, rk.jenis, rk.periode, rk.catatan, rk.created_at, COALESCE(u.name, '') AS penulis_nama
FROM riayah_kontak rk
LEFT JOIN users u ON u.id = rk.author_user_id
WHERE rk.santri_id = ?
ORDER BY rk.tanggal DESC, rk.id DESC
LIMIT 200
`

type ListRiayahKontakBySantriRow struct {
	ID           int64
	SantriID     int64
	GuruID       sql.NullInt64
	AuthorUserID sql.NullInt64
	Tanggal      string
	Media        string
	Jenis        string
	Periode      string
	Catatan      string
	CreatedAt    time.Time
	PenulisNama  string
}

func (q *Queries) ListRiayahKontakBySantri(ctx context.Context, santriID int64) ([]ListRiayahKontakBySantriRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiayahKontakBySantri, santriID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiayahKontakBySantriRow
	for rows.Next() {
		var i ListRiayahKontakBySantriRow
		if err := rows.Scan(
			&i.ID,
			&i.SantriID,
			&i.GuruID,
			&i.AuthorUserID,
			&i.Tanggal,
			&i.Media,
			&i.Jenis,
			&i.Periode,
			&i.Catatan,
			&i.CreatedAt,
			&i.PenulisNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantriRaporTerkirimPeriode = `-- name: ListSantriRaporTerkirimPeriode :many
SELECT DISTINCT rk.santri_id
FROM riayah_kontak rk
JOIN santri s ON s.id = rk.santri_id
JOIN kelas k ON k.id = s.kelas_id
WHERE rk.jenis = 'rapor'
  AND rk.periode = ?1
  AND s.status = 'aktif'
  AND (?2 IS NULL OR k.guru_id = ?2)
`

type ListSantriRaporTerkirimPeriodeParams struct {
	Periode string
	GuruID  interface{}
}

func (q *Queries) ListSantriRaporTerkirimPeriode(ctx context.Context, arg ListSantriRaporTerkirimPeriodeParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSantriRaporTerkirimPeriode, arg.Periode, arg.GuruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var santri_id int64
		if err := rows.Scan(&santri_id); err != nil {
			return nil, err
		}
		items = append(items, santri_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantriRiayahScope = `-- name: ListSantriRiayahScope :many
SELECT s.id, s.nama, s.id_mahasantri, s.no_wa, s.jenis_kelamin,
    s.mulai_belajar, s.tanggal_daftar,
    k.id AS kelas_id, k.nama_kelas, k.level, k.jadwal,
    COALESCE(g.nama, '') AS guru_nama
FROM santri s
JOIN kelas k ON k.id = s.kelas_id
LEFT JOIN guru g ON g.id = k.guru_id
WHERE s.status = 'aktif'
  AND (?1 IS NULL OR k.guru_id = ?1)
ORDER BY k.nama_kelas, s.nama
`

type ListSantriRiayahScopeRow struct {
	ID            int64
	Nama          string
	IDMahasantri  string
	NoWa          string
	JenisKelamin  string
	MulaiBelajar  sql.NullTime
	TanggalDaftar sql.NullTime
	KelasID       int64
	NamaKelas     string
	Level         string
	Jadwal        string
	GuruNama      string
}

// Santri aktif yang menjadi tanggung jawab riayah. guru_id NULL = semua santri.
func (q *Queries) ListSantriRiayahScope(ctx context.Context, guruID interface{}) ([]ListSantriRiayahScopeRow, error) {
	rows, err := q.db.QueryContext(ctx, listSantriRiayahScope, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSantriRiayahScopeRow
	for rows.Next() {
		var i ListSantriRiayahScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.IDMahasantri,
			&i.NoWa,
			&i.JenisKelamin,
			&i.MulaiBelajar,
			&i.TanggalDaftar,
			&i.KelasID,
			&i.NamaKelas,
			&i.Level,
			&i.Jadwal,
			&i.GuruNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineAbsensiSantri = `-- name: ListTimelineAbsensiSantri :many
SELECT a.id, a.status, a.catatan, a.batas_materi,
    p.id AS pertemuan_id, p.tanggal, p.pertemuan_level_ke, p.materi,
    k.nama_kelas
FROM absensi a
JOIN pertemuan p ON p.id = a.pertemuan_id
JOIN kelas k ON k.id = p.kelas_id
WHERE a.santri_id = ? AND p.status = 'selesai'
ORDER BY p.tanggal DESC, p.id DESC
LIMIT 200
`

type ListTimelineAbsensiSantriRow struct {
	ID               int64
	Status           string
	Catatan          string
	BatasMateri      string
	PertemuanID      int64
	Tanggal          time.Time
	PertemuanLevelKe int64
	Materi           string
	NamaKelas        string
}

func (q *Queries) ListTimelineAbsensiSantri(ctx context.Context, santriID int64) ([]ListTimelineAbsensiSantriRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineAbsensiSantri, santriID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineAbsensiSantriRow
	for rows.Next() {
		var i ListTimelineAbsensiSantriRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Catatan,
			&i.BatasMateri,
			&i.PertemuanID,
			&i.Tanggal,
			&i.PertemuanLevelKe,
			&i.Materi,
			&i.NamaKelas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rekapKehadiranRiayahSejak = `-- name: RekapKehadiranRiayahSejak :many
SELECT a.santri_id,
    COUNT(*) AS total,
    SUM(CASE WHEN a.status IN ('hadir', 'telat') THEN 1 ELSE 0 END) AS total_hadir
FROM absensi a
JOIN pertemuan p ON p.id = a.pertemuan_id
JOIN santri s ON s.id = a.santri_id
JOIN kelas k ON k.id = s.kelas_id
WHERE p.status = 'selesai'
  AND s.status = 'aktif'
  AND p.tanggal >= CAST(?1 AS TEXT)
  AND (?2 IS NULL OR k.guru_id = ?2)
GROUP BY a.santri_id
`

type RekapKehadiranRiayahSejakParams struct {
	Sejak  string
	GuruID interface{}
}

type RekapKehadiranRiayahSejakRow struct {
	SantriID   int64
	Total      int64
	TotalHadir sql.NullFloat64
}

// Kehadiran (hadir + telat) per santri sejak tanggal tertentu.
func (q *Queries) RekapKehadiranRiayahSejak(ctx context.Context, arg RekapKehadiranRiayahSejakParams) ([]RekapKehadiranRiayahSejakRow, error) {
	rows, err := q.db.QueryContext(ctx, rekapKehadiranRiayahSejak, arg.Sejak, arg.GuruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RekapKehadiranRiayahSejakRow
	for rows.Next() {
		var i RekapKehadiranRiayahSejakRow
		if err := rows.Scan(&i.SantriID, &i.Total, &i.TotalHadir); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
