// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: riayah.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countRiayahByGuru = `-- name: CountRiayahByGuru :one
SELECT COUNT(*) FROM catatan_riayah WHERE guru_id = ?
`

func (q *Queries) CountRiayahByGuru(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRiayahByGuru, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRiayah = `-- name: CreateRiayah :execresult
INSERT INTO catatan_riayah (guru_id, author_user_id, target_type, target_id, catatan)
VALUES (?, ?, ?, ?, ?)
`

type CreateRiayahParams struct {
	GuruID       sql.NullInt64
	AuthorUserID sql.NullInt64
	TargetType   string
	TargetID     int64
	Catatan      string
}

func (q *Queries) CreateRiayah(ctx context.Context, arg CreateRiayahParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRiayah,
		arg.GuruID,
		arg.AuthorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Catatan,
	)
}

const createUserRiayah = `-- name: CreateUserRiayah :execresult
INSERT INTO catatan_riayah (author_user_id, target_type, target_id, catatan)
VALUES (?, ?, ?, ?)
`

type CreateUserRiayahParams struct {
	AuthorUserID sql.NullInt64
	TargetType   string
	TargetID     int64
	Catatan      string
}

func (q *Queries) CreateUserRiayah(ctx context.Context, arg CreateUserRiayahParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserRiayah,
		arg.AuthorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Catatan,
	)
}

const deleteRiayah = `-- name: DeleteRiayah :exec
DELETE FROM catatan_riayah WHERE id = ? AND guru_id = ?
`

type DeleteRiayahParams struct {
	ID     int64
	GuruID sql.NullInt64
}

func (q *Queries) DeleteRiayah(ctx context.Context, arg DeleteRiayahParams) error {
	_, err := q.db.ExecContext(ctx, deleteRiayah, arg.ID, arg.GuruID)
	return err
}

const deleteRiayahByID = `-- name: DeleteRiayahByID :exec
DELETE FROM catatan_riayah WHERE id = ?
`

func (q *Queries) DeleteRiayahByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRiayahByID, id)
	return err
}

const deleteRiayahByTarget = `-- name: DeleteRiayahByTarget :exec
DELETE FROM catatan_riayah WHERE target_type = ? AND target_id = ?
`

type DeleteRiayahByTargetParams struct {
	TargetType string
	TargetID   int64
}

func (q *Queries) DeleteRiayahByTarget(ctx context.Context, arg DeleteRiayahByTargetParams) error {
	_, err := q.db.ExecContext(ctx, deleteRiayahByTarget, arg.TargetType, arg.TargetID)
	return err
}

const getRiayahByID = `-- name: GetRiayahByID :one
SELECT id, guru_id, author_user_id, target_type, target_id, catatan, created_at, updated_at FROM catatan_riayah WHERE id = ?
`

func (q *Queries) GetRiayahByID(ctx context.Context, id int64) (CatatanRiayah, error) {
	row := q.db.QueryRowContext(ctx, getRiayahByID, id)
	var i CatatanRiayah
	err := row.Scan(
		&i.ID,
		&i.GuruID,
		&i.AuthorUserID,
		&i.TargetType,
		&i.TargetID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRiayahByGuru = `-- name: ListRiayahByGuru :many
SELECT cr.id, cr.guru_id, cr.author_user_id, cr.target_type, cr.target_id, cr.catatan, cr.created_at, cr.updated_at,
    COALESCE(s.nama, '') AS target_nama,
    COALESCE(s.id_mahasantri, '') AS target_id_mahasantri,
    COALESCE(author.name, u.name) AS penulis_nama
FROM catatan_riayah cr
LEFT JOIN santri s ON cr.target_type = 'santri' AND cr.target_id = s.id
LEFT JOIN guru g ON cr.guru_id = g.id
LEFT JOIN users u ON g.user_id = u.id
LEFT JOIN users author ON cr.author_user_id = author.id
WHERE cr.guru_id = ?
ORDER BY cr.created_at DESC
`

type ListRiayahByGuruRow struct {
	ID                 int64
	GuruID             sql.NullInt64
	AuthorUserID       sql.NullInt64
	TargetType         string
	TargetID           int64
	Catatan            string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TargetNama         string
	TargetIDMahasantri string
	PenulisNama        string
}

func (q *Queries) ListRiayahByGuru(ctx context.Context, guruID sql.NullInt64) ([]ListRiayahByGuruRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiayahByGuru, guruID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiayahByGuruRow
	for rows.Next() {
		var i ListRiayahByGuruRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.AuthorUserID,
			&i.TargetType,
			&i.TargetID,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetNama,
			&i.TargetIDMahasantri,
			&i.PenulisNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiayahByTarget = `-- name: ListRiayahByTarget :many
SELECT cr.id, cr.guru_id, cr.author_user_id, cr.target_type, cr.target_id, cr.catatan, cr.created_at, cr.updated_at, COALESCE(author.name, u.name) AS penulis_nama
FROM catatan_riayah cr
LEFT JOIN guru g ON cr.guru_id = g.id
LEFT JOIN users u ON g.user_id = u.id
LEFT JOIN users author ON cr.author_user_id = author.id
WHERE cr.target_type = ? AND cr.target_id = ?
ORDER BY cr.created_at DESC
`

type ListRiayahByTargetParams struct {
	TargetType string
	TargetID   int64
}

type ListRiayahByTargetRow struct {
	ID           int64
	GuruID       sql.NullInt64
	AuthorUserID sql.NullInt64
	TargetType   string
	TargetID     int64
	Catatan      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PenulisNama  string
}

func (q *Queries) ListRiayahByTarget(ctx context.Context, arg ListRiayahByTargetParams) ([]ListRiayahByTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiayahByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiayahByTargetRow
	for rows.Next() {
		var i ListRiayahByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.AuthorUserID,
			&i.TargetType,
			&i.TargetID,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PenulisNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRiayah = `-- name: UpdateRiayah :exec
UPDATE catatan_riayah
SET catatan = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND guru_id = ?
`

type UpdateRiayahParams struct {
	Catatan string
	ID      int64
	GuruID  sql.NullInt64
}

func (q *Queries) UpdateRiayah(ctx context.Context, arg UpdateRiayahParams) error {
	_, err := q.db.ExecContext(ctx, updateRiayah, arg.Catatan, arg.ID, arg.GuruID)
	return err
}

const updateRiayahByID = `-- name: UpdateRiayahByID :exec
UPDATE catatan_riayah
SET catatan = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRiayahByIDParams struct {
	Catatan string
	ID      int64
}

func (q *Queries) UpdateRiayahByID(ctx context.Context, arg UpdateRiayahByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRiayahByID, arg.Catatan, arg.ID)
	return err
}
