// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: santri.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countSantri = `-- name: CountSantri :one
SELECT COUNT(*) FROM santri
WHERE (?1 = '' OR angkatan = ?1)
  AND (?2 = '' OR level = ?2)
  AND (?3 = '' OR tipe = ?3)
  AND (?4 = '' OR jadwal = ?4)
  AND (?5 = '' OR jenis_kelamin = ?5)
  AND (?6 = '' OR status = ?6)
  AND (?7 IS NULL OR kelas_id = ?7)
  AND (?8 = -1 OR is_lengkap = ?8)
  AND (?9 = '' OR nama LIKE '%' || ?9 || '%' OR id_mahasantri LIKE '%' || ?9 || '%')
`

type CountSantriParams struct {
	Angkatan interface{}
	Level    interface{}
	Tipe     interface{}
	Jadwal   interface{}
	Gender   interface{}
	Status   interface{}
	KelasID  interface{}
	Lengkap  interface{}
	Search   interface{}
}

func (q *Queries) CountSantri(ctx context.Context, arg CountSantriParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSantri,
		arg.Angkatan,
		arg.Level,
		arg.Tipe,
		arg.Jadwal,
		arg.Gender,
		arg.Status,
		arg.KelasID,
		arg.Lengkap,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSantriByAngkatan = `-- name: CountSantriByAngkatan :many
SELECT angkatan, COUNT(*) as total FROM santri
WHERE status = 'aktif'
GROUP BY angkatan
ORDER BY angkatan
`

type CountSantriByAngkatanRow struct {
	Angkatan string
	Total    int64
}

func (q *Queries) CountSantriByAngkatan(ctx context.Context) ([]CountSantriByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByAngkatanRow
	for rows.Next() {
		var i CountSantriByAngkatanRow
		if err := rows.Scan(&i.Angkatan, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByGender = `-- name: CountSantriByGender :many
SELECT jenis_kelamin, COUNT(*) as total FROM santri
WHERE status = 'aktif'
GROUP BY jenis_kelamin
`

type CountSantriByGenderRow struct {
	JenisKelamin string
	Total        int64
}

func (q *Queries) CountSantriByGender(ctx context.Context) ([]CountSantriByGenderRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByGenderRow
	for rows.Next() {
		var i CountSantriByGenderRow
		if err := rows.Scan(&i.JenisKelamin, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByLevel = `-- name: CountSantriByLevel :many
SELECT level, COUNT(*) as total FROM santri
WHERE status = 'aktif' AND level != ''
GROUP BY level
ORDER BY level
`

type CountSantriByLevelRow struct {
	Level string
	Total int64
}

func (q *Queries) CountSantriByLevel(ctx context.Context) ([]CountSantriByLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByLevelRow
	for rows.Next() {
		var i CountSantriByLevelRow
		if err := rows.Scan(&i.Level, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByStatus = `-- name: CountSantriByStatus :many
SELECT status, COUNT(*) as total FROM santri
GROUP BY status
`

type CountSantriByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountSantriByStatus(ctx context.Context) ([]CountSantriByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByStatusRow
	for rows.Next() {
		var i CountSantriByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByTipe = `-- name: CountSantriByTipe :many
SELECT tipe, COUNT(*) as total FROM santri
WHERE status = 'aktif' AND tipe != ''
GROUP BY tipe
`

type CountSantriByTipeRow struct {
	Tipe  string
	Total int64
}

func (q *Queries) CountSantriByTipe(ctx context.Context) ([]CountSantriByTipeRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByTipe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByTipeRow
	for rows.Next() {
		var i CountSantriByTipeRow
		if err := rows.Scan(&i.Tipe, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSantri = `-- name: CreateSantri :execresult
INSERT INTO santri (
    id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar,
    angkatan, usia, domisili, tipe, frekuensi, is_lengkap, kelas_id,
    status, created_by, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateSantriParams struct {
	IDMahasantri  string
	KelasKode     string
	Nama          string
	JenisKelamin  string
	Nominal       int64
	TanggalDaftar sql.NullTime
	Angkatan      string
	Usia          sql.NullInt64
	Domisili      string
	Tipe          string
	Frekuensi     string
	IsLengkap     int64
	KelasID       sql.NullInt64
	Status        string
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateSantri(ctx context.Context, arg CreateSantriParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSantri,
		arg.IDMahasantri,
		arg.KelasKode,
		arg.Nama,
		arg.JenisKelamin,
		arg.Nominal,
		arg.TanggalDaftar,
		arg.Angkatan,
		arg.Usia,
		arg.Domisili,
		arg.Tipe,
		arg.Frekuensi,
		arg.IsLengkap,
		arg.KelasID,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteSantri = `-- name: DeleteSantri :exec
DELETE FROM santri WHERE id = ?
`

func (q *Queries) DeleteSantri(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSantri, id)
	return err
}

const getPerluDilengkapi = `-- name: GetPerluDilengkapi :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at FROM santri
WHERE is_lengkap = 0 AND status = 'aktif'
ORDER BY id DESC
`

func (q *Queries) GetPerluDilengkapi(ctx context.Context) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, getPerluDilengkapi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSantriByID = `-- name: GetSantriByID :one
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at FROM santri WHERE id = ?
`

func (q *Queries) GetSantriByID(ctx context.Context, id int64) (Santri, error) {
	row := q.db.QueryRowContext(ctx, getSantriByID, id)
	var i Santri
	err := row.Scan(
		&i.ID,
		&i.IDMahasantri,
		&i.KelasKode,
		&i.Nama,
		&i.JenisKelamin,
		&i.Nominal,
		&i.TanggalDaftar,
		&i.Angkatan,
		&i.Usia,
		&i.Domisili,
		&i.Fu,
		&i.TanggalVn,
		&i.HasilVn,
		&i.MasukGrup,
		&i.MulaiBelajar,
		&i.Jumlah,
		&i.Level,
		&i.Jadwal,
		&i.Guru,
		&i.JadwalCatatan,
		&i.InfaqTerakhir,
		&i.KeteranganTidakLanjut,
		&i.Tipe,
		&i.Frekuensi,
		&i.IsLengkap,
		&i.KelasID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSantriByKelasID = `-- name: GetSantriByKelasID :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at FROM santri
WHERE kelas_id = ? AND status = 'aktif'
ORDER BY nama
`

func (q *Queries) GetSantriByKelasID(ctx context.Context, kelasID sql.NullInt64) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, getSantriByKelasID, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantri = `-- name: ListSantri :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at FROM santri
WHERE (?1 = '' OR angkatan = ?1)
  AND (?2 = '' OR level = ?2)
  AND (?3 = '' OR tipe = ?3)
  AND (?4 = '' OR jadwal = ?4)
  AND (?5 = '' OR jenis_kelamin = ?5)
  AND (?6 = '' OR status = ?6)
  AND (?7 IS NULL OR kelas_id = ?7)
  AND (?8 = -1 OR is_lengkap = ?8)
  AND (?9 = '' OR nama LIKE '%' || ?9 || '%' OR id_mahasantri LIKE '%' || ?9 || '%')
ORDER BY id DESC
LIMIT ?11 OFFSET ?10
`

type ListSantriParams struct {
	Angkatan interface{}
	Level    interface{}
	Tipe     interface{}
	Jadwal   interface{}
	Gender   interface{}
	Status   interface{}
	KelasID  interface{}
	Lengkap  interface{}
	Search   interface{}
	Off      int64
	Lim      int64
}

func (q *Queries) ListSantri(ctx context.Context, arg ListSantriParams) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, listSantri,
		arg.Angkatan,
		arg.Level,
		arg.Tipe,
		arg.Jadwal,
		arg.Gender,
		arg.Status,
		arg.KelasID,
		arg.Lengkap,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNominalByAngkatan = `-- name: SumNominalByAngkatan :many
SELECT angkatan, SUM(nominal) as total_nominal FROM santri
WHERE status = 'aktif' AND nominal > 0
GROUP BY angkatan
ORDER BY angkatan
`

type SumNominalByAngkatanRow struct {
	Angkatan     string
	TotalNominal sql.NullFloat64
}

func (q *Queries) SumNominalByAngkatan(ctx context.Context) ([]SumNominalByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, sumNominalByAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumNominalByAngkatanRow
	for rows.Next() {
		var i SumNominalByAngkatanRow
		if err := rows.Scan(&i.Angkatan, &i.TotalNominal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSantriAdminKelas = `-- name: UpdateSantriAdminKelas :exec
UPDATE santri
SET fu = ?, tanggal_vn = ?, hasil_vn = ?, masuk_grup = ?,
    mulai_belajar = ?, jumlah = ?, level = ?, jadwal = ?,
    guru = ?, tipe = ?, frekuensi = ?, is_lengkap = ?,
    kelas_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriAdminKelasParams struct {
	Fu           string
	TanggalVn    sql.NullTime
	HasilVn      string
	MasukGrup    string
	MulaiBelajar sql.NullTime
	Jumlah       sql.NullInt64
	Level        string
	Jadwal       string
	Guru         string
	Tipe         string
	Frekuensi    string
	IsLengkap    int64
	KelasID      sql.NullInt64
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) UpdateSantriAdminKelas(ctx context.Context, arg UpdateSantriAdminKelasParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriAdminKelas,
		arg.Fu,
		arg.TanggalVn,
		arg.HasilVn,
		arg.MasukGrup,
		arg.MulaiBelajar,
		arg.Jumlah,
		arg.Level,
		arg.Jadwal,
		arg.Guru,
		arg.Tipe,
		arg.Frekuensi,
		arg.IsLengkap,
		arg.KelasID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriCS = `-- name: UpdateSantriCS :exec
UPDATE santri
SET kelas_kode = ?, nama = ?, jenis_kelamin = ?, nominal = ?,
    tanggal_daftar = ?, angkatan = ?, usia = ?, domisili = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateSantriCSParams struct {
	KelasKode     string
	Nama          string
	JenisKelamin  string
	Nominal       int64
	TanggalDaftar sql.NullTime
	Angkatan      string
	Usia          sql.NullInt64
	Domisili      string
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateSantriCS(ctx context.Context, arg UpdateSantriCSParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriCS,
		arg.KelasKode,
		arg.Nama,
		arg.JenisKelamin,
		arg.Nominal,
		arg.TanggalDaftar,
		arg.Angkatan,
		arg.Usia,
		arg.Domisili,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriEngine = `-- name: UpdateSantriEngine :exec
UPDATE santri
SET tipe = ?, frekuensi = ?, is_lengkap = ?, kelas_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriEngineParams struct {
	Tipe      string
	Frekuensi string
	IsLengkap int64
	KelasID   sql.NullInt64
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSantriEngine(ctx context.Context, arg UpdateSantriEngineParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriEngine,
		arg.Tipe,
		arg.Frekuensi,
		arg.IsLengkap,
		arg.KelasID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriIdMahasantri = `-- name: UpdateSantriIdMahasantri :exec
UPDATE santri SET id_mahasantri = ? WHERE id = ?
`

type UpdateSantriIdMahasantriParams struct {
	IDMahasantri string
	ID           int64
}

func (q *Queries) UpdateSantriIdMahasantri(ctx context.Context, arg UpdateSantriIdMahasantriParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriIdMahasantri, arg.IDMahasantri, arg.ID)
	return err
}

const updateSantriKelas = `-- name: UpdateSantriKelas :exec
UPDATE santri SET kelas_id = ?, updated_at = ? WHERE id = ?
`

type UpdateSantriKelasParams struct {
	KelasID   sql.NullInt64
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSantriKelas(ctx context.Context, arg UpdateSantriKelasParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriKelas, arg.KelasID, arg.UpdatedAt, arg.ID)
	return err
}

const updateSantriKeuangan = `-- name: UpdateSantriKeuangan :exec
UPDATE santri
SET infaq_terakhir = ?, keterangan_tidak_lanjut = ?,
    status = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriKeuanganParams struct {
	InfaqTerakhir         string
	KeteranganTidakLanjut string
	Status                string
	UpdatedAt             time.Time
	ID                    int64
}

func (q *Queries) UpdateSantriKeuangan(ctx context.Context, arg UpdateSantriKeuanganParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriKeuangan,
		arg.InfaqTerakhir,
		arg.KeteranganTidakLanjut,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriStatus = `-- name: UpdateSantriStatus :exec
UPDATE santri SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateSantriStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSantriStatus(ctx context.Context, arg UpdateSantriStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
