// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: santri.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const clearSantriKelasByKelasID = `-- name: ClearSantriKelasByKelasID :exec
UPDATE santri SET kelas_id = NULL, angkatan_kelas = '', is_lengkap = 0, updated_at = ? WHERE kelas_id = ?
`

type ClearSantriKelasByKelasIDParams struct {
	UpdatedAt time.Time
	KelasID   sql.NullInt64
}

func (q *Queries) ClearSantriKelasByKelasID(ctx context.Context, arg ClearSantriKelasByKelasIDParams) error {
	_, err := q.db.ExecContext(ctx, clearSantriKelasByKelasID, arg.UpdatedAt, arg.KelasID)
	return err
}

const correctSantriRegistrationIdentity = `-- name: CorrectSantriRegistrationIdentity :exec
UPDATE santri
SET id_mahasantri = ?, angkatan = ?, tanggal_daftar = ?, updated_at = ?
WHERE id = ?
`

type CorrectSantriRegistrationIdentityParams struct {
	IDMahasantri  string
	Angkatan      string
	TanggalDaftar sql.NullTime
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) CorrectSantriRegistrationIdentity(ctx context.Context, arg CorrectSantriRegistrationIdentityParams) error {
	_, err := q.db.ExecContext(ctx, correctSantriRegistrationIdentity,
		arg.IDMahasantri,
		arg.Angkatan,
		arg.TanggalDaftar,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countSantri = `-- name: CountSantri :one
SELECT COUNT(*) FROM santri
WHERE (?1 = '' OR angkatan = ?1)
  AND (?2 = '' OR angkatan_kelas = ?2)
  AND (?3 = '' OR level = ?3)
  AND (?4 = '' OR tipe = ?4)
  AND (?5 = '' OR jadwal = ?5)
  AND (?6 = '' OR jenis_kelamin = ?6)
  AND (?7 = '' OR status = ?7)
  AND (?8 IS NULL OR kelas_id = ?8)
  AND (?9 = -1 OR is_lengkap = ?9)
  AND (?10 = 0 OR (
      substr(id_mahasantri, 1, 4) != 'MHS.'
      OR length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6 <= 0
      OR substr(id_mahasantri, 5, length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6)
          != trim(substr(id_mahasantri, 5, length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6), ' ' || char(9) || char(10) || char(11) || char(12) || char(13))
      OR substr(id_mahasantri, 5 + length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6)
          != ('.' || printf('%04d', id) || '.' || substr(id_mahasantri, -6))
      OR substr(id_mahasantri, -6) NOT GLOB '[0-9][0-9][0-9][0-9][0-9][0-9]'
      OR CAST(substr(id_mahasantri, -6, 2) AS INTEGER) NOT BETWEEN 1 AND 12
      OR EXISTS (SELECT 1 FROM santri duplicate WHERE duplicate.id_mahasantri = santri.id_mahasantri AND duplicate.id != santri.id)
  ))
  AND (?11 = '' OR nama LIKE '%' || ?11 || '%' OR id_mahasantri LIKE '%' || ?11 || '%')
`

type CountSantriParams struct {
	AngkatanPendaftaran interface{}
	AngkatanKelas       interface{}
	Level               interface{}
	Tipe                interface{}
	Jadwal              interface{}
	Gender              interface{}
	Status              interface{}
	KelasID             interface{}
	Lengkap             interface{}
	IDBermasalah        interface{}
	Search              interface{}
}

func (q *Queries) CountSantri(ctx context.Context, arg CountSantriParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSantri,
		arg.AngkatanPendaftaran,
		arg.AngkatanKelas,
		arg.Level,
		arg.Tipe,
		arg.Jadwal,
		arg.Gender,
		arg.Status,
		arg.KelasID,
		arg.Lengkap,
		arg.IDBermasalah,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSantriByAngkatan = `-- name: CountSantriByAngkatan :many
SELECT angkatan, COUNT(*) as total FROM santri
WHERE status = 'aktif'
GROUP BY angkatan
ORDER BY angkatan
`

type CountSantriByAngkatanRow struct {
	Angkatan string
	Total    int64
}

func (q *Queries) CountSantriByAngkatan(ctx context.Context) ([]CountSantriByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByAngkatanRow
	for rows.Next() {
		var i CountSantriByAngkatanRow
		if err := rows.Scan(&i.Angkatan, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByGender = `-- name: CountSantriByGender :many
SELECT jenis_kelamin, COUNT(*) as total FROM santri
WHERE status = 'aktif'
GROUP BY jenis_kelamin
`

type CountSantriByGenderRow struct {
	JenisKelamin string
	Total        int64
}

func (q *Queries) CountSantriByGender(ctx context.Context) ([]CountSantriByGenderRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByGenderRow
	for rows.Next() {
		var i CountSantriByGenderRow
		if err := rows.Scan(&i.JenisKelamin, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByLevel = `-- name: CountSantriByLevel :many
SELECT level, COUNT(*) as total FROM santri
WHERE status = 'aktif' AND level != ''
GROUP BY level
ORDER BY level
`

type CountSantriByLevelRow struct {
	Level string
	Total int64
}

func (q *Queries) CountSantriByLevel(ctx context.Context) ([]CountSantriByLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByLevelRow
	for rows.Next() {
		var i CountSantriByLevelRow
		if err := rows.Scan(&i.Level, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByStatus = `-- name: CountSantriByStatus :many
SELECT status, COUNT(*) as total FROM santri
GROUP BY status
`

type CountSantriByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountSantriByStatus(ctx context.Context) ([]CountSantriByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByStatusRow
	for rows.Next() {
		var i CountSantriByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSantriByTipe = `-- name: CountSantriByTipe :many
SELECT tipe, COUNT(*) as total FROM santri
WHERE status = 'aktif' AND tipe != ''
GROUP BY tipe
`

type CountSantriByTipeRow struct {
	Tipe  string
	Total int64
}

func (q *Queries) CountSantriByTipe(ctx context.Context) ([]CountSantriByTipeRow, error) {
	rows, err := q.db.QueryContext(ctx, countSantriByTipe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSantriByTipeRow
	for rows.Next() {
		var i CountSantriByTipeRow
		if err := rows.Scan(&i.Tipe, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSantri = `-- name: CreateSantri :execresult
INSERT INTO santri (
    id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar,
    angkatan, angkatan_kelas, usia, domisili, no_wa, email, tipe, frekuensi, is_lengkap, kelas_id,
    status, created_by, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateSantriParams struct {
	IDMahasantri  string
	KelasKode     string
	Nama          string
	JenisKelamin  string
	Nominal       int64
	TanggalDaftar sql.NullTime
	Angkatan      string
	AngkatanKelas string
	Usia          sql.NullInt64
	Domisili      string
	NoWa          string
	Email         string
	Tipe          string
	Frekuensi     string
	IsLengkap     int64
	KelasID       sql.NullInt64
	Status        string
	CreatedBy     sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateSantri(ctx context.Context, arg CreateSantriParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSantri,
		arg.IDMahasantri,
		arg.KelasKode,
		arg.Nama,
		arg.JenisKelamin,
		arg.Nominal,
		arg.TanggalDaftar,
		arg.Angkatan,
		arg.AngkatanKelas,
		arg.Usia,
		arg.Domisili,
		arg.NoWa,
		arg.Email,
		arg.Tipe,
		arg.Frekuensi,
		arg.IsLengkap,
		arg.KelasID,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteSantri = `-- name: DeleteSantri :exec
DELETE FROM santri WHERE id = ?
`

func (q *Queries) DeleteSantri(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSantri, id)
	return err
}

const getPerluDilengkapi = `-- name: GetPerluDilengkapi :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas FROM santri
WHERE is_lengkap = 0 AND status = 'aktif'
ORDER BY id DESC
`

func (q *Queries) GetPerluDilengkapi(ctx context.Context) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, getPerluDilengkapi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSantriByID = `-- name: GetSantriByID :one
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas FROM santri WHERE id = ?
`

func (q *Queries) GetSantriByID(ctx context.Context, id int64) (Santri, error) {
	row := q.db.QueryRowContext(ctx, getSantriByID, id)
	var i Santri
	err := row.Scan(
		&i.ID,
		&i.IDMahasantri,
		&i.KelasKode,
		&i.Nama,
		&i.JenisKelamin,
		&i.Nominal,
		&i.TanggalDaftar,
		&i.Angkatan,
		&i.Usia,
		&i.Domisili,
		&i.Fu,
		&i.TanggalVn,
		&i.HasilVn,
		&i.MasukGrup,
		&i.MulaiBelajar,
		&i.Jumlah,
		&i.Level,
		&i.Jadwal,
		&i.Guru,
		&i.JadwalCatatan,
		&i.InfaqTerakhir,
		&i.KeteranganTidakLanjut,
		&i.Tipe,
		&i.Frekuensi,
		&i.IsLengkap,
		&i.KelasID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NoWa,
		&i.VoiceNoteUrl,
		&i.KeteranganVn,
		&i.Email,
		&i.PertemuanAwal,
		&i.AngkatanKelas,
	)
	return i, err
}

const getSantriByKelasID = `-- name: GetSantriByKelasID :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas FROM santri
WHERE kelas_id = ? AND status = 'aktif'
ORDER BY nama
`

func (q *Queries) GetSantriByKelasID(ctx context.Context, kelasID sql.NullInt64) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, getSantriByKelasID, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueSantriRegistrationIdentity = `-- name: IssueSantriRegistrationIdentity :exec
UPDATE santri
SET id_mahasantri = ?, angkatan = ?, tanggal_daftar = ?, updated_at = ?
WHERE id = ?
`

type IssueSantriRegistrationIdentityParams struct {
	IDMahasantri  string
	Angkatan      string
	TanggalDaftar sql.NullTime
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) IssueSantriRegistrationIdentity(ctx context.Context, arg IssueSantriRegistrationIdentityParams) error {
	_, err := q.db.ExecContext(ctx, issueSantriRegistrationIdentity,
		arg.IDMahasantri,
		arg.Angkatan,
		arg.TanggalDaftar,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const listDuplicateIDMahasantri = `-- name: ListDuplicateIDMahasantri :many
SELECT id_mahasantri FROM santri
WHERE id_mahasantri != ''
GROUP BY id_mahasantri
HAVING COUNT(*) > 1
`

func (q *Queries) ListDuplicateIDMahasantri(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateIDMahasantri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id_mahasantri string
		if err := rows.Scan(&id_mahasantri); err != nil {
			return nil, err
		}
		items = append(items, id_mahasantri)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantri = `-- name: ListSantri :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas FROM santri
WHERE (?1 = '' OR angkatan = ?1)
  AND (?2 = '' OR angkatan_kelas = ?2)
  AND (?3 = '' OR level = ?3)
  AND (?4 = '' OR tipe = ?4)
  AND (?5 = '' OR jadwal = ?5)
  AND (?6 = '' OR jenis_kelamin = ?6)
  AND (?7 = '' OR status = ?7)
  AND (?8 IS NULL OR kelas_id = ?8)
  AND (?9 = -1 OR is_lengkap = ?9)
  AND (?10 = 0 OR (
      substr(id_mahasantri, 1, 4) != 'MHS.'
      OR length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6 <= 0
      OR substr(id_mahasantri, 5, length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6)
          != trim(substr(id_mahasantri, 5, length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6), ' ' || char(9) || char(10) || char(11) || char(12) || char(13))
      OR substr(id_mahasantri, 5 + length(id_mahasantri) - 4 - length('.' || printf('%04d', id) || '.') - 6)
          != ('.' || printf('%04d', id) || '.' || substr(id_mahasantri, -6))
      OR substr(id_mahasantri, -6) NOT GLOB '[0-9][0-9][0-9][0-9][0-9][0-9]'
      OR CAST(substr(id_mahasantri, -6, 2) AS INTEGER) NOT BETWEEN 1 AND 12
      OR EXISTS (SELECT 1 FROM santri duplicate WHERE duplicate.id_mahasantri = santri.id_mahasantri AND duplicate.id != santri.id)
  ))
  AND (?11 = '' OR nama LIKE '%' || ?11 || '%' OR id_mahasantri LIKE '%' || ?11 || '%')
ORDER BY id DESC
LIMIT ?13 OFFSET ?12
`

type ListSantriParams struct {
	AngkatanPendaftaran interface{}
	AngkatanKelas       interface{}
	Level               interface{}
	Tipe                interface{}
	Jadwal              interface{}
	Gender              interface{}
	Status              interface{}
	KelasID             interface{}
	Lengkap             interface{}
	IDBermasalah        interface{}
	Search              interface{}
	Off                 int64
	Lim                 int64
}

func (q *Queries) ListSantri(ctx context.Context, arg ListSantriParams) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, listSantri,
		arg.AngkatanPendaftaran,
		arg.AngkatanKelas,
		arg.Level,
		arg.Tipe,
		arg.Jadwal,
		arg.Gender,
		arg.Status,
		arg.KelasID,
		arg.Lengkap,
		arg.IDBermasalah,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNominalByAngkatan = `-- name: SumNominalByAngkatan :many
SELECT angkatan, SUM(nominal) as total_nominal FROM santri
WHERE status = 'aktif' AND nominal > 0
GROUP BY angkatan
ORDER BY angkatan
`

type SumNominalByAngkatanRow struct {
	Angkatan     string
	TotalNominal sql.NullFloat64
}

func (q *Queries) SumNominalByAngkatan(ctx context.Context) ([]SumNominalByAngkatanRow, error) {
	rows, err := q.db.QueryContext(ctx, sumNominalByAngkatan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumNominalByAngkatanRow
	for rows.Next() {
		var i SumNominalByAngkatanRow
		if err := rows.Scan(&i.Angkatan, &i.TotalNominal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSantriAdminKelas = `-- name: UpdateSantriAdminKelas :exec
UPDATE santri
SET fu = ?, tanggal_vn = ?, hasil_vn = ?, masuk_grup = ?,
    mulai_belajar = ?, jumlah = ?, angkatan_kelas = ?, level = ?, jadwal = ?,
    guru = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriAdminKelasParams struct {
	Fu            string
	TanggalVn     sql.NullTime
	HasilVn       string
	MasukGrup     string
	MulaiBelajar  sql.NullTime
	Jumlah        sql.NullInt64
	AngkatanKelas string
	Level         string
	Jadwal        string
	Guru          string
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateSantriAdminKelas(ctx context.Context, arg UpdateSantriAdminKelasParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriAdminKelas,
		arg.Fu,
		arg.TanggalVn,
		arg.HasilVn,
		arg.MasukGrup,
		arg.MulaiBelajar,
		arg.Jumlah,
		arg.AngkatanKelas,
		arg.Level,
		arg.Jadwal,
		arg.Guru,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriCSMutable = `-- name: UpdateSantriCSMutable :exec
UPDATE santri
SET kelas_kode = ?, nama = ?, jenis_kelamin = ?, nominal = ?,
    usia = ?, domisili = ?, no_wa = ?, email = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateSantriCSMutableParams struct {
	KelasKode    string
	Nama         string
	JenisKelamin string
	Nominal      int64
	Usia         sql.NullInt64
	Domisili     string
	NoWa         string
	Email        string
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) UpdateSantriCSMutable(ctx context.Context, arg UpdateSantriCSMutableParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriCSMutable,
		arg.KelasKode,
		arg.Nama,
		arg.JenisKelamin,
		arg.Nominal,
		arg.Usia,
		arg.Domisili,
		arg.NoWa,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriEngine = `-- name: UpdateSantriEngine :exec
UPDATE santri
SET tipe = ?, frekuensi = ?, is_lengkap = ?, kelas_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriEngineParams struct {
	Tipe      string
	Frekuensi string
	IsLengkap int64
	KelasID   sql.NullInt64
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSantriEngine(ctx context.Context, arg UpdateSantriEngineParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriEngine,
		arg.Tipe,
		arg.Frekuensi,
		arg.IsLengkap,
		arg.KelasID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriIdMahasantri = `-- name: UpdateSantriIdMahasantri :exec
UPDATE santri SET id_mahasantri = ? WHERE id = ?
`

type UpdateSantriIdMahasantriParams struct {
	IDMahasantri string
	ID           int64
}

func (q *Queries) UpdateSantriIdMahasantri(ctx context.Context, arg UpdateSantriIdMahasantriParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriIdMahasantri, arg.IDMahasantri, arg.ID)
	return err
}

const updateSantriKelas = `-- name: UpdateSantriKelas :exec
UPDATE santri
SET kelas_id = ?, angkatan_kelas = ?, kelas_kode = ?, level = ?, jadwal = ?,
    tipe = ?, frekuensi = ?, is_lengkap = 1, updated_at = ?
WHERE id = ?
`

type UpdateSantriKelasParams struct {
	KelasID       sql.NullInt64
	AngkatanKelas string
	KelasKode     string
	Level         string
	Jadwal        string
	Tipe          string
	Frekuensi     string
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateSantriKelas(ctx context.Context, arg UpdateSantriKelasParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriKelas,
		arg.KelasID,
		arg.AngkatanKelas,
		arg.KelasKode,
		arg.Level,
		arg.Jadwal,
		arg.Tipe,
		arg.Frekuensi,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriKeuangan = `-- name: UpdateSantriKeuangan :exec
UPDATE santri
SET infaq_terakhir = ?, keterangan_tidak_lanjut = ?,
    status = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriKeuanganParams struct {
	InfaqTerakhir         string
	KeteranganTidakLanjut string
	Status                string
	UpdatedAt             time.Time
	ID                    int64
}

func (q *Queries) UpdateSantriKeuangan(ctx context.Context, arg UpdateSantriKeuanganParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriKeuangan,
		arg.InfaqTerakhir,
		arg.KeteranganTidakLanjut,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSantriPertemuanAwal = `-- name: UpdateSantriPertemuanAwal :exec
UPDATE santri SET pertemuan_awal = ?, updated_at = ? WHERE id = ?
`

type UpdateSantriPertemuanAwalParams struct {
	PertemuanAwal int64
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) UpdateSantriPertemuanAwal(ctx context.Context, arg UpdateSantriPertemuanAwalParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriPertemuanAwal, arg.PertemuanAwal, arg.UpdatedAt, arg.ID)
	return err
}

const updateSantriStatus = `-- name: UpdateSantriStatus :exec
UPDATE santri SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateSantriStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateSantriStatus(ctx context.Context, arg UpdateSantriStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateSantriVoiceNote = `-- name: UpdateSantriVoiceNote :exec
UPDATE santri
SET voice_note_url = ?, keterangan_vn = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriVoiceNoteParams struct {
	VoiceNoteUrl string
	KeteranganVn string
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) UpdateSantriVoiceNote(ctx context.Context, arg UpdateSantriVoiceNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriVoiceNote,
		arg.VoiceNoteUrl,
		arg.KeteranganVn,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
