// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: santri_status.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createSantriStatusLog = `-- name: CreateSantriStatusLog :exec
INSERT INTO santri_status_log (
    santri_id, kelas_id, status_lama, status_baru, alasan, cuti_mulai, cuti_selesai, dibuat_oleh
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSantriStatusLogParams struct {
	SantriID    int64
	KelasID     sql.NullInt64
	StatusLama  string
	StatusBaru  string
	Alasan      string
	CutiMulai   string
	CutiSelesai string
	DibuatOleh  sql.NullInt64
}

func (q *Queries) CreateSantriStatusLog(ctx context.Context, arg CreateSantriStatusLogParams) error {
	_, err := q.db.ExecContext(ctx, createSantriStatusLog,
		arg.SantriID,
		arg.KelasID,
		arg.StatusLama,
		arg.StatusBaru,
		arg.Alasan,
		arg.CutiMulai,
		arg.CutiSelesai,
		arg.DibuatOleh,
	)
	return err
}

const getSantriRosterByKelasID = `-- name: GetSantriRosterByKelasID :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas, status_alasan, cuti_mulai, cuti_selesai FROM santri
WHERE kelas_id = ?
ORDER BY nama
`

// Semua santri di kelas lintas status, untuk tampilan Detail Kelas.
func (q *Queries) GetSantriRosterByKelasID(ctx context.Context, kelasID sql.NullInt64) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, getSantriRosterByKelasID, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
			&i.StatusAlasan,
			&i.CutiMulai,
			&i.CutiSelesai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantriCutiBerakhir = `-- name: ListSantriCutiBerakhir :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas, status_alasan, cuti_mulai, cuti_selesai FROM santri
WHERE status = 'cuti' AND cuti_selesai != '' AND cuti_selesai < CAST(?1 AS TEXT)
ORDER BY id
`

// cuti_selesai adalah hari terakhir cuti (YYYY-MM-DD).
func (q *Queries) ListSantriCutiBerakhir(ctx context.Context, hariIni string) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, listSantriCutiBerakhir, hariIni)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
			&i.StatusAlasan,
			&i.CutiMulai,
			&i.CutiSelesai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantriCutiTerjadwal = `-- name: ListSantriCutiTerjadwal :many
SELECT id, id_mahasantri, kelas_kode, nama, jenis_kelamin, nominal, tanggal_daftar, angkatan, usia, domisili, fu, tanggal_vn, hasil_vn, masuk_grup, mulai_belajar, jumlah, level, jadwal, guru, jadwal_catatan, infaq_terakhir, keterangan_tidak_lanjut, tipe, frekuensi, is_lengkap, kelas_id, status, created_by, created_at, updated_at, no_wa, voice_note_url, keterangan_vn, email, pertemuan_awal, angkatan_kelas, status_alasan, cuti_mulai, cuti_selesai FROM santri
WHERE status = 'aktif' AND cuti_mulai != '' AND cuti_mulai <= CAST(?1 AS TEXT)
ORDER BY id
`

// Santri aktif dengan cuti terjadwal yang tanggal mulainya sudah tiba.
func (q *Queries) ListSantriCutiTerjadwal(ctx context.Context, hariIni string) ([]Santri, error) {
	rows, err := q.db.QueryContext(ctx, listSantriCutiTerjadwal, hariIni)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Santri
	for rows.Next() {
		var i Santri
		if err := rows.Scan(
			&i.ID,
			&i.IDMahasantri,
			&i.KelasKode,
			&i.Nama,
			&i.JenisKelamin,
			&i.Nominal,
			&i.TanggalDaftar,
			&i.Angkatan,
			&i.Usia,
			&i.Domisili,
			&i.Fu,
			&i.TanggalVn,
			&i.HasilVn,
			&i.MasukGrup,
			&i.MulaiBelajar,
			&i.Jumlah,
			&i.Level,
			&i.Jadwal,
			&i.Guru,
			&i.JadwalCatatan,
			&i.InfaqTerakhir,
			&i.KeteranganTidakLanjut,
			&i.Tipe,
			&i.Frekuensi,
			&i.IsLengkap,
			&i.KelasID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NoWa,
			&i.VoiceNoteUrl,
			&i.KeteranganVn,
			&i.Email,
			&i.PertemuanAwal,
			&i.AngkatanKelas,
			&i.StatusAlasan,
			&i.CutiMulai,
			&i.CutiSelesai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSantriStatusLogByKelas = `-- name: ListSantriStatusLogByKelas :many
SELECT l.id, l.santri_id, s.nama AS santri_nama, l.status_lama, l.status_baru,
       l.alasan, l.cuti_mulai, l.cuti_selesai, COALESCE(u.name, '') AS dibuat_oleh_nama,
       l.created_at
FROM santri_status_log l
JOIN santri s ON s.id = l.santri_id
LEFT JOIN users u ON u.id = l.dibuat_oleh
WHERE l.kelas_id = ?
ORDER BY l.created_at DESC, l.id DESC
LIMIT 200
`

type ListSantriStatusLogByKelasRow struct {
	ID             int64
	SantriID       int64
	SantriNama     string
	StatusLama     string
	StatusBaru     string
	Alasan         string
	CutiMulai      string
	CutiSelesai    string
	DibuatOlehNama string
	CreatedAt      time.Time
}

func (q *Queries) ListSantriStatusLogByKelas(ctx context.Context, kelasID sql.NullInt64) ([]ListSantriStatusLogByKelasRow, error) {
	rows, err := q.db.QueryContext(ctx, listSantriStatusLogByKelas, kelasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSantriStatusLogByKelasRow
	for rows.Next() {
		var i ListSantriStatusLogByKelasRow
		if err := rows.Scan(
			&i.ID,
			&i.SantriID,
			&i.SantriNama,
			&i.StatusLama,
			&i.StatusBaru,
			&i.Alasan,
			&i.CutiMulai,
			&i.CutiSelesai,
			&i.DibuatOlehNama,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSantriStatusDetail = `-- name: UpdateSantriStatusDetail :exec
UPDATE santri
SET status = ?, status_alasan = ?, cuti_mulai = ?, cuti_selesai = ?, updated_at = ?
WHERE id = ?
`

type UpdateSantriStatusDetailParams struct {
	Status       string
	StatusAlasan string
	CutiMulai    string
	CutiSelesai  string
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) UpdateSantriStatusDetail(ctx context.Context, arg UpdateSantriStatusDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateSantriStatusDetail,
		arg.Status,
		arg.StatusAlasan,
		arg.CutiMulai,
		arg.CutiSelesai,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
