// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tagihan.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const batalkanTagihan = `-- name: BatalkanTagihan :exec
UPDATE tagihan
SET status = 'batal', catatan = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND status != 'lunas'
`

type BatalkanTagihanParams struct {
	Catatan string
	ID      int64
}

func (q *Queries) BatalkanTagihan(ctx context.Context, arg BatalkanTagihanParams) error {
	_, err := q.db.ExecContext(ctx, batalkanTagihan, arg.Catatan, arg.ID)
	return err
}

const countTagihanSantriBulan = `-- name: CountTagihanSantriBulan :one
SELECT COUNT(*) FROM tagihan WHERE santri_id = ? AND bulan_ke = ?
`

type CountTagihanSantriBulanParams struct {
	SantriID int64
	BulanKe  int64
}

func (q *Queries) CountTagihanSantriBulan(ctx context.Context, arg CountTagihanSantriBulanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagihanSantriBulan, arg.SantriID, arg.BulanKe)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagihanSantriPertemuan = `-- name: CountTagihanSantriPertemuan :one
SELECT COUNT(*) FROM tagihan WHERE santri_id = ? AND pertemuan_id = ?
`

type CountTagihanSantriPertemuanParams struct {
	SantriID    int64
	PertemuanID sql.NullInt64
}

func (q *Queries) CountTagihanSantriPertemuan(ctx context.Context, arg CountTagihanSantriPertemuanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagihanSantriPertemuan, arg.SantriID, arg.PertemuanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTagihan = `-- name: CreateTagihan :execresult
INSERT INTO tagihan (
    santri_id, kelas_id, pertemuan_id, bulan_ke, pertemuan_ke, nominal,
    tanggal_tagih, jatuh_tempo, angkatan_kelas
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type CreateTagihanParams struct {
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	AngkatanKelas string
}

func (q *Queries) CreateTagihan(ctx context.Context, arg CreateTagihanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTagihan,
		arg.SantriID,
		arg.KelasID,
		arg.PertemuanID,
		arg.BulanKe,
		arg.PertemuanKe,
		arg.Nominal,
		arg.TanggalTagih,
		arg.JatuhTempo,
		arg.AngkatanKelas,
	)
}

const getMaxBulanKeSantri = `-- name: GetMaxBulanKeSantri :one
SELECT CAST(COALESCE(MAX(bulan_ke), 0) AS INTEGER) FROM tagihan WHERE santri_id = ?
`

func (q *Queries) GetMaxBulanKeSantri(ctx context.Context, santriID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxBulanKeSantri, santriID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTagihanByID = `-- name: GetTagihanByID :one
SELECT t.id, t.santri_id, t.kelas_id, t.pertemuan_id, t.bulan_ke, t.pertemuan_ke, t.nominal, t.tanggal_tagih, t.jatuh_tempo, t.status, t.tanggal_bayar, t.metode, t.catatan, t.dicatat_oleh, t.fu_terakhir, t.fu_count, t.created_at, t.updated_at, t.angkatan_kelas, s.nama AS santri_nama, s.id_mahasantri, s.no_wa, s.angkatan,
       s.frekuensi, k.nama_kelas, COALESCE(g.nama, '') AS guru_nama
FROM tagihan t
JOIN santri s ON s.id = t.santri_id
LEFT JOIN kelas k ON k.id = t.kelas_id
LEFT JOIN guru g ON g.id = k.guru_id
WHERE t.id = ?
`

type GetTagihanByIDRow struct {
	ID            int64
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	Status        string
	TanggalBayar  sql.NullTime
	Metode        string
	Catatan       string
	DicatatOleh   sql.NullInt64
	FuTerakhir    sql.NullTime
	FuCount       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AngkatanKelas string
	SantriNama    string
	IDMahasantri  string
	NoWa          string
	Angkatan      string
	Frekuensi     string
	NamaKelas     sql.NullString
	GuruNama      string
}

func (q *Queries) GetTagihanByID(ctx context.Context, id int64) (GetTagihanByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTagihanByID, id)
	var i GetTagihanByIDRow
	err := row.Scan(
		&i.ID,
		&i.SantriID,
		&i.KelasID,
		&i.PertemuanID,
		&i.BulanKe,
		&i.PertemuanKe,
		&i.Nominal,
		&i.TanggalTagih,
		&i.JatuhTempo,
		&i.Status,
		&i.TanggalBayar,
		&i.Metode,
		&i.Catatan,
		&i.DicatatOleh,
		&i.FuTerakhir,
		&i.FuCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AngkatanKelas,
		&i.SantriNama,
		&i.IDMahasantri,
		&i.NoWa,
		&i.Angkatan,
		&i.Frekuensi,
		&i.NamaKelas,
		&i.GuruNama,
	)
	return i, err
}

const listPertemuanSelesai = `-- name: ListPertemuanSelesai :many
SELECT id, kelas_id, pertemuan_ke, tanggal, jam_mulai, jam_selesai, materi, catatan, is_reschedule, jadwal_semula, alasan_reschedule, is_badal, guru_pengganti_id, alasan_badal, status, dibuat_oleh, created_at, updated_at, level_nama, pertemuan_level_ke FROM pertemuan WHERE status = 'selesai' ORDER BY tanggal, id
`

func (q *Queries) ListPertemuanSelesai(ctx context.Context) ([]Pertemuan, error) {
	rows, err := q.db.QueryContext(ctx, listPertemuanSelesai)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pertemuan
	for rows.Next() {
		var i Pertemuan
		if err := rows.Scan(
			&i.ID,
			&i.KelasID,
			&i.PertemuanKe,
			&i.Tanggal,
			&i.JamMulai,
			&i.JamSelesai,
			&i.Materi,
			&i.Catatan,
			&i.IsReschedule,
			&i.JadwalSemula,
			&i.AlasanReschedule,
			&i.IsBadal,
			&i.GuruPenggantiID,
			&i.AlasanBadal,
			&i.Status,
			&i.DibuatOleh,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LevelNama,
			&i.PertemuanLevelKe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagihan = `-- name: ListTagihan :many
SELECT t.id, t.santri_id, t.kelas_id, t.pertemuan_id, t.bulan_ke, t.pertemuan_ke, t.nominal, t.tanggal_tagih, t.jatuh_tempo, t.status, t.tanggal_bayar, t.metode, t.catatan, t.dicatat_oleh, t.fu_terakhir, t.fu_count, t.created_at, t.updated_at, t.angkatan_kelas, s.nama AS santri_nama, s.id_mahasantri, s.no_wa, s.angkatan,
       s.frekuensi, s.jenis_kelamin, s.level, k.nama_kelas,
       COALESCE(g.nama, '') AS guru_nama
FROM tagihan t
JOIN santri s ON s.id = t.santri_id
LEFT JOIN kelas k ON k.id = t.kelas_id
LEFT JOIN guru g ON g.id = k.guru_id
WHERE (?1 IS NULL OR t.status = ?1)
  AND (?2 IS NULL OR t.kelas_id = ?2)
  AND (?3 = '' OR t.angkatan_kelas = ?3)
  AND (?4 IS NULL OR k.guru_id = ?4)
  AND (?5 = '' OR s.frekuensi = ?5)
  AND (?6 = '' OR s.level = ?6)
  AND (?7 = '' OR s.jenis_kelamin = ?7)
  AND (?8 IS NULL OR t.bulan_ke = ?8)
  AND (?9 IS NULL OR t.tanggal_tagih >= ?9)
  AND (?10 IS NULL OR t.tanggal_tagih <= ?10)
  AND (?11 = '' OR s.nama LIKE '%' || ?11 || '%' OR s.id_mahasantri LIKE '%' || ?11 || '%')
ORDER BY t.tanggal_tagih DESC, t.id DESC
`

type ListTagihanParams struct {
	Status        interface{}
	KelasID       interface{}
	AngkatanKelas interface{}
	GuruID        interface{}
	Frekuensi     interface{}
	Level         interface{}
	Gender        interface{}
	BulanKe       interface{}
	TanggalDari   interface{}
	TanggalSampai interface{}
	Search        interface{}
}

type ListTagihanRow struct {
	ID            int64
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	Status        string
	TanggalBayar  sql.NullTime
	Metode        string
	Catatan       string
	DicatatOleh   sql.NullInt64
	FuTerakhir    sql.NullTime
	FuCount       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AngkatanKelas string
	SantriNama    string
	IDMahasantri  string
	NoWa          string
	Angkatan      string
	Frekuensi     string
	JenisKelamin  string
	Level         string
	NamaKelas     sql.NullString
	GuruNama      string
}

func (q *Queries) ListTagihan(ctx context.Context, arg ListTagihanParams) ([]ListTagihanRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagihan,
		arg.Status,
		arg.KelasID,
		arg.AngkatanKelas,
		arg.GuruID,
		arg.Frekuensi,
		arg.Level,
		arg.Gender,
		arg.BulanKe,
		arg.TanggalDari,
		arg.TanggalSampai,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagihanRow
	for rows.Next() {
		var i ListTagihanRow
		if err := rows.Scan(
			&i.ID,
			&i.SantriID,
			&i.KelasID,
			&i.PertemuanID,
			&i.BulanKe,
			&i.PertemuanKe,
			&i.Nominal,
			&i.TanggalTagih,
			&i.JatuhTempo,
			&i.Status,
			&i.TanggalBayar,
			&i.Metode,
			&i.Catatan,
			&i.DicatatOleh,
			&i.FuTerakhir,
			&i.FuCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AngkatanKelas,
			&i.SantriNama,
			&i.IDMahasantri,
			&i.NoWa,
			&i.Angkatan,
			&i.Frekuensi,
			&i.JenisKelamin,
			&i.Level,
			&i.NamaKelas,
			&i.GuruNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagihanBelumBayar = `-- name: ListTagihanBelumBayar :many
SELECT t.id, t.santri_id, t.kelas_id, t.pertemuan_id, t.bulan_ke, t.pertemuan_ke, t.nominal, t.tanggal_tagih, t.jatuh_tempo, t.status, t.tanggal_bayar, t.metode, t.catatan, t.dicatat_oleh, t.fu_terakhir, t.fu_count, t.created_at, t.updated_at, t.angkatan_kelas, s.nama AS santri_nama, s.id_mahasantri, s.no_wa, s.angkatan,
       s.frekuensi, k.nama_kelas, COALESCE(g.nama, '') AS guru_nama
FROM tagihan t
JOIN santri s ON s.id = t.santri_id
LEFT JOIN kelas k ON k.id = t.kelas_id
LEFT JOIN guru g ON g.id = k.guru_id
WHERE t.status = 'belum_bayar' AND t.tanggal_tagih >= ? AND t.tanggal_tagih <= ?
ORDER BY t.tanggal_tagih DESC, t.id DESC
`

type ListTagihanBelumBayarParams struct {
	TanggalTagih   time.Time
	TanggalTagih_2 time.Time
}

type ListTagihanBelumBayarRow struct {
	ID            int64
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	Status        string
	TanggalBayar  sql.NullTime
	Metode        string
	Catatan       string
	DicatatOleh   sql.NullInt64
	FuTerakhir    sql.NullTime
	FuCount       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AngkatanKelas string
	SantriNama    string
	IDMahasantri  string
	NoWa          string
	Angkatan      string
	Frekuensi     string
	NamaKelas     sql.NullString
	GuruNama      string
}

func (q *Queries) ListTagihanBelumBayar(ctx context.Context, arg ListTagihanBelumBayarParams) ([]ListTagihanBelumBayarRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagihanBelumBayar, arg.TanggalTagih, arg.TanggalTagih_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagihanBelumBayarRow
	for rows.Next() {
		var i ListTagihanBelumBayarRow
		if err := rows.Scan(
			&i.ID,
			&i.SantriID,
			&i.KelasID,
			&i.PertemuanID,
			&i.BulanKe,
			&i.PertemuanKe,
			&i.Nominal,
			&i.TanggalTagih,
			&i.JatuhTempo,
			&i.Status,
			&i.TanggalBayar,
			&i.Metode,
			&i.Catatan,
			&i.DicatatOleh,
			&i.FuTerakhir,
			&i.FuCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AngkatanKelas,
			&i.SantriNama,
			&i.IDMahasantri,
			&i.NoWa,
			&i.Angkatan,
			&i.Frekuensi,
			&i.NamaKelas,
			&i.GuruNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagihanLunas = `-- name: ListTagihanLunas :many
SELECT t.id, t.santri_id, t.kelas_id, t.pertemuan_id, t.bulan_ke, t.pertemuan_ke, t.nominal, t.tanggal_tagih, t.jatuh_tempo, t.status, t.tanggal_bayar, t.metode, t.catatan, t.dicatat_oleh, t.fu_terakhir, t.fu_count, t.created_at, t.updated_at, t.angkatan_kelas, s.nama AS santri_nama, s.id_mahasantri, s.no_wa, s.angkatan,
       s.frekuensi, k.nama_kelas, COALESCE(g.nama, '') AS guru_nama
FROM tagihan t
JOIN santri s ON s.id = t.santri_id
LEFT JOIN kelas k ON k.id = t.kelas_id
LEFT JOIN guru g ON g.id = k.guru_id
WHERE t.status = 'lunas' AND t.tanggal_tagih >= ? AND t.tanggal_tagih <= ?
ORDER BY t.tanggal_tagih DESC, t.id DESC
`

type ListTagihanLunasParams struct {
	TanggalTagih   time.Time
	TanggalTagih_2 time.Time
}

type ListTagihanLunasRow struct {
	ID            int64
	SantriID      int64
	KelasID       sql.NullInt64
	PertemuanID   sql.NullInt64
	BulanKe       int64
	PertemuanKe   int64
	Nominal       int64
	TanggalTagih  time.Time
	JatuhTempo    sql.NullTime
	Status        string
	TanggalBayar  sql.NullTime
	Metode        string
	Catatan       string
	DicatatOleh   sql.NullInt64
	FuTerakhir    sql.NullTime
	FuCount       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AngkatanKelas string
	SantriNama    string
	IDMahasantri  string
	NoWa          string
	Angkatan      string
	Frekuensi     string
	NamaKelas     sql.NullString
	GuruNama      string
}

func (q *Queries) ListTagihanLunas(ctx context.Context, arg ListTagihanLunasParams) ([]ListTagihanLunasRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagihanLunas, arg.TanggalTagih, arg.TanggalTagih_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagihanLunasRow
	for rows.Next() {
		var i ListTagihanLunasRow
		if err := rows.Scan(
			&i.ID,
			&i.SantriID,
			&i.KelasID,
			&i.PertemuanID,
			&i.BulanKe,
			&i.PertemuanKe,
			&i.Nominal,
			&i.TanggalTagih,
			&i.JatuhTempo,
			&i.Status,
			&i.TanggalBayar,
			&i.Metode,
			&i.Catatan,
			&i.DicatatOleh,
			&i.FuTerakhir,
			&i.FuCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AngkatanKelas,
			&i.SantriNama,
			&i.IDMahasantri,
			&i.NoWa,
			&i.Angkatan,
			&i.Frekuensi,
			&i.NamaKelas,
			&i.GuruNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTagihanLunas = `-- name: MarkTagihanLunas :exec
UPDATE tagihan
SET status = 'lunas', tanggal_bayar = ?, metode = ?, catatan = ?, dicatat_oleh = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'belum_bayar'
`

type MarkTagihanLunasParams struct {
	TanggalBayar sql.NullTime
	Metode       string
	Catatan      string
	DicatatOleh  sql.NullInt64
	ID           int64
}

func (q *Queries) MarkTagihanLunas(ctx context.Context, arg MarkTagihanLunasParams) error {
	_, err := q.db.ExecContext(ctx, markTagihanLunas,
		arg.TanggalBayar,
		arg.Metode,
		arg.Catatan,
		arg.DicatatOleh,
		arg.ID,
	)
	return err
}

const ringkasanTagihanPeriode = `-- name: RingkasanTagihanPeriode :one
SELECT COUNT(*) AS total_tagihan,
       COALESCE(SUM(nominal), 0) AS nominal_tagihan,
       COALESCE(SUM(CASE WHEN status = 'lunas' THEN 1 ELSE 0 END), 0) AS total_lunas,
       COALESCE(SUM(CASE WHEN status = 'lunas' THEN nominal ELSE 0 END), 0) AS nominal_lunas,
       COALESCE(SUM(CASE WHEN status = 'belum_bayar' THEN 1 ELSE 0 END), 0) AS total_belum_bayar,
       COALESCE(SUM(CASE WHEN status = 'belum_bayar' THEN nominal ELSE 0 END), 0) AS nominal_belum_bayar,
       COALESCE(SUM(CASE WHEN status = 'belum_bayar' AND jatuh_tempo < DATE('now') THEN 1 ELSE 0 END), 0) AS total_terlambat
FROM tagihan
WHERE tanggal_tagih >= ? AND tanggal_tagih <= ?
`

type RingkasanTagihanPeriodeParams struct {
	TanggalTagih   time.Time
	TanggalTagih_2 time.Time
}

type RingkasanTagihanPeriodeRow struct {
	TotalTagihan      int64
	NominalTagihan    interface{}
	TotalLunas        interface{}
	NominalLunas      interface{}
	TotalBelumBayar   interface{}
	NominalBelumBayar interface{}
	TotalTerlambat    interface{}
}

func (q *Queries) RingkasanTagihanPeriode(ctx context.Context, arg RingkasanTagihanPeriodeParams) (RingkasanTagihanPeriodeRow, error) {
	row := q.db.QueryRowContext(ctx, ringkasanTagihanPeriode, arg.TanggalTagih, arg.TanggalTagih_2)
	var i RingkasanTagihanPeriodeRow
	err := row.Scan(
		&i.TotalTagihan,
		&i.NominalTagihan,
		&i.TotalLunas,
		&i.NominalLunas,
		&i.TotalBelumBayar,
		&i.NominalBelumBayar,
		&i.TotalTerlambat,
	)
	return i, err
}

const touchFollowUp = `-- name: TouchFollowUp :exec
UPDATE tagihan
SET fu_terakhir = CURRENT_TIMESTAMP, fu_count = fu_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchFollowUp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchFollowUp, id)
	return err
}
