// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package queries

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo_koordinator (judul, teknis, kebutuhan, deadline, pic, status, recurring, link_pendukung, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateTodoParams struct {
	Judul         string
	Teknis        string
	Kebutuhan     string
	Deadline      sql.NullTime
	Pic           string
	Status        string
	Recurring     string
	LinkPendukung string
	Catatan       string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Judul,
		arg.Teknis,
		arg.Kebutuhan,
		arg.Deadline,
		arg.Pic,
		arg.Status,
		arg.Recurring,
		arg.LinkPendukung,
		arg.Catatan,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todo_koordinator WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, judul, teknis, kebutuhan, deadline, pic, status, recurring, link_pendukung, catatan, created_at, updated_at FROM todo_koordinator WHERE id = ?
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (TodoKoordinator, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i TodoKoordinator
	err := row.Scan(
		&i.ID,
		&i.Judul,
		&i.Teknis,
		&i.Kebutuhan,
		&i.Deadline,
		&i.Pic,
		&i.Status,
		&i.Recurring,
		&i.LinkPendukung,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodo = `-- name: ListTodo :many
SELECT id, judul, teknis, kebutuhan, deadline, pic, status, recurring, link_pendukung, catatan, created_at, updated_at FROM todo_koordinator
ORDER BY
    CASE status WHEN 'belum' THEN 1 WHEN 'proses' THEN 2 WHEN 'selesai' THEN 3 ELSE 4 END,
    deadline IS NULL, deadline ASC, created_at DESC
`

func (q *Queries) ListTodo(ctx context.Context) ([]TodoKoordinator, error) {
	rows, err := q.db.QueryContext(ctx, listTodo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoKoordinator
	for rows.Next() {
		var i TodoKoordinator
		if err := rows.Scan(
			&i.ID,
			&i.Judul,
			&i.Teknis,
			&i.Kebutuhan,
			&i.Deadline,
			&i.Pic,
			&i.Status,
			&i.Recurring,
			&i.LinkPendukung,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTodoStatus = `-- name: SetTodoStatus :exec
UPDATE todo_koordinator SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetTodoStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetTodoStatus(ctx context.Context, arg SetTodoStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTodoStatus, arg.Status, arg.ID)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todo_koordinator SET judul = ?, teknis = ?, kebutuhan = ?, deadline = ?, pic = ?, status = ?, recurring = ?, link_pendukung = ?, catatan = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTodoParams struct {
	Judul         string
	Teknis        string
	Kebutuhan     string
	Deadline      sql.NullTime
	Pic           string
	Status        string
	Recurring     string
	LinkPendukung string
	Catatan       string
	ID            int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Judul,
		arg.Teknis,
		arg.Kebutuhan,
		arg.Deadline,
		arg.Pic,
		arg.Status,
		arg.Recurring,
		arg.LinkPendukung,
		arg.Catatan,
		arg.ID,
	)
	return err
}
