// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tsi.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countKalamInRange = `-- name: CountKalamInRange :one
SELECT COUNT(*) FROM kalam_bersanad WHERE tanggal >= ? AND tanggal <= ?
`

type CountKalamInRangeParams struct {
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountKalamInRange(ctx context.Context, arg CountKalamInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKalamInRange, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRapatTerlaksana = `-- name: CountRapatTerlaksana :one
SELECT COUNT(*) FROM rapat_guru WHERE status = 'terlaksana' AND tanggal >= ? AND tanggal <= ?
`

type CountRapatTerlaksanaParams struct {
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) CountRapatTerlaksana(ctx context.Context, arg CountRapatTerlaksanaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRapatTerlaksana, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTsiPeriode = `-- name: CreateTsiPeriode :one
INSERT INTO tsi_periode (guru_id, bulan, status) VALUES (?, ?, 'draft') RETURNING id
`

type CreateTsiPeriodeParams struct {
	GuruID int64
	Bulan  string
}

func (q *Queries) CreateTsiPeriode(ctx context.Context, arg CreateTsiPeriodeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTsiPeriode, arg.GuruID, arg.Bulan)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTsiNilai = `-- name: GetTsiNilai :one
SELECT id, periode_id, kriteria_id, nilai, is_override, alasan_override, catatan, updated_at FROM tsi_nilai WHERE periode_id = ? AND kriteria_id = ?
`

type GetTsiNilaiParams struct {
	PeriodeID  int64
	KriteriaID int64
}

func (q *Queries) GetTsiNilai(ctx context.Context, arg GetTsiNilaiParams) (TsiNilai, error) {
	row := q.db.QueryRowContext(ctx, getTsiNilai, arg.PeriodeID, arg.KriteriaID)
	var i TsiNilai
	err := row.Scan(
		&i.ID,
		&i.PeriodeID,
		&i.KriteriaID,
		&i.Nilai,
		&i.IsOverride,
		&i.AlasanOverride,
		&i.Catatan,
		&i.UpdatedAt,
	)
	return i, err
}

const getTsiPeriode = `-- name: GetTsiPeriode :one

SELECT id, guru_id, bulan, status, created_at, updated_at FROM tsi_periode WHERE guru_id = ? AND bulan = ?
`

type GetTsiPeriodeParams struct {
	GuruID int64
	Bulan  string
}

// ============ Periode ============
func (q *Queries) GetTsiPeriode(ctx context.Context, arg GetTsiPeriodeParams) (TsiPeriode, error) {
	row := q.db.QueryRowContext(ctx, getTsiPeriode, arg.GuruID, arg.Bulan)
	var i TsiPeriode
	err := row.Scan(
		&i.ID,
		&i.GuruID,
		&i.Bulan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTsiPeriodeByID = `-- name: GetTsiPeriodeByID :one
SELECT id, guru_id, bulan, status, created_at, updated_at FROM tsi_periode WHERE id = ?
`

func (q *Queries) GetTsiPeriodeByID(ctx context.Context, id int64) (TsiPeriode, error) {
	row := q.db.QueryRowContext(ctx, getTsiPeriodeByID, id)
	var i TsiPeriode
	err := row.Scan(
		&i.ID,
		&i.GuruID,
		&i.Bulan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTsiAudit = `-- name: InsertTsiAudit :exec
INSERT INTO tsi_audit (periode_id, kriteria_id, nilai_lama, nilai_baru, alasan, oleh)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTsiAuditParams struct {
	PeriodeID  int64
	KriteriaID int64
	NilaiLama  sql.NullFloat64
	NilaiBaru  sql.NullFloat64
	Alasan     string
	Oleh       sql.NullInt64
}

func (q *Queries) InsertTsiAudit(ctx context.Context, arg InsertTsiAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertTsiAudit,
		arg.PeriodeID,
		arg.KriteriaID,
		arg.NilaiLama,
		arg.NilaiBaru,
		arg.Alasan,
		arg.Oleh,
	)
	return err
}

const listTsiKriteria = `-- name: ListTsiKriteria :many

SELECT id, kategori, bobot, urutan, sumber, kode, nama FROM tsi_kriteria ORDER BY
    CASE kategori WHEN 'kompetensi' THEN 1 WHEN 'kepuasan' THEN 2 WHEN 'kedisiplinan' THEN 3 ELSE 4 END,
    urutan ASC
`

// ============ Kriteria ============
func (q *Queries) ListTsiKriteria(ctx context.Context) ([]TsiKriterium, error) {
	rows, err := q.db.QueryContext(ctx, listTsiKriteria)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TsiKriterium
	for rows.Next() {
		var i TsiKriterium
		if err := rows.Scan(
			&i.ID,
			&i.Kategori,
			&i.Bobot,
			&i.Urutan,
			&i.Sumber,
			&i.Kode,
			&i.Nama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTsiNilaiByPeriode = `-- name: ListTsiNilaiByPeriode :many

SELECT id, periode_id, kriteria_id, nilai, is_override, alasan_override, catatan, updated_at FROM tsi_nilai WHERE periode_id = ?
`

// ============ Nilai ============
func (q *Queries) ListTsiNilaiByPeriode(ctx context.Context, periodeID int64) ([]TsiNilai, error) {
	rows, err := q.db.QueryContext(ctx, listTsiNilaiByPeriode, periodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TsiNilai
	for rows.Next() {
		var i TsiNilai
		if err := rows.Scan(
			&i.ID,
			&i.PeriodeID,
			&i.KriteriaID,
			&i.Nilai,
			&i.IsOverride,
			&i.AlasanOverride,
			&i.Catatan,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTsiPeriodeByBulan = `-- name: ListTsiPeriodeByBulan :many
SELECT tp.id, tp.guru_id, tp.bulan, tp.status, tp.created_at, tp.updated_at, g.nama AS guru_nama, g.status AS guru_status
FROM tsi_periode tp JOIN guru g ON g.id = tp.guru_id
WHERE tp.bulan = ? ORDER BY g.nama ASC
`

type ListTsiPeriodeByBulanRow struct {
	ID         int64
	GuruID     int64
	Bulan      string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	GuruNama   string
	GuruStatus string
}

func (q *Queries) ListTsiPeriodeByBulan(ctx context.Context, bulan string) ([]ListTsiPeriodeByBulanRow, error) {
	rows, err := q.db.QueryContext(ctx, listTsiPeriodeByBulan, bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTsiPeriodeByBulanRow
	for rows.Next() {
		var i ListTsiPeriodeByBulanRow
		if err := rows.Scan(
			&i.ID,
			&i.GuruID,
			&i.Bulan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuruNama,
			&i.GuruStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTsiPeriodeStatus = `-- name: SetTsiPeriodeStatus :exec
UPDATE tsi_periode SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetTsiPeriodeStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetTsiPeriodeStatus(ctx context.Context, arg SetTsiPeriodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTsiPeriodeStatus, arg.Status, arg.ID)
	return err
}

const tsiCountBadal = `-- name: TsiCountBadal :one
SELECT COUNT(*) FROM pertemuan p JOIN kelas k ON k.id = p.kelas_id
WHERE k.guru_id = ? AND p.is_badal = 1 AND p.tanggal >= ? AND p.tanggal <= ?
`

type TsiCountBadalParams struct {
	GuruID    sql.NullInt64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) TsiCountBadal(ctx context.Context, arg TsiCountBadalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountBadal, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountPertemuanSelesai = `-- name: TsiCountPertemuanSelesai :one

SELECT COUNT(*) FROM pertemuan p JOIN kelas k ON k.id = p.kelas_id
WHERE k.guru_id = ? AND p.status = 'selesai' AND p.tanggal >= ? AND p.tanggal <= ?
`

type TsiCountPertemuanSelesaiParams struct {
	GuruID    sql.NullInt64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

// ============ Aggregates for automatic indicators (range = [start, end]) ============
func (q *Queries) TsiCountPertemuanSelesai(ctx context.Context, arg TsiCountPertemuanSelesaiParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountPertemuanSelesai, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountPertemuanTotal = `-- name: TsiCountPertemuanTotal :one
SELECT COUNT(*) FROM pertemuan p JOIN kelas k ON k.id = p.kelas_id
WHERE k.guru_id = ? AND p.tanggal >= ? AND p.tanggal <= ?
`

type TsiCountPertemuanTotalParams struct {
	GuruID    sql.NullInt64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) TsiCountPertemuanTotal(ctx context.Context, arg TsiCountPertemuanTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountPertemuanTotal, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountPertemuanWithAbsensi = `-- name: TsiCountPertemuanWithAbsensi :one
SELECT COUNT(*) FROM pertemuan p JOIN kelas k ON k.id = p.kelas_id
WHERE k.guru_id = ? AND p.status = 'selesai' AND p.tanggal >= ? AND p.tanggal <= ?
  AND EXISTS (SELECT 1 FROM absensi a WHERE a.pertemuan_id = p.id)
`

type TsiCountPertemuanWithAbsensiParams struct {
	GuruID    sql.NullInt64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) TsiCountPertemuanWithAbsensi(ctx context.Context, arg TsiCountPertemuanWithAbsensiParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountPertemuanWithAbsensi, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountReschedule = `-- name: TsiCountReschedule :one
SELECT COUNT(*) FROM pertemuan p JOIN kelas k ON k.id = p.kelas_id
WHERE k.guru_id = ? AND p.is_reschedule = 1 AND p.tanggal >= ? AND p.tanggal <= ?
`

type TsiCountRescheduleParams struct {
	GuruID    sql.NullInt64
	Tanggal   time.Time
	Tanggal_2 time.Time
}

func (q *Queries) TsiCountReschedule(ctx context.Context, arg TsiCountRescheduleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountReschedule, arg.GuruID, arg.Tanggal, arg.Tanggal_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountSantriTidakLanjut = `-- name: TsiCountSantriTidakLanjut :one
SELECT COUNT(*) FROM santri s JOIN kelas k ON k.id = s.kelas_id WHERE k.guru_id = ? AND s.status = 'tidak_lanjut'
`

func (q *Queries) TsiCountSantriTidakLanjut(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountSantriTidakLanjut, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tsiCountSantriTotal = `-- name: TsiCountSantriTotal :one
SELECT COUNT(*) FROM santri s JOIN kelas k ON k.id = s.kelas_id WHERE k.guru_id = ?
`

func (q *Queries) TsiCountSantriTotal(ctx context.Context, guruID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, tsiCountSantriTotal, guruID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertTsiNilai = `-- name: UpsertTsiNilai :exec
INSERT INTO tsi_nilai (periode_id, kriteria_id, nilai, is_override, alasan_override, catatan, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(periode_id, kriteria_id) DO UPDATE SET
    nilai = excluded.nilai,
    is_override = excluded.is_override,
    alasan_override = excluded.alasan_override,
    catatan = excluded.catatan,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertTsiNilaiParams struct {
	PeriodeID      int64
	KriteriaID     int64
	Nilai          sql.NullFloat64
	IsOverride     int64
	AlasanOverride string
	Catatan        string
}

func (q *Queries) UpsertTsiNilai(ctx context.Context, arg UpsertTsiNilaiParams) error {
	_, err := q.db.ExecContext(ctx, upsertTsiNilai,
		arg.PeriodeID,
		arg.KriteriaID,
		arg.Nilai,
		arg.IsOverride,
		arg.AlasanOverride,
		arg.Catatan,
	)
	return err
}
