// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_extend.sql

package queries

import (
	"context"
	"time"
)

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE id = ?
`

func (q *Queries) GetUserRole(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password, avatar, role, google_id, email_verified, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Avatar,
			&i.Role,
			&i.GoogleID,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ?, updated_at = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.UpdatedAt, arg.ID)
	return err
}
